version: "2.2"

services:
  nginx: 
    image: nginx
    container_name: gokusyun-nginx
    ports: 
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
  postgre:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=public
volumes:
  postgres-data:
    name: gokusyun_db