package com.logpose.ph2.api.dao.db.entity;

import java.util.Date;

public class Ph2BrandMasterEntity {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_brand_master.id
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_brand_master.name
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_brand_master.created_at
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	private Date createdAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_brand_master.updated_at
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	private Date updatedAt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_brand_master.id
	 * @return  the value of ph2_brand_master.id
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	public Integer getId()
		{
		return id;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_brand_master.id
	 * @param id  the value for ph2_brand_master.id
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	public void setId(Integer id)
		{
		this.id = id;
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_brand_master.name
	 * @return  the value of ph2_brand_master.name
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	public String getName()
		{
		return name;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_brand_master.name
	 * @param name  the value for ph2_brand_master.name
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	public void setName(String name)
		{
		this.name = name == null ? null : name.trim();
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_brand_master.created_at
	 * @return  the value of ph2_brand_master.created_at
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	public Date getCreatedAt()
		{
		return createdAt;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_brand_master.created_at
	 * @param createdAt  the value for ph2_brand_master.created_at
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	public void setCreatedAt(Date createdAt)
		{
		this.createdAt = createdAt;
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_brand_master.updated_at
	 * @return  the value of ph2_brand_master.updated_at
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	public Date getUpdatedAt()
		{
		return updatedAt;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_brand_master.updated_at
	 * @param updatedAt  the value for ph2_brand_master.updated_at
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	public void setUpdatedAt(Date updatedAt)
		{
		this.updatedAt = updatedAt;
		}
}