package com.logpose.ph2.api.dao.db.entity;

public class Ph2DashboardsRelEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ph2_dashboards_rel.user_id
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ph2_dashboards_rel.field_id
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    private Long fieldId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ph2_dashboards_rel.user_id
     *
     * @return the value of ph2_dashboards_rel.user_id
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ph2_dashboards_rel.user_id
     *
     * @param userId the value for ph2_dashboards_rel.user_id
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ph2_dashboards_rel.field_id
     *
     * @return the value of ph2_dashboards_rel.field_id
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    public Long getFieldId() {
        return fieldId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ph2_dashboards_rel.field_id
     *
     * @param fieldId the value for ph2_dashboards_rel.field_id
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    public void setFieldId(Long fieldId) {
        this.fieldId = fieldId;
    }
}