package com.logpose.ph2.api.dao.db.entity;

public class Ph2DailyBaseDataEntity {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_daily_base_data.day_id
	 * @mbg.generated
	 */
	private Long dayId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_daily_base_data.tm
	 * @mbg.generated
	 */
	private Float tm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_daily_base_data.average
	 * @mbg.generated
	 */
	private Float average;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_daily_base_data.cdd
	 * @mbg.generated
	 */
	private Double cdd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_daily_base_data.par
	 * @mbg.generated
	 */
	private Double par;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_daily_base_data.sun_time
	 * @mbg.generated
	 */
	private Long sunTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_daily_base_data.day_id
	 * @return  the value of ph2_daily_base_data.day_id
	 * @mbg.generated
	 */
	public Long getDayId()
		{
		return dayId;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_daily_base_data.day_id
	 * @param dayId  the value for ph2_daily_base_data.day_id
	 * @mbg.generated
	 */
	public void setDayId(Long dayId)
		{
		this.dayId = dayId;
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_daily_base_data.tm
	 * @return  the value of ph2_daily_base_data.tm
	 * @mbg.generated
	 */
	public Float getTm()
		{
		return tm;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_daily_base_data.tm
	 * @param tm  the value for ph2_daily_base_data.tm
	 * @mbg.generated
	 */
	public void setTm(Float tm)
		{
		this.tm = tm;
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_daily_base_data.average
	 * @return  the value of ph2_daily_base_data.average
	 * @mbg.generated
	 */
	public Float getAverage()
		{
		return average;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_daily_base_data.average
	 * @param average  the value for ph2_daily_base_data.average
	 * @mbg.generated
	 */
	public void setAverage(Float average)
		{
		this.average = average;
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_daily_base_data.cdd
	 * @return  the value of ph2_daily_base_data.cdd
	 * @mbg.generated
	 */
	public Double getCdd()
		{
		return cdd;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_daily_base_data.cdd
	 * @param cdd  the value for ph2_daily_base_data.cdd
	 * @mbg.generated
	 */
	public void setCdd(Double cdd)
		{
		this.cdd = cdd;
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_daily_base_data.par
	 * @return  the value of ph2_daily_base_data.par
	 * @mbg.generated
	 */
	public Double getPar()
		{
		return par;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_daily_base_data.par
	 * @param par  the value for ph2_daily_base_data.par
	 * @mbg.generated
	 */
	public void setPar(Double par)
		{
		this.par = par;
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_daily_base_data.sun_time
	 * @return  the value of ph2_daily_base_data.sun_time
	 * @mbg.generated
	 */
	public Long getSunTime()
		{
		return sunTime;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_daily_base_data.sun_time
	 * @param sunTime  the value for ph2_daily_base_data.sun_time
	 * @mbg.generated
	 */
	public void setSunTime(Long sunTime)
		{
		this.sunTime = sunTime;
		}
}