package com.logpose.ph2.api.dao.db.entity;

import java.util.Date;

public class Ph2DeviceDayEntity {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_device_day.id
	 * @mbg.generated  Thu Jul 20 13:52:34 JST 2023
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_device_day.device_id
	 * @mbg.generated  Thu Jul 20 13:52:34 JST 2023
	 */
	private Long deviceId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_device_day.date
	 * @mbg.generated  Thu Jul 20 13:52:34 JST 2023
	 */
	private Date date;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_device_day.year
	 * @mbg.generated  Thu Jul 20 13:52:34 JST 2023
	 */
	private Short year;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_device_day.lapse_day
	 * @mbg.generated  Thu Jul 20 13:52:34 JST 2023
	 */
	private Short lapseDay;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_device_day.has_real
	 * @mbg.generated  Thu Jul 20 13:52:34 JST 2023
	 */
	private Boolean hasReal;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_device_day.id
	 * @return  the value of ph2_device_day.id
	 * @mbg.generated  Thu Jul 20 13:52:34 JST 2023
	 */
	public Long getId()
		{
		return id;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_device_day.id
	 * @param id  the value for ph2_device_day.id
	 * @mbg.generated  Thu Jul 20 13:52:34 JST 2023
	 */
	public void setId(Long id)
		{
		this.id = id;
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_device_day.device_id
	 * @return  the value of ph2_device_day.device_id
	 * @mbg.generated  Thu Jul 20 13:52:34 JST 2023
	 */
	public Long getDeviceId()
		{
		return deviceId;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_device_day.device_id
	 * @param deviceId  the value for ph2_device_day.device_id
	 * @mbg.generated  Thu Jul 20 13:52:34 JST 2023
	 */
	public void setDeviceId(Long deviceId)
		{
		this.deviceId = deviceId;
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_device_day.date
	 * @return  the value of ph2_device_day.date
	 * @mbg.generated  Thu Jul 20 13:52:34 JST 2023
	 */
	public Date getDate()
		{
		return date;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_device_day.date
	 * @param date  the value for ph2_device_day.date
	 * @mbg.generated  Thu Jul 20 13:52:34 JST 2023
	 */
	public void setDate(Date date)
		{
		this.date = date;
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_device_day.year
	 * @return  the value of ph2_device_day.year
	 * @mbg.generated  Thu Jul 20 13:52:34 JST 2023
	 */
	public Short getYear()
		{
		return year;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_device_day.year
	 * @param year  the value for ph2_device_day.year
	 * @mbg.generated  Thu Jul 20 13:52:34 JST 2023
	 */
	public void setYear(Short year)
		{
		this.year = year;
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_device_day.lapse_day
	 * @return  the value of ph2_device_day.lapse_day
	 * @mbg.generated  Thu Jul 20 13:52:34 JST 2023
	 */
	public Short getLapseDay()
		{
		return lapseDay;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_device_day.lapse_day
	 * @param lapseDay  the value for ph2_device_day.lapse_day
	 * @mbg.generated  Thu Jul 20 13:52:34 JST 2023
	 */
	public void setLapseDay(Short lapseDay)
		{
		this.lapseDay = lapseDay;
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_device_day.has_real
	 * @return  the value of ph2_device_day.has_real
	 * @mbg.generated  Thu Jul 20 13:52:34 JST 2023
	 */
	public Boolean getHasReal()
		{
		return hasReal;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_device_day.has_real
	 * @param hasReal  the value for ph2_device_day.has_real
	 * @mbg.generated  Thu Jul 20 13:52:34 JST 2023
	 */
	public void setHasReal(Boolean hasReal)
		{
		this.hasReal = hasReal;
		}
}