package com.logpose.ph2.api.dao.db.entity;

import java.util.ArrayList;
import java.util.List;

public class Ph2DashBoardSensorsEntityExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ph2_dashboard_sensors
	 * @mbg.generated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ph2_dashboard_sensors
	 * @mbg.generated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ph2_dashboard_sensors
	 * @mbg.generated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_dashboard_sensors
	 * @mbg.generated
	 */
	public Ph2DashBoardSensorsEntityExample()
		{
		oredCriteria = new ArrayList<>();
		}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_dashboard_sensors
	 * @mbg.generated
	 */
	public void setOrderByClause(String orderByClause)
		{
		this.orderByClause = orderByClause;
		}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_dashboard_sensors
	 * @mbg.generated
	 */
	public String getOrderByClause()
		{
		return orderByClause;
		}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_dashboard_sensors
	 * @mbg.generated
	 */
	public void setDistinct(boolean distinct)
		{
		this.distinct = distinct;
		}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_dashboard_sensors
	 * @mbg.generated
	 */
	public boolean isDistinct()
		{
		return distinct;
		}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_dashboard_sensors
	 * @mbg.generated
	 */
	public List<Criteria> getOredCriteria()
		{
		return oredCriteria;
		}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_dashboard_sensors
	 * @mbg.generated
	 */
	public void or(Criteria criteria)
		{
		oredCriteria.add(criteria);
		}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_dashboard_sensors
	 * @mbg.generated
	 */
	public Criteria or()
		{
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
		}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_dashboard_sensors
	 * @mbg.generated
	 */
	public Criteria createCriteria()
		{
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0)
			{
			oredCriteria.add(criteria);
			}
		return criteria;
		}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_dashboard_sensors
	 * @mbg.generated
	 */
	protected Criteria createCriteriaInternal()
		{
		Criteria criteria = new Criteria();
		return criteria;
		}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_dashboard_sensors
	 * @mbg.generated
	 */
	public void clear()
		{
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
		}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table ph2_dashboard_sensors
	 * @mbg.generated
	 */
	protected abstract static class GeneratedCriteria
		{
		protected List<Criterion> criteria;

		protected GeneratedCriteria()
			{
			super();
			criteria = new ArrayList<>();
			}

		public boolean isValid()
			{
			return criteria.size() > 0;
			}

		public List<Criterion> getAllCriteria()
			{
			return criteria;
			}

		public List<Criterion> getCriteria()
			{
			return criteria;
			}

		protected void addCriterion(String condition)
			{
			if (condition == null)
				{
				throw new RuntimeException("Value for condition cannot be null");
				}
			criteria.add(new Criterion(condition));
			}

		protected void addCriterion(String condition, Object value, String property)
			{
			if (value == null)
				{
				throw new RuntimeException("Value for " + property + " cannot be null");
				}
			criteria.add(new Criterion(condition, value));
			}

		protected void addCriterion(String condition, Object value1, Object value2, String property)
			{
			if (value1 == null || value2 == null)
				{
				throw new RuntimeException("Between values for " + property + " cannot be null");
				}
			criteria.add(new Criterion(condition, value1, value2));
			}

		public Criteria andSensorIdIsNull()
			{
			addCriterion("sensor_id is null");
			return (Criteria) this;
			}

		public Criteria andSensorIdIsNotNull()
			{
			addCriterion("sensor_id is not null");
			return (Criteria) this;
			}

		public Criteria andSensorIdEqualTo(Long value)
			{
			addCriterion("sensor_id =", value, "sensorId");
			return (Criteria) this;
			}

		public Criteria andSensorIdNotEqualTo(Long value)
			{
			addCriterion("sensor_id <>", value, "sensorId");
			return (Criteria) this;
			}

		public Criteria andSensorIdGreaterThan(Long value)
			{
			addCriterion("sensor_id >", value, "sensorId");
			return (Criteria) this;
			}

		public Criteria andSensorIdGreaterThanOrEqualTo(Long value)
			{
			addCriterion("sensor_id >=", value, "sensorId");
			return (Criteria) this;
			}

		public Criteria andSensorIdLessThan(Long value)
			{
			addCriterion("sensor_id <", value, "sensorId");
			return (Criteria) this;
			}

		public Criteria andSensorIdLessThanOrEqualTo(Long value)
			{
			addCriterion("sensor_id <=", value, "sensorId");
			return (Criteria) this;
			}

		public Criteria andSensorIdIn(List<Long> values)
			{
			addCriterion("sensor_id in", values, "sensorId");
			return (Criteria) this;
			}

		public Criteria andSensorIdNotIn(List<Long> values)
			{
			addCriterion("sensor_id not in", values, "sensorId");
			return (Criteria) this;
			}

		public Criteria andSensorIdBetween(Long value1, Long value2)
			{
			addCriterion("sensor_id between", value1, value2, "sensorId");
			return (Criteria) this;
			}

		public Criteria andSensorIdNotBetween(Long value1, Long value2)
			{
			addCriterion("sensor_id not between", value1, value2, "sensorId");
			return (Criteria) this;
			}

		public Criteria andDisplayNoIsNull()
			{
			addCriterion("display_no is null");
			return (Criteria) this;
			}

		public Criteria andDisplayNoIsNotNull()
			{
			addCriterion("display_no is not null");
			return (Criteria) this;
			}

		public Criteria andDisplayNoEqualTo(Long value)
			{
			addCriterion("display_no =", value, "displayNo");
			return (Criteria) this;
			}

		public Criteria andDisplayNoNotEqualTo(Long value)
			{
			addCriterion("display_no <>", value, "displayNo");
			return (Criteria) this;
			}

		public Criteria andDisplayNoGreaterThan(Long value)
			{
			addCriterion("display_no >", value, "displayNo");
			return (Criteria) this;
			}

		public Criteria andDisplayNoGreaterThanOrEqualTo(Long value)
			{
			addCriterion("display_no >=", value, "displayNo");
			return (Criteria) this;
			}

		public Criteria andDisplayNoLessThan(Long value)
			{
			addCriterion("display_no <", value, "displayNo");
			return (Criteria) this;
			}

		public Criteria andDisplayNoLessThanOrEqualTo(Long value)
			{
			addCriterion("display_no <=", value, "displayNo");
			return (Criteria) this;
			}

		public Criteria andDisplayNoIn(List<Long> values)
			{
			addCriterion("display_no in", values, "displayNo");
			return (Criteria) this;
			}

		public Criteria andDisplayNoNotIn(List<Long> values)
			{
			addCriterion("display_no not in", values, "displayNo");
			return (Criteria) this;
			}

		public Criteria andDisplayNoBetween(Long value1, Long value2)
			{
			addCriterion("display_no between", value1, value2, "displayNo");
			return (Criteria) this;
			}

		public Criteria andDisplayNoNotBetween(Long value1, Long value2)
			{
			addCriterion("display_no not between", value1, value2, "displayNo");
			return (Criteria) this;
			}
		}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table ph2_dashboard_sensors
	 * @mbg.generated
	 */
	public static class Criterion
		{
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition()
			{
			return condition;
			}

		public Object getValue()
			{
			return value;
			}

		public Object getSecondValue()
			{
			return secondValue;
			}

		public boolean isNoValue()
			{
			return noValue;
			}

		public boolean isSingleValue()
			{
			return singleValue;
			}

		public boolean isBetweenValue()
			{
			return betweenValue;
			}

		public boolean isListValue()
			{
			return listValue;
			}

		public String getTypeHandler()
			{
			return typeHandler;
			}

		protected Criterion(String condition)
			{
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
			}

		protected Criterion(String condition, Object value, String typeHandler)
			{
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>)
				{
				this.listValue = true;
				}
			else
				{
				this.singleValue = true;
				}
			}

		protected Criterion(String condition, Object value)
			{
			this(condition, value, null);
			}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler)
			{
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
			}

		protected Criterion(String condition, Object value, Object secondValue)
			{
			this(condition, value, secondValue, null);
			}
		}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ph2_dashboard_sensors
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }
}