package com.logpose.ph2.api.dao.db.entity;

public class Ph2DashBoardSensorsEntity {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_dashboard_sensors.sensor_id
	 * @mbg.generated
	 */
	private Long sensorId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_dashboard_sensors.display_no
	 * @mbg.generated
	 */
	private Long displayNo;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_dashboard_sensors.sensor_id
	 * @return  the value of ph2_dashboard_sensors.sensor_id
	 * @mbg.generated
	 */
	public Long getSensorId()
		{
		return sensorId;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_dashboard_sensors.sensor_id
	 * @param sensorId  the value for ph2_dashboard_sensors.sensor_id
	 * @mbg.generated
	 */
	public void setSensorId(Long sensorId)
		{
		this.sensorId = sensorId;
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_dashboard_sensors.display_no
	 * @return  the value of ph2_dashboard_sensors.display_no
	 * @mbg.generated
	 */
	public Long getDisplayNo()
		{
		return displayNo;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_dashboard_sensors.display_no
	 * @param displayNo  the value for ph2_dashboard_sensors.display_no
	 * @mbg.generated
	 */
	public void setDisplayNo(Long displayNo)
		{
		this.displayNo = displayNo;
		}
}