package com.logpose.ph2.api.dao.db.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class Ph2MessagesEntityExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ph2_messages
	 * @mbg.generated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ph2_messages
	 * @mbg.generated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ph2_messages
	 * @mbg.generated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_messages
	 * @mbg.generated
	 */
	public Ph2MessagesEntityExample()
		{
		oredCriteria = new ArrayList<>();
		}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_messages
	 * @mbg.generated
	 */
	public void setOrderByClause(String orderByClause)
		{
		this.orderByClause = orderByClause;
		}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_messages
	 * @mbg.generated
	 */
	public String getOrderByClause()
		{
		return orderByClause;
		}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_messages
	 * @mbg.generated
	 */
	public void setDistinct(boolean distinct)
		{
		this.distinct = distinct;
		}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_messages
	 * @mbg.generated
	 */
	public boolean isDistinct()
		{
		return distinct;
		}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_messages
	 * @mbg.generated
	 */
	public List<Criteria> getOredCriteria()
		{
		return oredCriteria;
		}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_messages
	 * @mbg.generated
	 */
	public void or(Criteria criteria)
		{
		oredCriteria.add(criteria);
		}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_messages
	 * @mbg.generated
	 */
	public Criteria or()
		{
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
		}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_messages
	 * @mbg.generated
	 */
	public Criteria createCriteria()
		{
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0)
			{
			oredCriteria.add(criteria);
			}
		return criteria;
		}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_messages
	 * @mbg.generated
	 */
	protected Criteria createCriteriaInternal()
		{
		Criteria criteria = new Criteria();
		return criteria;
		}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_messages
	 * @mbg.generated
	 */
	public void clear()
		{
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
		}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table ph2_messages
	 * @mbg.generated
	 */
	protected abstract static class GeneratedCriteria
		{
		protected List<Criterion> criteria;

		protected GeneratedCriteria()
			{
			super();
			criteria = new ArrayList<>();
			}

		public boolean isValid()
			{
			return criteria.size() > 0;
			}

		public List<Criterion> getAllCriteria()
			{
			return criteria;
			}

		public List<Criterion> getCriteria()
			{
			return criteria;
			}

		protected void addCriterion(String condition)
			{
			if (condition == null)
				{
				throw new RuntimeException("Value for condition cannot be null");
				}
			criteria.add(new Criterion(condition));
			}

		protected void addCriterion(String condition, Object value, String property)
			{
			if (value == null)
				{
				throw new RuntimeException("Value for " + property + " cannot be null");
				}
			criteria.add(new Criterion(condition, value));
			}

		protected void addCriterion(String condition, Object value1, Object value2, String property)
			{
			if (value1 == null || value2 == null)
				{
				throw new RuntimeException("Between values for " + property + " cannot be null");
				}
			criteria.add(new Criterion(condition, value1, value2));
			}

		public Criteria andSigfoxIdIsNull()
			{
			addCriterion("sigfox_id is null");
			return (Criteria) this;
			}

		public Criteria andSigfoxIdIsNotNull()
			{
			addCriterion("sigfox_id is not null");
			return (Criteria) this;
			}

		public Criteria andSigfoxIdEqualTo(String value)
			{
			addCriterion("sigfox_id =", value, "sigfoxId");
			return (Criteria) this;
			}

		public Criteria andSigfoxIdNotEqualTo(String value)
			{
			addCriterion("sigfox_id <>", value, "sigfoxId");
			return (Criteria) this;
			}

		public Criteria andSigfoxIdGreaterThan(String value)
			{
			addCriterion("sigfox_id >", value, "sigfoxId");
			return (Criteria) this;
			}

		public Criteria andSigfoxIdGreaterThanOrEqualTo(String value)
			{
			addCriterion("sigfox_id >=", value, "sigfoxId");
			return (Criteria) this;
			}

		public Criteria andSigfoxIdLessThan(String value)
			{
			addCriterion("sigfox_id <", value, "sigfoxId");
			return (Criteria) this;
			}

		public Criteria andSigfoxIdLessThanOrEqualTo(String value)
			{
			addCriterion("sigfox_id <=", value, "sigfoxId");
			return (Criteria) this;
			}

		public Criteria andSigfoxIdLike(String value)
			{
			addCriterion("sigfox_id like", value, "sigfoxId");
			return (Criteria) this;
			}

		public Criteria andSigfoxIdNotLike(String value)
			{
			addCriterion("sigfox_id not like", value, "sigfoxId");
			return (Criteria) this;
			}

		public Criteria andSigfoxIdIn(List<String> values)
			{
			addCriterion("sigfox_id in", values, "sigfoxId");
			return (Criteria) this;
			}

		public Criteria andSigfoxIdNotIn(List<String> values)
			{
			addCriterion("sigfox_id not in", values, "sigfoxId");
			return (Criteria) this;
			}

		public Criteria andSigfoxIdBetween(String value1, String value2)
			{
			addCriterion("sigfox_id between", value1, value2, "sigfoxId");
			return (Criteria) this;
			}

		public Criteria andSigfoxIdNotBetween(String value1, String value2)
			{
			addCriterion("sigfox_id not between", value1, value2, "sigfoxId");
			return (Criteria) this;
			}

		public Criteria andSeqIsNull()
			{
			addCriterion("seq is null");
			return (Criteria) this;
			}

		public Criteria andSeqIsNotNull()
			{
			addCriterion("seq is not null");
			return (Criteria) this;
			}

		public Criteria andSeqEqualTo(Integer value)
			{
			addCriterion("seq =", value, "seq");
			return (Criteria) this;
			}

		public Criteria andSeqNotEqualTo(Integer value)
			{
			addCriterion("seq <>", value, "seq");
			return (Criteria) this;
			}

		public Criteria andSeqGreaterThan(Integer value)
			{
			addCriterion("seq >", value, "seq");
			return (Criteria) this;
			}

		public Criteria andSeqGreaterThanOrEqualTo(Integer value)
			{
			addCriterion("seq >=", value, "seq");
			return (Criteria) this;
			}

		public Criteria andSeqLessThan(Integer value)
			{
			addCriterion("seq <", value, "seq");
			return (Criteria) this;
			}

		public Criteria andSeqLessThanOrEqualTo(Integer value)
			{
			addCriterion("seq <=", value, "seq");
			return (Criteria) this;
			}

		public Criteria andSeqIn(List<Integer> values)
			{
			addCriterion("seq in", values, "seq");
			return (Criteria) this;
			}

		public Criteria andSeqNotIn(List<Integer> values)
			{
			addCriterion("seq not in", values, "seq");
			return (Criteria) this;
			}

		public Criteria andSeqBetween(Integer value1, Integer value2)
			{
			addCriterion("seq between", value1, value2, "seq");
			return (Criteria) this;
			}

		public Criteria andSeqNotBetween(Integer value1, Integer value2)
			{
			addCriterion("seq not between", value1, value2, "seq");
			return (Criteria) this;
			}

		public Criteria andCastedAtIsNull()
			{
			addCriterion("casted_at is null");
			return (Criteria) this;
			}

		public Criteria andCastedAtIsNotNull()
			{
			addCriterion("casted_at is not null");
			return (Criteria) this;
			}

		public Criteria andCastedAtEqualTo(Date value)
			{
			addCriterion("casted_at =", value, "castedAt");
			return (Criteria) this;
			}

		public Criteria andCastedAtNotEqualTo(Date value)
			{
			addCriterion("casted_at <>", value, "castedAt");
			return (Criteria) this;
			}

		public Criteria andCastedAtGreaterThan(Date value)
			{
			addCriterion("casted_at >", value, "castedAt");
			return (Criteria) this;
			}

		public Criteria andCastedAtGreaterThanOrEqualTo(Date value)
			{
			addCriterion("casted_at >=", value, "castedAt");
			return (Criteria) this;
			}

		public Criteria andCastedAtLessThan(Date value)
			{
			addCriterion("casted_at <", value, "castedAt");
			return (Criteria) this;
			}

		public Criteria andCastedAtLessThanOrEqualTo(Date value)
			{
			addCriterion("casted_at <=", value, "castedAt");
			return (Criteria) this;
			}

		public Criteria andCastedAtIn(List<Date> values)
			{
			addCriterion("casted_at in", values, "castedAt");
			return (Criteria) this;
			}

		public Criteria andCastedAtNotIn(List<Date> values)
			{
			addCriterion("casted_at not in", values, "castedAt");
			return (Criteria) this;
			}

		public Criteria andCastedAtBetween(Date value1, Date value2)
			{
			addCriterion("casted_at between", value1, value2, "castedAt");
			return (Criteria) this;
			}

		public Criteria andCastedAtNotBetween(Date value1, Date value2)
			{
			addCriterion("casted_at not between", value1, value2, "castedAt");
			return (Criteria) this;
			}

		public Criteria andRawIsNull()
			{
			addCriterion("raw is null");
			return (Criteria) this;
			}

		public Criteria andRawIsNotNull()
			{
			addCriterion("raw is not null");
			return (Criteria) this;
			}

		public Criteria andRawEqualTo(String value)
			{
			addCriterion("raw =", value, "raw");
			return (Criteria) this;
			}

		public Criteria andRawNotEqualTo(String value)
			{
			addCriterion("raw <>", value, "raw");
			return (Criteria) this;
			}

		public Criteria andRawGreaterThan(String value)
			{
			addCriterion("raw >", value, "raw");
			return (Criteria) this;
			}

		public Criteria andRawGreaterThanOrEqualTo(String value)
			{
			addCriterion("raw >=", value, "raw");
			return (Criteria) this;
			}

		public Criteria andRawLessThan(String value)
			{
			addCriterion("raw <", value, "raw");
			return (Criteria) this;
			}

		public Criteria andRawLessThanOrEqualTo(String value)
			{
			addCriterion("raw <=", value, "raw");
			return (Criteria) this;
			}

		public Criteria andRawLike(String value)
			{
			addCriterion("raw like", value, "raw");
			return (Criteria) this;
			}

		public Criteria andRawNotLike(String value)
			{
			addCriterion("raw not like", value, "raw");
			return (Criteria) this;
			}

		public Criteria andRawIn(List<String> values)
			{
			addCriterion("raw in", values, "raw");
			return (Criteria) this;
			}

		public Criteria andRawNotIn(List<String> values)
			{
			addCriterion("raw not in", values, "raw");
			return (Criteria) this;
			}

		public Criteria andRawBetween(String value1, String value2)
			{
			addCriterion("raw between", value1, value2, "raw");
			return (Criteria) this;
			}

		public Criteria andRawNotBetween(String value1, String value2)
			{
			addCriterion("raw not between", value1, value2, "raw");
			return (Criteria) this;
			}
		}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table ph2_messages
	 * @mbg.generated
	 */
	public static class Criterion
		{
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition()
			{
			return condition;
			}

		public Object getValue()
			{
			return value;
			}

		public Object getSecondValue()
			{
			return secondValue;
			}

		public boolean isNoValue()
			{
			return noValue;
			}

		public boolean isSingleValue()
			{
			return singleValue;
			}

		public boolean isBetweenValue()
			{
			return betweenValue;
			}

		public boolean isListValue()
			{
			return listValue;
			}

		public String getTypeHandler()
			{
			return typeHandler;
			}

		protected Criterion(String condition)
			{
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
			}

		protected Criterion(String condition, Object value, String typeHandler)
			{
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>)
				{
				this.listValue = true;
				}
			else
				{
				this.singleValue = true;
				}
			}

		protected Criterion(String condition, Object value)
			{
			this(condition, value, null);
			}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler)
			{
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
			}

		protected Criterion(String condition, Object value, Object secondValue)
			{
			this(condition, value, secondValue, null);
			}
		}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ph2_messages
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }
}