package com.logpose.ph2.api.dao.db.entity;

import java.util.Date;

public class Ph2OauthEntity {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_oauth.user_id
	 * @mbg.generated
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_oauth.token
	 * @mbg.generated
	 */
	private String token;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_oauth.load_time
	 * @mbg.generated
	 */
	private Date loadTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_oauth.check_time
	 * @mbg.generated
	 */
	private Date checkTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_oauth.expires_in
	 * @mbg.generated
	 */
	private Long expiresIn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_oauth.refresh_token
	 * @mbg.generated
	 */
	private String refreshToken;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_oauth.access_token
	 * @mbg.generated
	 */
	private String accessToken;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_oauth.user_id
	 * @return  the value of ph2_oauth.user_id
	 * @mbg.generated
	 */
	public String getUserId()
		{
		return userId;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_oauth.user_id
	 * @param userId  the value for ph2_oauth.user_id
	 * @mbg.generated
	 */
	public void setUserId(String userId)
		{
		this.userId = userId == null ? null : userId.trim();
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_oauth.token
	 * @return  the value of ph2_oauth.token
	 * @mbg.generated
	 */
	public String getToken()
		{
		return token;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_oauth.token
	 * @param token  the value for ph2_oauth.token
	 * @mbg.generated
	 */
	public void setToken(String token)
		{
		this.token = token == null ? null : token.trim();
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_oauth.load_time
	 * @return  the value of ph2_oauth.load_time
	 * @mbg.generated
	 */
	public Date getLoadTime()
		{
		return loadTime;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_oauth.load_time
	 * @param loadTime  the value for ph2_oauth.load_time
	 * @mbg.generated
	 */
	public void setLoadTime(Date loadTime)
		{
		this.loadTime = loadTime;
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_oauth.check_time
	 * @return  the value of ph2_oauth.check_time
	 * @mbg.generated
	 */
	public Date getCheckTime()
		{
		return checkTime;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_oauth.check_time
	 * @param checkTime  the value for ph2_oauth.check_time
	 * @mbg.generated
	 */
	public void setCheckTime(Date checkTime)
		{
		this.checkTime = checkTime;
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_oauth.expires_in
	 * @return  the value of ph2_oauth.expires_in
	 * @mbg.generated
	 */
	public Long getExpiresIn()
		{
		return expiresIn;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_oauth.expires_in
	 * @param expiresIn  the value for ph2_oauth.expires_in
	 * @mbg.generated
	 */
	public void setExpiresIn(Long expiresIn)
		{
		this.expiresIn = expiresIn;
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_oauth.refresh_token
	 * @return  the value of ph2_oauth.refresh_token
	 * @mbg.generated
	 */
	public String getRefreshToken()
		{
		return refreshToken;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_oauth.refresh_token
	 * @param refreshToken  the value for ph2_oauth.refresh_token
	 * @mbg.generated
	 */
	public void setRefreshToken(String refreshToken)
		{
		this.refreshToken = refreshToken == null ? null : refreshToken.trim();
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_oauth.access_token
	 * @return  the value of ph2_oauth.access_token
	 * @mbg.generated
	 */
	public String getAccessToken()
		{
		return accessToken;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_oauth.access_token
	 * @param accessToken  the value for ph2_oauth.access_token
	 * @mbg.generated
	 */
	public void setAccessToken(String accessToken)
		{
		this.accessToken = accessToken == null ? null : accessToken.trim();
		}
}