package com.logpose.ph2.api.dao.db.entity;

import java.util.Date;

public class Ph2ParamsetPsWeibullEntity {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_paramset_ps_weibull.paramset_id
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	private Long paramsetId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_paramset_ps_weibull.value_a
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	private Double valueA;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_paramset_ps_weibull.value_b
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	private Double valueB;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_paramset_ps_weibull.value_l
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	private Double valueL;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_paramset_ps_weibull.created_at
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	private Date createdAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_paramset_ps_weibull.updated_at
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	private Date updatedAt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_paramset_ps_weibull.paramset_id
	 * @return  the value of ph2_paramset_ps_weibull.paramset_id
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	public Long getParamsetId()
		{
		return paramsetId;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_paramset_ps_weibull.paramset_id
	 * @param paramsetId  the value for ph2_paramset_ps_weibull.paramset_id
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	public void setParamsetId(Long paramsetId)
		{
		this.paramsetId = paramsetId;
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_paramset_ps_weibull.value_a
	 * @return  the value of ph2_paramset_ps_weibull.value_a
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	public Double getValueA()
		{
		return valueA;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_paramset_ps_weibull.value_a
	 * @param valueA  the value for ph2_paramset_ps_weibull.value_a
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	public void setValueA(Double valueA)
		{
		this.valueA = valueA;
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_paramset_ps_weibull.value_b
	 * @return  the value of ph2_paramset_ps_weibull.value_b
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	public Double getValueB()
		{
		return valueB;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_paramset_ps_weibull.value_b
	 * @param valueB  the value for ph2_paramset_ps_weibull.value_b
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	public void setValueB(Double valueB)
		{
		this.valueB = valueB;
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_paramset_ps_weibull.value_l
	 * @return  the value of ph2_paramset_ps_weibull.value_l
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	public Double getValueL()
		{
		return valueL;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_paramset_ps_weibull.value_l
	 * @param valueL  the value for ph2_paramset_ps_weibull.value_l
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	public void setValueL(Double valueL)
		{
		this.valueL = valueL;
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_paramset_ps_weibull.created_at
	 * @return  the value of ph2_paramset_ps_weibull.created_at
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	public Date getCreatedAt()
		{
		return createdAt;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_paramset_ps_weibull.created_at
	 * @param createdAt  the value for ph2_paramset_ps_weibull.created_at
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	public void setCreatedAt(Date createdAt)
		{
		this.createdAt = createdAt;
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_paramset_ps_weibull.updated_at
	 * @return  the value of ph2_paramset_ps_weibull.updated_at
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	public Date getUpdatedAt()
		{
		return updatedAt;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_paramset_ps_weibull.updated_at
	 * @param updatedAt  the value for ph2_paramset_ps_weibull.updated_at
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	public void setUpdatedAt(Date updatedAt)
		{
		this.updatedAt = updatedAt;
		}
}