package com.logpose.ph2.api.dao.db.entity;

import java.util.Date;

public class Ph2RealGrowthFStageEntity {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_real_growth_f_stage.id
	 * @mbg.generated
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_real_growth_f_stage.device_id
	 * @mbg.generated
	 */
	private Long deviceId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_real_growth_f_stage.year
	 * @mbg.generated
	 */
	private Short year;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_real_growth_f_stage.stage_name
	 * @mbg.generated
	 */
	private String stageName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_real_growth_f_stage.stage_start
	 * @mbg.generated
	 */
	private Short stageStart;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_real_growth_f_stage.stage_end
	 * @mbg.generated
	 */
	private Short stageEnd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_real_growth_f_stage.interval_f
	 * @mbg.generated
	 */
	private Double intervalF;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_real_growth_f_stage.accumulated_f
	 * @mbg.generated
	 */
	private Double accumulatedF;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_real_growth_f_stage.created_at
	 * @mbg.generated
	 */
	private Date createdAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_real_growth_f_stage.updated_at
	 * @mbg.generated
	 */
	private Date updatedAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_real_growth_f_stage.actual_date
	 * @mbg.generated
	 */
	private Date actualDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_real_growth_f_stage.color
	 * @mbg.generated
	 */
	private String color;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_real_growth_f_stage.id
	 * @return  the value of ph2_real_growth_f_stage.id
	 * @mbg.generated
	 */
	public Long getId()
		{
		return id;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_real_growth_f_stage.id
	 * @param id  the value for ph2_real_growth_f_stage.id
	 * @mbg.generated
	 */
	public void setId(Long id)
		{
		this.id = id;
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_real_growth_f_stage.device_id
	 * @return  the value of ph2_real_growth_f_stage.device_id
	 * @mbg.generated
	 */
	public Long getDeviceId()
		{
		return deviceId;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_real_growth_f_stage.device_id
	 * @param deviceId  the value for ph2_real_growth_f_stage.device_id
	 * @mbg.generated
	 */
	public void setDeviceId(Long deviceId)
		{
		this.deviceId = deviceId;
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_real_growth_f_stage.year
	 * @return  the value of ph2_real_growth_f_stage.year
	 * @mbg.generated
	 */
	public Short getYear()
		{
		return year;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_real_growth_f_stage.year
	 * @param year  the value for ph2_real_growth_f_stage.year
	 * @mbg.generated
	 */
	public void setYear(Short year)
		{
		this.year = year;
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_real_growth_f_stage.stage_name
	 * @return  the value of ph2_real_growth_f_stage.stage_name
	 * @mbg.generated
	 */
	public String getStageName()
		{
		return stageName;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_real_growth_f_stage.stage_name
	 * @param stageName  the value for ph2_real_growth_f_stage.stage_name
	 * @mbg.generated
	 */
	public void setStageName(String stageName)
		{
		this.stageName = stageName == null ? null : stageName.trim();
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_real_growth_f_stage.stage_start
	 * @return  the value of ph2_real_growth_f_stage.stage_start
	 * @mbg.generated
	 */
	public Short getStageStart()
		{
		return stageStart;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_real_growth_f_stage.stage_start
	 * @param stageStart  the value for ph2_real_growth_f_stage.stage_start
	 * @mbg.generated
	 */
	public void setStageStart(Short stageStart)
		{
		this.stageStart = stageStart;
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_real_growth_f_stage.stage_end
	 * @return  the value of ph2_real_growth_f_stage.stage_end
	 * @mbg.generated
	 */
	public Short getStageEnd()
		{
		return stageEnd;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_real_growth_f_stage.stage_end
	 * @param stageEnd  the value for ph2_real_growth_f_stage.stage_end
	 * @mbg.generated
	 */
	public void setStageEnd(Short stageEnd)
		{
		this.stageEnd = stageEnd;
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_real_growth_f_stage.interval_f
	 * @return  the value of ph2_real_growth_f_stage.interval_f
	 * @mbg.generated
	 */
	public Double getIntervalF()
		{
		return intervalF;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_real_growth_f_stage.interval_f
	 * @param intervalF  the value for ph2_real_growth_f_stage.interval_f
	 * @mbg.generated
	 */
	public void setIntervalF(Double intervalF)
		{
		this.intervalF = intervalF;
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_real_growth_f_stage.accumulated_f
	 * @return  the value of ph2_real_growth_f_stage.accumulated_f
	 * @mbg.generated
	 */
	public Double getAccumulatedF()
		{
		return accumulatedF;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_real_growth_f_stage.accumulated_f
	 * @param accumulatedF  the value for ph2_real_growth_f_stage.accumulated_f
	 * @mbg.generated
	 */
	public void setAccumulatedF(Double accumulatedF)
		{
		this.accumulatedF = accumulatedF;
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_real_growth_f_stage.created_at
	 * @return  the value of ph2_real_growth_f_stage.created_at
	 * @mbg.generated
	 */
	public Date getCreatedAt()
		{
		return createdAt;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_real_growth_f_stage.created_at
	 * @param createdAt  the value for ph2_real_growth_f_stage.created_at
	 * @mbg.generated
	 */
	public void setCreatedAt(Date createdAt)
		{
		this.createdAt = createdAt;
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_real_growth_f_stage.updated_at
	 * @return  the value of ph2_real_growth_f_stage.updated_at
	 * @mbg.generated
	 */
	public Date getUpdatedAt()
		{
		return updatedAt;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_real_growth_f_stage.updated_at
	 * @param updatedAt  the value for ph2_real_growth_f_stage.updated_at
	 * @mbg.generated
	 */
	public void setUpdatedAt(Date updatedAt)
		{
		this.updatedAt = updatedAt;
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_real_growth_f_stage.actual_date
	 * @return  the value of ph2_real_growth_f_stage.actual_date
	 * @mbg.generated
	 */
	public Date getActualDate()
		{
		return actualDate;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_real_growth_f_stage.actual_date
	 * @param actualDate  the value for ph2_real_growth_f_stage.actual_date
	 * @mbg.generated
	 */
	public void setActualDate(Date actualDate)
		{
		this.actualDate = actualDate;
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_real_growth_f_stage.color
	 * @return  the value of ph2_real_growth_f_stage.color
	 * @mbg.generated
	 */
	public String getColor()
		{
		return color;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_real_growth_f_stage.color
	 * @param color  the value for ph2_real_growth_f_stage.color
	 * @mbg.generated
	 */
	public void setColor(String color)
		{
		this.color = color == null ? null : color.trim();
		}
}