package com.logpose.ph2.api.dao.db.entity;

import java.util.Date;

public class Ph2RealFruitsBearingEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ph2_real_fruits_bearing.device_id
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    private Long deviceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ph2_real_fruits_bearing.year
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    private Short year;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ph2_real_fruits_bearing.bearing
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    private Short bearing;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ph2_real_fruits_bearing.amount
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    private Double amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ph2_real_fruits_bearing.area
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    private Double area;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ph2_real_fruits_bearing.created_at
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ph2_real_fruits_bearing.updated_at
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ph2_real_fruits_bearing.device_id
     *
     * @return the value of ph2_real_fruits_bearing.device_id
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    public Long getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ph2_real_fruits_bearing.device_id
     *
     * @param deviceId the value for ph2_real_fruits_bearing.device_id
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    public void setDeviceId(Long deviceId) {
        this.deviceId = deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ph2_real_fruits_bearing.year
     *
     * @return the value of ph2_real_fruits_bearing.year
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    public Short getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ph2_real_fruits_bearing.year
     *
     * @param year the value for ph2_real_fruits_bearing.year
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    public void setYear(Short year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ph2_real_fruits_bearing.bearing
     *
     * @return the value of ph2_real_fruits_bearing.bearing
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    public Short getBearing() {
        return bearing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ph2_real_fruits_bearing.bearing
     *
     * @param bearing the value for ph2_real_fruits_bearing.bearing
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    public void setBearing(Short bearing) {
        this.bearing = bearing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ph2_real_fruits_bearing.amount
     *
     * @return the value of ph2_real_fruits_bearing.amount
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    public Double getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ph2_real_fruits_bearing.amount
     *
     * @param amount the value for ph2_real_fruits_bearing.amount
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    public void setAmount(Double amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ph2_real_fruits_bearing.area
     *
     * @return the value of ph2_real_fruits_bearing.area
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    public Double getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ph2_real_fruits_bearing.area
     *
     * @param area the value for ph2_real_fruits_bearing.area
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    public void setArea(Double area) {
        this.area = area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ph2_real_fruits_bearing.created_at
     *
     * @return the value of ph2_real_fruits_bearing.created_at
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ph2_real_fruits_bearing.created_at
     *
     * @param createdAt the value for ph2_real_fruits_bearing.created_at
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ph2_real_fruits_bearing.updated_at
     *
     * @return the value of ph2_real_fruits_bearing.updated_at
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ph2_real_fruits_bearing.updated_at
     *
     * @param updatedAt the value for ph2_real_fruits_bearing.updated_at
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}