package com.logpose.ph2.api.dao.db.entity;

import java.util.Date;

import org.apache.ibatis.annotations.Mapper;
@Mapper
public class Ph2RelFieldDeviceEntity {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_rel_field_device.id
	 * @mbg.generated  Tue Aug 01 04:16:34 JST 2023
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_rel_field_device.field_id
	 * @mbg.generated  Tue Aug 01 04:16:34 JST 2023
	 */
	private Long fieldId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_rel_field_device.device_id
	 * @mbg.generated  Tue Aug 01 04:16:34 JST 2023
	 */
	private Long deviceId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_rel_field_device.brand_id
	 * @mbg.generated  Tue Aug 01 04:16:34 JST 2023
	 */
	private Integer brandId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_rel_field_device.commenced_at
	 * @mbg.generated  Tue Aug 01 04:16:34 JST 2023
	 */
	private Date commencedAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_rel_field_device.closed_at
	 * @mbg.generated  Tue Aug 01 04:16:34 JST 2023
	 */
	private Date closedAt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_rel_field_device.id
	 * @return  the value of ph2_rel_field_device.id
	 * @mbg.generated  Tue Aug 01 04:16:34 JST 2023
	 */
	public Long getId()
		{
		return id;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_rel_field_device.id
	 * @param id  the value for ph2_rel_field_device.id
	 * @mbg.generated  Tue Aug 01 04:16:34 JST 2023
	 */
	public void setId(Long id)
		{
		this.id = id;
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_rel_field_device.field_id
	 * @return  the value of ph2_rel_field_device.field_id
	 * @mbg.generated  Tue Aug 01 04:16:34 JST 2023
	 */
	public Long getFieldId()
		{
		return fieldId;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_rel_field_device.field_id
	 * @param fieldId  the value for ph2_rel_field_device.field_id
	 * @mbg.generated  Tue Aug 01 04:16:34 JST 2023
	 */
	public void setFieldId(Long fieldId)
		{
		this.fieldId = fieldId;
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_rel_field_device.device_id
	 * @return  the value of ph2_rel_field_device.device_id
	 * @mbg.generated  Tue Aug 01 04:16:34 JST 2023
	 */
	public Long getDeviceId()
		{
		return deviceId;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_rel_field_device.device_id
	 * @param deviceId  the value for ph2_rel_field_device.device_id
	 * @mbg.generated  Tue Aug 01 04:16:34 JST 2023
	 */
	public void setDeviceId(Long deviceId)
		{
		this.deviceId = deviceId;
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_rel_field_device.brand_id
	 * @return  the value of ph2_rel_field_device.brand_id
	 * @mbg.generated  Tue Aug 01 04:16:34 JST 2023
	 */
	public Integer getBrandId()
		{
		return brandId;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_rel_field_device.brand_id
	 * @param brandId  the value for ph2_rel_field_device.brand_id
	 * @mbg.generated  Tue Aug 01 04:16:34 JST 2023
	 */
	public void setBrandId(Integer brandId)
		{
		this.brandId = brandId;
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_rel_field_device.commenced_at
	 * @return  the value of ph2_rel_field_device.commenced_at
	 * @mbg.generated  Tue Aug 01 04:16:34 JST 2023
	 */
	public Date getCommencedAt()
		{
		return commencedAt;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_rel_field_device.commenced_at
	 * @param commencedAt  the value for ph2_rel_field_device.commenced_at
	 * @mbg.generated  Tue Aug 01 04:16:34 JST 2023
	 */
	public void setCommencedAt(Date commencedAt)
		{
		this.commencedAt = commencedAt;
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_rel_field_device.closed_at
	 * @return  the value of ph2_rel_field_device.closed_at
	 * @mbg.generated  Tue Aug 01 04:16:34 JST 2023
	 */
	public Date getClosedAt()
		{
		return closedAt;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_rel_field_device.closed_at
	 * @param closedAt  the value for ph2_rel_field_device.closed_at
	 * @mbg.generated  Tue Aug 01 04:16:34 JST 2023
	 */
	public void setClosedAt(Date closedAt)
		{
		this.closedAt = closedAt;
		}
}