package com.logpose.ph2.api.dao.db.entity;

import java.util.Date;

public class Ph2RealPsAmountEntity {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_real_ps_amount.device_id
	 * @mbg.generated
	 */
	private Long deviceId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_real_ps_amount.date
	 * @mbg.generated
	 */
	private Date date;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_real_ps_amount.value_f
	 * @mbg.generated
	 */
	private Float valueF;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_real_ps_amount.value_g
	 * @mbg.generated
	 */
	private Float valueG;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_real_ps_amount.created_at
	 * @mbg.generated
	 */
	private Date createdAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_real_ps_amount.updated_at
	 * @mbg.generated
	 */
	private Date updatedAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_real_ps_amount.year
	 * @mbg.generated
	 */
	private Short year;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_real_ps_amount.device_id
	 * @return  the value of ph2_real_ps_amount.device_id
	 * @mbg.generated
	 */
	public Long getDeviceId()
		{
		return deviceId;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_real_ps_amount.device_id
	 * @param deviceId  the value for ph2_real_ps_amount.device_id
	 * @mbg.generated
	 */
	public void setDeviceId(Long deviceId)
		{
		this.deviceId = deviceId;
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_real_ps_amount.date
	 * @return  the value of ph2_real_ps_amount.date
	 * @mbg.generated
	 */
	public Date getDate()
		{
		return date;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_real_ps_amount.date
	 * @param date  the value for ph2_real_ps_amount.date
	 * @mbg.generated
	 */
	public void setDate(Date date)
		{
		this.date = date;
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_real_ps_amount.value_f
	 * @return  the value of ph2_real_ps_amount.value_f
	 * @mbg.generated
	 */
	public Float getValueF()
		{
		return valueF;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_real_ps_amount.value_f
	 * @param valueF  the value for ph2_real_ps_amount.value_f
	 * @mbg.generated
	 */
	public void setValueF(Float valueF)
		{
		this.valueF = valueF;
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_real_ps_amount.value_g
	 * @return  the value of ph2_real_ps_amount.value_g
	 * @mbg.generated
	 */
	public Float getValueG()
		{
		return valueG;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_real_ps_amount.value_g
	 * @param valueG  the value for ph2_real_ps_amount.value_g
	 * @mbg.generated
	 */
	public void setValueG(Float valueG)
		{
		this.valueG = valueG;
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_real_ps_amount.created_at
	 * @return  the value of ph2_real_ps_amount.created_at
	 * @mbg.generated
	 */
	public Date getCreatedAt()
		{
		return createdAt;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_real_ps_amount.created_at
	 * @param createdAt  the value for ph2_real_ps_amount.created_at
	 * @mbg.generated
	 */
	public void setCreatedAt(Date createdAt)
		{
		this.createdAt = createdAt;
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_real_ps_amount.updated_at
	 * @return  the value of ph2_real_ps_amount.updated_at
	 * @mbg.generated
	 */
	public Date getUpdatedAt()
		{
		return updatedAt;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_real_ps_amount.updated_at
	 * @param updatedAt  the value for ph2_real_ps_amount.updated_at
	 * @mbg.generated
	 */
	public void setUpdatedAt(Date updatedAt)
		{
		this.updatedAt = updatedAt;
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_real_ps_amount.year
	 * @return  the value of ph2_real_ps_amount.year
	 * @mbg.generated
	 */
	public Short getYear()
		{
		return year;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_real_ps_amount.year
	 * @param year  the value for ph2_real_ps_amount.year
	 * @mbg.generated
	 */
	public void setYear(Short year)
		{
		this.year = year;
		}
}