package com.logpose.ph2.api.dao.db.entity;

import java.util.Date;

public class Ph2SystemStatusEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ph2_system_status.table_name
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    private String tableName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ph2_system_status.last_time
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    private Date lastTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ph2_system_status.table_name
     *
     * @return the value of ph2_system_status.table_name
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ph2_system_status.table_name
     *
     * @param tableName the value for ph2_system_status.table_name
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    public void setTableName(String tableName) {
        this.tableName = tableName == null ? null : tableName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ph2_system_status.last_time
     *
     * @return the value of ph2_system_status.last_time
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    public Date getLastTime() {
        return lastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ph2_system_status.last_time
     *
     * @param lastTime the value for ph2_system_status.last_time
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    public void setLastTime(Date lastTime) {
        this.lastTime = lastTime;
    }
}