package com.logpose.ph2.api.dao.db.entity;

import java.util.Date;

public class Ph2SensorContentsEntity {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_sensor_contents.id
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_sensor_contents.name
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_sensor_contents.channel_size
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	private Integer channelSize;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_sensor_contents.code
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_sensor_contents.created_at
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	private Date createdAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_sensor_contents.updated_at
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	private Date updatedAt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_sensor_contents.id
	 * @return  the value of ph2_sensor_contents.id
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	public Long getId()
		{
		return id;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_sensor_contents.id
	 * @param id  the value for ph2_sensor_contents.id
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	public void setId(Long id)
		{
		this.id = id;
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_sensor_contents.name
	 * @return  the value of ph2_sensor_contents.name
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	public String getName()
		{
		return name;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_sensor_contents.name
	 * @param name  the value for ph2_sensor_contents.name
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	public void setName(String name)
		{
		this.name = name == null ? null : name.trim();
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_sensor_contents.channel_size
	 * @return  the value of ph2_sensor_contents.channel_size
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	public Integer getChannelSize()
		{
		return channelSize;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_sensor_contents.channel_size
	 * @param channelSize  the value for ph2_sensor_contents.channel_size
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	public void setChannelSize(Integer channelSize)
		{
		this.channelSize = channelSize;
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_sensor_contents.code
	 * @return  the value of ph2_sensor_contents.code
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	public String getCode()
		{
		return code;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_sensor_contents.code
	 * @param code  the value for ph2_sensor_contents.code
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	public void setCode(String code)
		{
		this.code = code == null ? null : code.trim();
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_sensor_contents.created_at
	 * @return  the value of ph2_sensor_contents.created_at
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	public Date getCreatedAt()
		{
		return createdAt;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_sensor_contents.created_at
	 * @param createdAt  the value for ph2_sensor_contents.created_at
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	public void setCreatedAt(Date createdAt)
		{
		this.createdAt = createdAt;
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_sensor_contents.updated_at
	 * @return  the value of ph2_sensor_contents.updated_at
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	public Date getUpdatedAt()
		{
		return updatedAt;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_sensor_contents.updated_at
	 * @param updatedAt  the value for ph2_sensor_contents.updated_at
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	public void setUpdatedAt(Date updatedAt)
		{
		this.updatedAt = updatedAt;
		}
}