package com.logpose.ph2.api.dao.db.entity;

import java.util.Date;

public class Ph2SensorsEntity {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_sensors.id
	 * @mbg.generated
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_sensors.device_id
	 * @mbg.generated
	 */
	private Long deviceId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_sensors.channel
	 * @mbg.generated
	 */
	private Integer channel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_sensors.sensor_size_id
	 * @mbg.generated
	 */
	private Long sensorSizeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_sensors.sensor_content_id
	 * @mbg.generated
	 */
	private Long sensorContentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_sensors.plant
	 * @mbg.generated
	 */
	private String plant;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_sensors.kst
	 * @mbg.generated
	 */
	private Double kst;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_sensors.sm
	 * @mbg.generated
	 */
	private Double sm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_sensors.lf
	 * @mbg.generated
	 */
	private Double lf;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_sensors.cb
	 * @mbg.generated
	 */
	private Double cb;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_sensors.sensor_model_id
	 * @mbg.generated
	 */
	private Long sensorModelId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_sensors.name
	 * @mbg.generated
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_sensors.created_at
	 * @mbg.generated
	 */
	private Date createdAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_sensors.updated_at
	 * @mbg.generated
	 */
	private Date updatedAt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_sensors.id
	 * @return  the value of ph2_sensors.id
	 * @mbg.generated
	 */
	public Long getId()
		{
		return id;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_sensors.id
	 * @param id  the value for ph2_sensors.id
	 * @mbg.generated
	 */
	public void setId(Long id)
		{
		this.id = id;
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_sensors.device_id
	 * @return  the value of ph2_sensors.device_id
	 * @mbg.generated
	 */
	public Long getDeviceId()
		{
		return deviceId;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_sensors.device_id
	 * @param deviceId  the value for ph2_sensors.device_id
	 * @mbg.generated
	 */
	public void setDeviceId(Long deviceId)
		{
		this.deviceId = deviceId;
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_sensors.channel
	 * @return  the value of ph2_sensors.channel
	 * @mbg.generated
	 */
	public Integer getChannel()
		{
		return channel;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_sensors.channel
	 * @param channel  the value for ph2_sensors.channel
	 * @mbg.generated
	 */
	public void setChannel(Integer channel)
		{
		this.channel = channel;
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_sensors.sensor_size_id
	 * @return  the value of ph2_sensors.sensor_size_id
	 * @mbg.generated
	 */
	public Long getSensorSizeId()
		{
		return sensorSizeId;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_sensors.sensor_size_id
	 * @param sensorSizeId  the value for ph2_sensors.sensor_size_id
	 * @mbg.generated
	 */
	public void setSensorSizeId(Long sensorSizeId)
		{
		this.sensorSizeId = sensorSizeId;
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_sensors.sensor_content_id
	 * @return  the value of ph2_sensors.sensor_content_id
	 * @mbg.generated
	 */
	public Long getSensorContentId()
		{
		return sensorContentId;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_sensors.sensor_content_id
	 * @param sensorContentId  the value for ph2_sensors.sensor_content_id
	 * @mbg.generated
	 */
	public void setSensorContentId(Long sensorContentId)
		{
		this.sensorContentId = sensorContentId;
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_sensors.plant
	 * @return  the value of ph2_sensors.plant
	 * @mbg.generated
	 */
	public String getPlant()
		{
		return plant;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_sensors.plant
	 * @param plant  the value for ph2_sensors.plant
	 * @mbg.generated
	 */
	public void setPlant(String plant)
		{
		this.plant = plant == null ? null : plant.trim();
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_sensors.kst
	 * @return  the value of ph2_sensors.kst
	 * @mbg.generated
	 */
	public Double getKst()
		{
		return kst;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_sensors.kst
	 * @param kst  the value for ph2_sensors.kst
	 * @mbg.generated
	 */
	public void setKst(Double kst)
		{
		this.kst = kst;
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_sensors.sm
	 * @return  the value of ph2_sensors.sm
	 * @mbg.generated
	 */
	public Double getSm()
		{
		return sm;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_sensors.sm
	 * @param sm  the value for ph2_sensors.sm
	 * @mbg.generated
	 */
	public void setSm(Double sm)
		{
		this.sm = sm;
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_sensors.lf
	 * @return  the value of ph2_sensors.lf
	 * @mbg.generated
	 */
	public Double getLf()
		{
		return lf;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_sensors.lf
	 * @param lf  the value for ph2_sensors.lf
	 * @mbg.generated
	 */
	public void setLf(Double lf)
		{
		this.lf = lf;
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_sensors.cb
	 * @return  the value of ph2_sensors.cb
	 * @mbg.generated
	 */
	public Double getCb()
		{
		return cb;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_sensors.cb
	 * @param cb  the value for ph2_sensors.cb
	 * @mbg.generated
	 */
	public void setCb(Double cb)
		{
		this.cb = cb;
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_sensors.sensor_model_id
	 * @return  the value of ph2_sensors.sensor_model_id
	 * @mbg.generated
	 */
	public Long getSensorModelId()
		{
		return sensorModelId;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_sensors.sensor_model_id
	 * @param sensorModelId  the value for ph2_sensors.sensor_model_id
	 * @mbg.generated
	 */
	public void setSensorModelId(Long sensorModelId)
		{
		this.sensorModelId = sensorModelId;
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_sensors.name
	 * @return  the value of ph2_sensors.name
	 * @mbg.generated
	 */
	public String getName()
		{
		return name;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_sensors.name
	 * @param name  the value for ph2_sensors.name
	 * @mbg.generated
	 */
	public void setName(String name)
		{
		this.name = name == null ? null : name.trim();
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_sensors.created_at
	 * @return  the value of ph2_sensors.created_at
	 * @mbg.generated
	 */
	public Date getCreatedAt()
		{
		return createdAt;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_sensors.created_at
	 * @param createdAt  the value for ph2_sensors.created_at
	 * @mbg.generated
	 */
	public void setCreatedAt(Date createdAt)
		{
		this.createdAt = createdAt;
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_sensors.updated_at
	 * @return  the value of ph2_sensors.updated_at
	 * @mbg.generated
	 */
	public Date getUpdatedAt()
		{
		return updatedAt;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_sensors.updated_at
	 * @param updatedAt  the value for ph2_sensors.updated_at
	 * @mbg.generated
	 */
	public void setUpdatedAt(Date updatedAt)
		{
		this.updatedAt = updatedAt;
		}
}