package com.logpose.ph2.api.dao.db.entity;

import java.util.Date;

public class Ph2TemperatureEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ph2_temperature.device_id
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    private Long deviceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ph2_temperature.min
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    private Short min;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ph2_temperature.max
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    private Short max;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ph2_temperature.target_date
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    private Date targetDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ph2_temperature.device_id
     *
     * @return the value of ph2_temperature.device_id
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    public Long getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ph2_temperature.device_id
     *
     * @param deviceId the value for ph2_temperature.device_id
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    public void setDeviceId(Long deviceId) {
        this.deviceId = deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ph2_temperature.min
     *
     * @return the value of ph2_temperature.min
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    public Short getMin() {
        return min;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ph2_temperature.min
     *
     * @param min the value for ph2_temperature.min
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    public void setMin(Short min) {
        this.min = min;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ph2_temperature.max
     *
     * @return the value of ph2_temperature.max
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    public Short getMax() {
        return max;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ph2_temperature.max
     *
     * @param max the value for ph2_temperature.max
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    public void setMax(Short max) {
        this.max = max;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ph2_temperature.target_date
     *
     * @return the value of ph2_temperature.target_date
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    public Date getTargetDate() {
        return targetDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ph2_temperature.target_date
     *
     * @param targetDate the value for ph2_temperature.target_date
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    public void setTargetDate(Date targetDate) {
        this.targetDate = targetDate;
    }
}