package com.logpose.ph2.api.dao.db.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class Ph2UsersEntityExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ph2_users
	 * @mbg.generated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ph2_users
	 * @mbg.generated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ph2_users
	 * @mbg.generated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_users
	 * @mbg.generated
	 */
	public Ph2UsersEntityExample()
		{
		oredCriteria = new ArrayList<>();
		}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_users
	 * @mbg.generated
	 */
	public void setOrderByClause(String orderByClause)
		{
		this.orderByClause = orderByClause;
		}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_users
	 * @mbg.generated
	 */
	public String getOrderByClause()
		{
		return orderByClause;
		}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_users
	 * @mbg.generated
	 */
	public void setDistinct(boolean distinct)
		{
		this.distinct = distinct;
		}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_users
	 * @mbg.generated
	 */
	public boolean isDistinct()
		{
		return distinct;
		}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_users
	 * @mbg.generated
	 */
	public List<Criteria> getOredCriteria()
		{
		return oredCriteria;
		}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_users
	 * @mbg.generated
	 */
	public void or(Criteria criteria)
		{
		oredCriteria.add(criteria);
		}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_users
	 * @mbg.generated
	 */
	public Criteria or()
		{
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
		}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_users
	 * @mbg.generated
	 */
	public Criteria createCriteria()
		{
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0)
			{
			oredCriteria.add(criteria);
			}
		return criteria;
		}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_users
	 * @mbg.generated
	 */
	protected Criteria createCriteriaInternal()
		{
		Criteria criteria = new Criteria();
		return criteria;
		}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_users
	 * @mbg.generated
	 */
	public void clear()
		{
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
		}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table ph2_users
	 * @mbg.generated
	 */
	protected abstract static class GeneratedCriteria
		{
		protected List<Criterion> criteria;

		protected GeneratedCriteria()
			{
			super();
			criteria = new ArrayList<>();
			}

		public boolean isValid()
			{
			return criteria.size() > 0;
			}

		public List<Criterion> getAllCriteria()
			{
			return criteria;
			}

		public List<Criterion> getCriteria()
			{
			return criteria;
			}

		protected void addCriterion(String condition)
			{
			if (condition == null)
				{
				throw new RuntimeException("Value for condition cannot be null");
				}
			criteria.add(new Criterion(condition));
			}

		protected void addCriterion(String condition, Object value, String property)
			{
			if (value == null)
				{
				throw new RuntimeException("Value for " + property + " cannot be null");
				}
			criteria.add(new Criterion(condition, value));
			}

		protected void addCriterion(String condition, Object value1, Object value2, String property)
			{
			if (value1 == null || value2 == null)
				{
				throw new RuntimeException("Between values for " + property + " cannot be null");
				}
			criteria.add(new Criterion(condition, value1, value2));
			}

		public Criteria andIdIsNull()
			{
			addCriterion("id is null");
			return (Criteria) this;
			}

		public Criteria andIdIsNotNull()
			{
			addCriterion("id is not null");
			return (Criteria) this;
			}

		public Criteria andIdEqualTo(Long value)
			{
			addCriterion("id =", value, "id");
			return (Criteria) this;
			}

		public Criteria andIdNotEqualTo(Long value)
			{
			addCriterion("id <>", value, "id");
			return (Criteria) this;
			}

		public Criteria andIdGreaterThan(Long value)
			{
			addCriterion("id >", value, "id");
			return (Criteria) this;
			}

		public Criteria andIdGreaterThanOrEqualTo(Long value)
			{
			addCriterion("id >=", value, "id");
			return (Criteria) this;
			}

		public Criteria andIdLessThan(Long value)
			{
			addCriterion("id <", value, "id");
			return (Criteria) this;
			}

		public Criteria andIdLessThanOrEqualTo(Long value)
			{
			addCriterion("id <=", value, "id");
			return (Criteria) this;
			}

		public Criteria andIdIn(List<Long> values)
			{
			addCriterion("id in", values, "id");
			return (Criteria) this;
			}

		public Criteria andIdNotIn(List<Long> values)
			{
			addCriterion("id not in", values, "id");
			return (Criteria) this;
			}

		public Criteria andIdBetween(Long value1, Long value2)
			{
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
			}

		public Criteria andIdNotBetween(Long value1, Long value2)
			{
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
			}

		public Criteria andUsernameIsNull()
			{
			addCriterion("username is null");
			return (Criteria) this;
			}

		public Criteria andUsernameIsNotNull()
			{
			addCriterion("username is not null");
			return (Criteria) this;
			}

		public Criteria andUsernameEqualTo(String value)
			{
			addCriterion("username =", value, "username");
			return (Criteria) this;
			}

		public Criteria andUsernameNotEqualTo(String value)
			{
			addCriterion("username <>", value, "username");
			return (Criteria) this;
			}

		public Criteria andUsernameGreaterThan(String value)
			{
			addCriterion("username >", value, "username");
			return (Criteria) this;
			}

		public Criteria andUsernameGreaterThanOrEqualTo(String value)
			{
			addCriterion("username >=", value, "username");
			return (Criteria) this;
			}

		public Criteria andUsernameLessThan(String value)
			{
			addCriterion("username <", value, "username");
			return (Criteria) this;
			}

		public Criteria andUsernameLessThanOrEqualTo(String value)
			{
			addCriterion("username <=", value, "username");
			return (Criteria) this;
			}

		public Criteria andUsernameLike(String value)
			{
			addCriterion("username like", value, "username");
			return (Criteria) this;
			}

		public Criteria andUsernameNotLike(String value)
			{
			addCriterion("username not like", value, "username");
			return (Criteria) this;
			}

		public Criteria andUsernameIn(List<String> values)
			{
			addCriterion("username in", values, "username");
			return (Criteria) this;
			}

		public Criteria andUsernameNotIn(List<String> values)
			{
			addCriterion("username not in", values, "username");
			return (Criteria) this;
			}

		public Criteria andUsernameBetween(String value1, String value2)
			{
			addCriterion("username between", value1, value2, "username");
			return (Criteria) this;
			}

		public Criteria andUsernameNotBetween(String value1, String value2)
			{
			addCriterion("username not between", value1, value2, "username");
			return (Criteria) this;
			}

		public Criteria andEmailIsNull()
			{
			addCriterion("email is null");
			return (Criteria) this;
			}

		public Criteria andEmailIsNotNull()
			{
			addCriterion("email is not null");
			return (Criteria) this;
			}

		public Criteria andEmailEqualTo(String value)
			{
			addCriterion("email =", value, "email");
			return (Criteria) this;
			}

		public Criteria andEmailNotEqualTo(String value)
			{
			addCriterion("email <>", value, "email");
			return (Criteria) this;
			}

		public Criteria andEmailGreaterThan(String value)
			{
			addCriterion("email >", value, "email");
			return (Criteria) this;
			}

		public Criteria andEmailGreaterThanOrEqualTo(String value)
			{
			addCriterion("email >=", value, "email");
			return (Criteria) this;
			}

		public Criteria andEmailLessThan(String value)
			{
			addCriterion("email <", value, "email");
			return (Criteria) this;
			}

		public Criteria andEmailLessThanOrEqualTo(String value)
			{
			addCriterion("email <=", value, "email");
			return (Criteria) this;
			}

		public Criteria andEmailLike(String value)
			{
			addCriterion("email like", value, "email");
			return (Criteria) this;
			}

		public Criteria andEmailNotLike(String value)
			{
			addCriterion("email not like", value, "email");
			return (Criteria) this;
			}

		public Criteria andEmailIn(List<String> values)
			{
			addCriterion("email in", values, "email");
			return (Criteria) this;
			}

		public Criteria andEmailNotIn(List<String> values)
			{
			addCriterion("email not in", values, "email");
			return (Criteria) this;
			}

		public Criteria andEmailBetween(String value1, String value2)
			{
			addCriterion("email between", value1, value2, "email");
			return (Criteria) this;
			}

		public Criteria andEmailNotBetween(String value1, String value2)
			{
			addCriterion("email not between", value1, value2, "email");
			return (Criteria) this;
			}

		public Criteria andPasswordDigestIsNull()
			{
			addCriterion("password_digest is null");
			return (Criteria) this;
			}

		public Criteria andPasswordDigestIsNotNull()
			{
			addCriterion("password_digest is not null");
			return (Criteria) this;
			}

		public Criteria andPasswordDigestEqualTo(String value)
			{
			addCriterion("password_digest =", value, "passwordDigest");
			return (Criteria) this;
			}

		public Criteria andPasswordDigestNotEqualTo(String value)
			{
			addCriterion("password_digest <>", value, "passwordDigest");
			return (Criteria) this;
			}

		public Criteria andPasswordDigestGreaterThan(String value)
			{
			addCriterion("password_digest >", value, "passwordDigest");
			return (Criteria) this;
			}

		public Criteria andPasswordDigestGreaterThanOrEqualTo(String value)
			{
			addCriterion("password_digest >=", value, "passwordDigest");
			return (Criteria) this;
			}

		public Criteria andPasswordDigestLessThan(String value)
			{
			addCriterion("password_digest <", value, "passwordDigest");
			return (Criteria) this;
			}

		public Criteria andPasswordDigestLessThanOrEqualTo(String value)
			{
			addCriterion("password_digest <=", value, "passwordDigest");
			return (Criteria) this;
			}

		public Criteria andPasswordDigestLike(String value)
			{
			addCriterion("password_digest like", value, "passwordDigest");
			return (Criteria) this;
			}

		public Criteria andPasswordDigestNotLike(String value)
			{
			addCriterion("password_digest not like", value, "passwordDigest");
			return (Criteria) this;
			}

		public Criteria andPasswordDigestIn(List<String> values)
			{
			addCriterion("password_digest in", values, "passwordDigest");
			return (Criteria) this;
			}

		public Criteria andPasswordDigestNotIn(List<String> values)
			{
			addCriterion("password_digest not in", values, "passwordDigest");
			return (Criteria) this;
			}

		public Criteria andPasswordDigestBetween(String value1, String value2)
			{
			addCriterion("password_digest between", value1, value2, "passwordDigest");
			return (Criteria) this;
			}

		public Criteria andPasswordDigestNotBetween(String value1, String value2)
			{
			addCriterion("password_digest not between", value1, value2, "passwordDigest");
			return (Criteria) this;
			}

		public Criteria andCreatedAtIsNull()
			{
			addCriterion("created_at is null");
			return (Criteria) this;
			}

		public Criteria andCreatedAtIsNotNull()
			{
			addCriterion("created_at is not null");
			return (Criteria) this;
			}

		public Criteria andCreatedAtEqualTo(Date value)
			{
			addCriterion("created_at =", value, "createdAt");
			return (Criteria) this;
			}

		public Criteria andCreatedAtNotEqualTo(Date value)
			{
			addCriterion("created_at <>", value, "createdAt");
			return (Criteria) this;
			}

		public Criteria andCreatedAtGreaterThan(Date value)
			{
			addCriterion("created_at >", value, "createdAt");
			return (Criteria) this;
			}

		public Criteria andCreatedAtGreaterThanOrEqualTo(Date value)
			{
			addCriterion("created_at >=", value, "createdAt");
			return (Criteria) this;
			}

		public Criteria andCreatedAtLessThan(Date value)
			{
			addCriterion("created_at <", value, "createdAt");
			return (Criteria) this;
			}

		public Criteria andCreatedAtLessThanOrEqualTo(Date value)
			{
			addCriterion("created_at <=", value, "createdAt");
			return (Criteria) this;
			}

		public Criteria andCreatedAtIn(List<Date> values)
			{
			addCriterion("created_at in", values, "createdAt");
			return (Criteria) this;
			}

		public Criteria andCreatedAtNotIn(List<Date> values)
			{
			addCriterion("created_at not in", values, "createdAt");
			return (Criteria) this;
			}

		public Criteria andCreatedAtBetween(Date value1, Date value2)
			{
			addCriterion("created_at between", value1, value2, "createdAt");
			return (Criteria) this;
			}

		public Criteria andCreatedAtNotBetween(Date value1, Date value2)
			{
			addCriterion("created_at not between", value1, value2, "createdAt");
			return (Criteria) this;
			}

		public Criteria andUpdatedAtIsNull()
			{
			addCriterion("updated_at is null");
			return (Criteria) this;
			}

		public Criteria andUpdatedAtIsNotNull()
			{
			addCriterion("updated_at is not null");
			return (Criteria) this;
			}

		public Criteria andUpdatedAtEqualTo(Date value)
			{
			addCriterion("updated_at =", value, "updatedAt");
			return (Criteria) this;
			}

		public Criteria andUpdatedAtNotEqualTo(Date value)
			{
			addCriterion("updated_at <>", value, "updatedAt");
			return (Criteria) this;
			}

		public Criteria andUpdatedAtGreaterThan(Date value)
			{
			addCriterion("updated_at >", value, "updatedAt");
			return (Criteria) this;
			}

		public Criteria andUpdatedAtGreaterThanOrEqualTo(Date value)
			{
			addCriterion("updated_at >=", value, "updatedAt");
			return (Criteria) this;
			}

		public Criteria andUpdatedAtLessThan(Date value)
			{
			addCriterion("updated_at <", value, "updatedAt");
			return (Criteria) this;
			}

		public Criteria andUpdatedAtLessThanOrEqualTo(Date value)
			{
			addCriterion("updated_at <=", value, "updatedAt");
			return (Criteria) this;
			}

		public Criteria andUpdatedAtIn(List<Date> values)
			{
			addCriterion("updated_at in", values, "updatedAt");
			return (Criteria) this;
			}

		public Criteria andUpdatedAtNotIn(List<Date> values)
			{
			addCriterion("updated_at not in", values, "updatedAt");
			return (Criteria) this;
			}

		public Criteria andUpdatedAtBetween(Date value1, Date value2)
			{
			addCriterion("updated_at between", value1, value2, "updatedAt");
			return (Criteria) this;
			}

		public Criteria andUpdatedAtNotBetween(Date value1, Date value2)
			{
			addCriterion("updated_at not between", value1, value2, "updatedAt");
			return (Criteria) this;
			}

		public Criteria andAuthIdIsNull()
			{
			addCriterion("auth_id is null");
			return (Criteria) this;
			}

		public Criteria andAuthIdIsNotNull()
			{
			addCriterion("auth_id is not null");
			return (Criteria) this;
			}

		public Criteria andAuthIdEqualTo(String value)
			{
			addCriterion("auth_id =", value, "authId");
			return (Criteria) this;
			}

		public Criteria andAuthIdNotEqualTo(String value)
			{
			addCriterion("auth_id <>", value, "authId");
			return (Criteria) this;
			}

		public Criteria andAuthIdGreaterThan(String value)
			{
			addCriterion("auth_id >", value, "authId");
			return (Criteria) this;
			}

		public Criteria andAuthIdGreaterThanOrEqualTo(String value)
			{
			addCriterion("auth_id >=", value, "authId");
			return (Criteria) this;
			}

		public Criteria andAuthIdLessThan(String value)
			{
			addCriterion("auth_id <", value, "authId");
			return (Criteria) this;
			}

		public Criteria andAuthIdLessThanOrEqualTo(String value)
			{
			addCriterion("auth_id <=", value, "authId");
			return (Criteria) this;
			}

		public Criteria andAuthIdLike(String value)
			{
			addCriterion("auth_id like", value, "authId");
			return (Criteria) this;
			}

		public Criteria andAuthIdNotLike(String value)
			{
			addCriterion("auth_id not like", value, "authId");
			return (Criteria) this;
			}

		public Criteria andAuthIdIn(List<String> values)
			{
			addCriterion("auth_id in", values, "authId");
			return (Criteria) this;
			}

		public Criteria andAuthIdNotIn(List<String> values)
			{
			addCriterion("auth_id not in", values, "authId");
			return (Criteria) this;
			}

		public Criteria andAuthIdBetween(String value1, String value2)
			{
			addCriterion("auth_id between", value1, value2, "authId");
			return (Criteria) this;
			}

		public Criteria andAuthIdNotBetween(String value1, String value2)
			{
			addCriterion("auth_id not between", value1, value2, "authId");
			return (Criteria) this;
			}
		}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table ph2_users
	 * @mbg.generated
	 */
	public static class Criterion
		{
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition()
			{
			return condition;
			}

		public Object getValue()
			{
			return value;
			}

		public Object getSecondValue()
			{
			return secondValue;
			}

		public boolean isNoValue()
			{
			return noValue;
			}

		public boolean isSingleValue()
			{
			return singleValue;
			}

		public boolean isBetweenValue()
			{
			return betweenValue;
			}

		public boolean isListValue()
			{
			return listValue;
			}

		public String getTypeHandler()
			{
			return typeHandler;
			}

		protected Criterion(String condition)
			{
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
			}

		protected Criterion(String condition, Object value, String typeHandler)
			{
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>)
				{
				this.listValue = true;
				}
			else
				{
				this.singleValue = true;
				}
			}

		protected Criterion(String condition, Object value)
			{
			this(condition, value, null);
			}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler)
			{
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
			}

		protected Criterion(String condition, Object value, Object secondValue)
			{
			this(condition, value, secondValue, null);
			}
		}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ph2_users
     *
     * @mbg.generated do_not_delete_during_merge Mon Jul 03 16:33:57 JST 2023
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }
}