package com.logpose.ph2.api.dao.db.entity;

public class Ph2VoltageDataEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ph2_voltage_data.relation_id
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    private Long relationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ph2_voltage_data.content_id
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    private Long contentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ph2_voltage_data.sensor_id
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    private Long sensorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ph2_voltage_data.channel_no
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    private Short channelNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ph2_voltage_data.voltage
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    private Double voltage;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ph2_voltage_data.relation_id
     *
     * @return the value of ph2_voltage_data.relation_id
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    public Long getRelationId() {
        return relationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ph2_voltage_data.relation_id
     *
     * @param relationId the value for ph2_voltage_data.relation_id
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    public void setRelationId(Long relationId) {
        this.relationId = relationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ph2_voltage_data.content_id
     *
     * @return the value of ph2_voltage_data.content_id
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    public Long getContentId() {
        return contentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ph2_voltage_data.content_id
     *
     * @param contentId the value for ph2_voltage_data.content_id
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    public void setContentId(Long contentId) {
        this.contentId = contentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ph2_voltage_data.sensor_id
     *
     * @return the value of ph2_voltage_data.sensor_id
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    public Long getSensorId() {
        return sensorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ph2_voltage_data.sensor_id
     *
     * @param sensorId the value for ph2_voltage_data.sensor_id
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    public void setSensorId(Long sensorId) {
        this.sensorId = sensorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ph2_voltage_data.channel_no
     *
     * @return the value of ph2_voltage_data.channel_no
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    public Short getChannelNo() {
        return channelNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ph2_voltage_data.channel_no
     *
     * @param channelNo the value for ph2_voltage_data.channel_no
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    public void setChannelNo(Short channelNo) {
        this.channelNo = channelNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ph2_voltage_data.voltage
     *
     * @return the value of ph2_voltage_data.voltage
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    public Double getVoltage() {
        return voltage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ph2_voltage_data.voltage
     *
     * @param voltage the value for ph2_voltage_data.voltage
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    public void setVoltage(Double voltage) {
        this.voltage = voltage;
    }
}