package com.logpose.ph2.api.dao.db.entity;

import java.util.Date;

public class Ph2WeatherDailyMasterEntity {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_weather_daily_master.device_id
	 * @mbg.generated
	 */
	private Long deviceId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_weather_daily_master.tm
	 * @mbg.generated
	 */
	private Float tm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_weather_daily_master.average
	 * @mbg.generated
	 */
	private Float average;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_weather_daily_master.cdd
	 * @mbg.generated
	 */
	private Double cdd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_weather_daily_master.par
	 * @mbg.generated
	 */
	private Double par;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_weather_daily_master.sun_time
	 * @mbg.generated
	 */
	private Long sunTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_weather_daily_master.raw_cdd
	 * @mbg.generated
	 */
	private Double rawCdd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_weather_daily_master.casted_at
	 * @mbg.generated
	 */
	private Date castedAt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_weather_daily_master.device_id
	 * @return  the value of ph2_weather_daily_master.device_id
	 * @mbg.generated
	 */
	public Long getDeviceId()
		{
		return deviceId;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_weather_daily_master.device_id
	 * @param deviceId  the value for ph2_weather_daily_master.device_id
	 * @mbg.generated
	 */
	public void setDeviceId(Long deviceId)
		{
		this.deviceId = deviceId;
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_weather_daily_master.tm
	 * @return  the value of ph2_weather_daily_master.tm
	 * @mbg.generated
	 */
	public Float getTm()
		{
		return tm;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_weather_daily_master.tm
	 * @param tm  the value for ph2_weather_daily_master.tm
	 * @mbg.generated
	 */
	public void setTm(Float tm)
		{
		this.tm = tm;
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_weather_daily_master.average
	 * @return  the value of ph2_weather_daily_master.average
	 * @mbg.generated
	 */
	public Float getAverage()
		{
		return average;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_weather_daily_master.average
	 * @param average  the value for ph2_weather_daily_master.average
	 * @mbg.generated
	 */
	public void setAverage(Float average)
		{
		this.average = average;
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_weather_daily_master.cdd
	 * @return  the value of ph2_weather_daily_master.cdd
	 * @mbg.generated
	 */
	public Double getCdd()
		{
		return cdd;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_weather_daily_master.cdd
	 * @param cdd  the value for ph2_weather_daily_master.cdd
	 * @mbg.generated
	 */
	public void setCdd(Double cdd)
		{
		this.cdd = cdd;
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_weather_daily_master.par
	 * @return  the value of ph2_weather_daily_master.par
	 * @mbg.generated
	 */
	public Double getPar()
		{
		return par;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_weather_daily_master.par
	 * @param par  the value for ph2_weather_daily_master.par
	 * @mbg.generated
	 */
	public void setPar(Double par)
		{
		this.par = par;
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_weather_daily_master.sun_time
	 * @return  the value of ph2_weather_daily_master.sun_time
	 * @mbg.generated
	 */
	public Long getSunTime()
		{
		return sunTime;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_weather_daily_master.sun_time
	 * @param sunTime  the value for ph2_weather_daily_master.sun_time
	 * @mbg.generated
	 */
	public void setSunTime(Long sunTime)
		{
		this.sunTime = sunTime;
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_weather_daily_master.raw_cdd
	 * @return  the value of ph2_weather_daily_master.raw_cdd
	 * @mbg.generated
	 */
	public Double getRawCdd()
		{
		return rawCdd;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_weather_daily_master.raw_cdd
	 * @param rawCdd  the value for ph2_weather_daily_master.raw_cdd
	 * @mbg.generated
	 */
	public void setRawCdd(Double rawCdd)
		{
		this.rawCdd = rawCdd;
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_weather_daily_master.casted_at
	 * @return  the value of ph2_weather_daily_master.casted_at
	 * @mbg.generated
	 */
	public Date getCastedAt()
		{
		return castedAt;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_weather_daily_master.casted_at
	 * @param castedAt  the value for ph2_weather_daily_master.casted_at
	 * @mbg.generated
	 */
	public void setCastedAt(Date castedAt)
		{
		this.castedAt = castedAt;
		}
}