package com.logpose.ph2.api.dao.db.entity;

public class Ph2WibleMasterEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ph2_wible_master.lapse_days
     *
     * @mbg.generated
     */
    private Short lapseDays;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ph2_wible_master.value
     *
     * @mbg.generated
     */
    private Double value;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ph2_wible_master.lapse_days
     *
     * @return the value of ph2_wible_master.lapse_days
     *
     * @mbg.generated
     */
    public Short getLapseDays() {
        return lapseDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ph2_wible_master.lapse_days
     *
     * @param lapseDays the value for ph2_wible_master.lapse_days
     *
     * @mbg.generated
     */
    public void setLapseDays(Short lapseDays) {
        this.lapseDays = lapseDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ph2_wible_master.value
     *
     * @return the value of ph2_wible_master.value
     *
     * @mbg.generated
     */
    public Double getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ph2_wible_master.value
     *
     * @param value the value for ph2_wible_master.value
     *
     * @mbg.generated
     */
    public void setValue(Double value) {
        this.value = value;
    }
}