package com.logpose.ph2.batch.dao.db.mappers;

import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.logpose.ph2.batch.dao.db.entity.MessagesEnyity;
import com.logpose.ph2.batch.dao.db.entity.MessagesEnyityExample;
@Mapper
public interface MessagesMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table messages
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	long countByExample(MessagesEnyityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table messages
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	int deleteByExample(MessagesEnyityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table messages
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table messages
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	int insert(MessagesEnyity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table messages
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	int insertSelective(MessagesEnyity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table messages
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	List<MessagesEnyity> selectByExample(MessagesEnyityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table messages
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	MessagesEnyity selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table messages
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	int updateByExampleSelective(@Param("row") MessagesEnyity row,
			@Param("example") MessagesEnyityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table messages
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	int updateByExample(@Param("row") MessagesEnyity row,
			@Param("example") MessagesEnyityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table messages
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	int updateByPrimaryKeySelective(MessagesEnyity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table messages
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	int updateByPrimaryKey(MessagesEnyity row);

	List<MessagesEnyity> selectByCastedAt(@Param("castedAt") Date castedAt);

}