package com.logpose.ph2.batch.dao.db.mappers;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.logpose.ph2.batch.dao.db.entity.Ph2BaseDataEntity;
import com.logpose.ph2.batch.dao.db.entity.Ph2BaseDataEntityExample;
@Mapper
public interface Ph2BaseDataMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_base_data
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	long countByExample(Ph2BaseDataEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_base_data
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	int deleteByExample(Ph2BaseDataEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_base_data
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	int insert(Ph2BaseDataEntity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_base_data
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	int insertSelective(Ph2BaseDataEntity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_base_data
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	List<Ph2BaseDataEntity> selectByExample(Ph2BaseDataEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_base_data
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	int updateByExampleSelective(@Param("row") Ph2BaseDataEntity row,
			@Param("example") Ph2BaseDataEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_base_data
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	int updateByExample(@Param("row") Ph2BaseDataEntity row,
			@Param("example") Ph2BaseDataEntityExample example);
}