package com.logpose.ph2.batch.dao.db.mappers;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.logpose.ph2.batch.dao.db.entity.Ph2DashBoardEntity;
import com.logpose.ph2.batch.dao.db.entity.Ph2DashBoardEntityExample;
@Mapper
public interface Ph2DashBoardMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_dashboard
	 * @mbg.generated  Sat Sep 16 17:32:32 JST 2023
	 */
	long countByExample(Ph2DashBoardEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_dashboard
	 * @mbg.generated  Sat Sep 16 17:32:32 JST 2023
	 */
	int deleteByExample(Ph2DashBoardEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_dashboard
	 * @mbg.generated  Sat Sep 16 17:32:32 JST 2023
	 */
	int insert(Ph2DashBoardEntity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_dashboard
	 * @mbg.generated  Sat Sep 16 17:32:32 JST 2023
	 */
	int insertSelective(Ph2DashBoardEntity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_dashboard
	 * @mbg.generated  Sat Sep 16 17:32:32 JST 2023
	 */
	List<Ph2DashBoardEntity> selectByExample(Ph2DashBoardEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_dashboard
	 * @mbg.generated  Sat Sep 16 17:32:32 JST 2023
	 */
	int updateByExampleSelective(@Param("row") Ph2DashBoardEntity row,
			@Param("example") Ph2DashBoardEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_dashboard
	 * @mbg.generated  Sat Sep 16 17:32:32 JST 2023
	 */
	int updateByExample(@Param("row") Ph2DashBoardEntity row,
			@Param("example") Ph2DashBoardEntityExample example);
}