package com.logpose.ph2.batch.dao.db.mappers;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.logpose.ph2.batch.dao.db.entity.Ph2ParamsetGrowthEntity;
import com.logpose.ph2.batch.dao.db.entity.Ph2ParamsetGrowthEntityExample;
@Mapper
public interface Ph2ParamsetGrowthMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_paramset_growth
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	long countByExample(Ph2ParamsetGrowthEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_paramset_growth
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	int deleteByExample(Ph2ParamsetGrowthEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_paramset_growth
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	int deleteByPrimaryKey(Long paramsetId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_paramset_growth
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	int insert(Ph2ParamsetGrowthEntity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_paramset_growth
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	int insertSelective(Ph2ParamsetGrowthEntity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_paramset_growth
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	List<Ph2ParamsetGrowthEntity> selectByExample(
			Ph2ParamsetGrowthEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_paramset_growth
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	Ph2ParamsetGrowthEntity selectByPrimaryKey(Long paramsetId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_paramset_growth
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	int updateByExampleSelective(@Param("row") Ph2ParamsetGrowthEntity row,
			@Param("example") Ph2ParamsetGrowthEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_paramset_growth
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	int updateByExample(@Param("row") Ph2ParamsetGrowthEntity row,
			@Param("example") Ph2ParamsetGrowthEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_paramset_growth
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	int updateByPrimaryKeySelective(Ph2ParamsetGrowthEntity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_paramset_growth
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	int updateByPrimaryKey(Ph2ParamsetGrowthEntity row);
}