package com.logpose.ph2.batch.dao.db.mappers;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.logpose.ph2.batch.dao.db.entity.Ph2ParamsetPsFieldEntity;
import com.logpose.ph2.batch.dao.db.entity.Ph2ParamsetPsFieldEntityExample;
@Mapper
public interface Ph2ParamsetPsFieldMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_paramset_ps_field
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	long countByExample(Ph2ParamsetPsFieldEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_paramset_ps_field
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	int deleteByExample(Ph2ParamsetPsFieldEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_paramset_ps_field
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	int deleteByPrimaryKey(Long paramsetId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_paramset_ps_field
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	int insert(Ph2ParamsetPsFieldEntity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_paramset_ps_field
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	int insertSelective(Ph2ParamsetPsFieldEntity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_paramset_ps_field
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	List<Ph2ParamsetPsFieldEntity> selectByExample(
			Ph2ParamsetPsFieldEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_paramset_ps_field
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	Ph2ParamsetPsFieldEntity selectByPrimaryKey(Long paramsetId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_paramset_ps_field
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	int updateByExampleSelective(@Param("row") Ph2ParamsetPsFieldEntity row,
			@Param("example") Ph2ParamsetPsFieldEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_paramset_ps_field
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	int updateByExample(@Param("row") Ph2ParamsetPsFieldEntity row,
			@Param("example") Ph2ParamsetPsFieldEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_paramset_ps_field
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	int updateByPrimaryKeySelective(Ph2ParamsetPsFieldEntity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_paramset_ps_field
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	int updateByPrimaryKey(Ph2ParamsetPsFieldEntity row);
}