package com.logpose.ph2.batch.dao.db.mappers;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.logpose.ph2.batch.dao.db.entity.Ph2RealFruitsDataEntity;
import com.logpose.ph2.batch.dao.db.entity.Ph2RealFruitsDataEntityExample;
@Mapper
public interface Ph2RealFruitsDataMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_real_fruits_data
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	long countByExample(Ph2RealFruitsDataEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_real_fruits_data
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	int deleteByExample(Ph2RealFruitsDataEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_real_fruits_data
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	int insert(Ph2RealFruitsDataEntity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_real_fruits_data
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	int insertSelective(Ph2RealFruitsDataEntity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_real_fruits_data
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	List<Ph2RealFruitsDataEntity> selectByExample(
			Ph2RealFruitsDataEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_real_fruits_data
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	int updateByExampleSelective(@Param("row") Ph2RealFruitsDataEntity row,
			@Param("example") Ph2RealFruitsDataEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_real_fruits_data
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	int updateByExample(@Param("row") Ph2RealFruitsDataEntity row,
			@Param("example") Ph2RealFruitsDataEntityExample example);
}