package com.logpose.ph2.batch.dao.db.mappers;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.logpose.ph2.batch.dao.db.entity.Ph2TemperatureEntity;
import com.logpose.ph2.batch.dao.db.entity.Ph2TemperatureEntityExample;
@Mapper
public interface Ph2TemperatureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph2_temperature
     *
     * @mbg.generated Thu Jul 06 19:21:57 JST 2023
     */
    long countByExample(Ph2TemperatureEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph2_temperature
     *
     * @mbg.generated Thu Jul 06 19:21:57 JST 2023
     */
    int deleteByExample(Ph2TemperatureEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph2_temperature
     *
     * @mbg.generated Thu Jul 06 19:21:57 JST 2023
     */
    int insert(Ph2TemperatureEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph2_temperature
     *
     * @mbg.generated Thu Jul 06 19:21:57 JST 2023
     */
    int insertSelective(Ph2TemperatureEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph2_temperature
     *
     * @mbg.generated Thu Jul 06 19:21:57 JST 2023
     */
    List<Ph2TemperatureEntity> selectByExample(Ph2TemperatureEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph2_temperature
     *
     * @mbg.generated Thu Jul 06 19:21:57 JST 2023
     */
    int updateByExampleSelective(@Param("row") Ph2TemperatureEntity row, @Param("example") Ph2TemperatureEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph2_temperature
     *
     * @mbg.generated Thu Jul 06 19:21:57 JST 2023
     */
    int updateByExample(@Param("row") Ph2TemperatureEntity row, @Param("example") Ph2TemperatureEntityExample example);
}