package com.logpose.ph2.api.dao.db.mappers;

import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.cursor.Cursor;

import com.logpose.ph2.api.dao.db.entity.MessagesEntity;
import com.logpose.ph2.api.dao.db.entity.MessagesEntityExample;

@Mapper
public interface MessagesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messages
     *
     * @mbg.generated
     */
    long countByExample(MessagesEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messages
     *
     * @mbg.generated
     */
    int deleteByExample(MessagesEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messages
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messages
     *
     * @mbg.generated
     */
    int insert(MessagesEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messages
     *
     * @mbg.generated
     */
    int insertSelective(MessagesEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messages
     *
     * @mbg.generated
     */
    List<MessagesEntity> selectByExample(MessagesEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messages
     *
     * @mbg.generated
     */
    MessagesEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messages
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") MessagesEntity row, @Param("example") MessagesEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messages
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") MessagesEntity row, @Param("example") MessagesEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messages
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MessagesEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messages
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MessagesEntity row);
    
	Cursor<MessagesEntity> selectByCastedAt(
			@Param("deviceId") Long deviceId, 
			@Param("tz") String tz, 
			@Param("castedAt") Date castedAt);
	
	Date selectLastCastedTime(@Param("deviceId") Long deviceId);
}