package com.logpose.ph2.api.dao.db.mappers;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.logpose.ph2.api.dao.db.entity.Ph2BatchLogEntity;
import com.logpose.ph2.api.dao.db.entity.Ph2BatchLogEntityExample;
import com.logpose.ph2.api.dao.db.entity.joined.Ph2BatchLogEntityExtendDevices;

@Mapper
public interface Ph2BatchLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph2_batch_log
     *
     * @mbg.generated
     */
    long countByExample(Ph2BatchLogEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph2_batch_log
     *
     * @mbg.generated
     */
    int deleteByExample(Ph2BatchLogEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph2_batch_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long deviceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph2_batch_log
     *
     * @mbg.generated
     */
    int insert(Ph2BatchLogEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph2_batch_log
     *
     * @mbg.generated
     */
    int insertSelective(Ph2BatchLogEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph2_batch_log
     *
     * @mbg.generated
     */
    List<Ph2BatchLogEntity> selectByExample(Ph2BatchLogEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph2_batch_log
     *
     * @mbg.generated
     */
    Ph2BatchLogEntity selectByPrimaryKey(Long deviceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph2_batch_log
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") Ph2BatchLogEntity row, @Param("example") Ph2BatchLogEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph2_batch_log
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") Ph2BatchLogEntity row, @Param("example") Ph2BatchLogEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph2_batch_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Ph2BatchLogEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph2_batch_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Ph2BatchLogEntity row);
    
    List<Ph2BatchLogEntityExtendDevices> selectWithStatus();
}