package com.logpose.ph2.api.dao.db.mappers;

import com.logpose.ph2.api.dao.db.entity.Ph2DefaultModelKeyValuesEntity;
import com.logpose.ph2.api.dao.db.entity.Ph2DefaultModelKeyValuesEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Ph2DefaultModelKeyValuesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph2_default_model_key_values
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    long countByExample(Ph2DefaultModelKeyValuesEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph2_default_model_key_values
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    int deleteByExample(Ph2DefaultModelKeyValuesEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph2_default_model_key_values
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    int insert(Ph2DefaultModelKeyValuesEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph2_default_model_key_values
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    int insertSelective(Ph2DefaultModelKeyValuesEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph2_default_model_key_values
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    List<Ph2DefaultModelKeyValuesEntity> selectByExample(Ph2DefaultModelKeyValuesEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph2_default_model_key_values
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    int updateByExampleSelective(@Param("row") Ph2DefaultModelKeyValuesEntity row, @Param("example") Ph2DefaultModelKeyValuesEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph2_default_model_key_values
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    int updateByExample(@Param("row") Ph2DefaultModelKeyValuesEntity row, @Param("example") Ph2DefaultModelKeyValuesEntityExample example);
}