package com.logpose.ph2.api.dao.db.mappers;

import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.logpose.ph2.api.dao.db.entity.Ph2DeviceDayEntity;
import com.logpose.ph2.api.dao.db.entity.Ph2DeviceDayEntityExample;
import com.logpose.ph2.api.dto.MaxMinDateDTO;
@Mapper
public interface Ph2DeviceDayMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_device_day
	 * @mbg.generated
	 */
	long countByExample(Ph2DeviceDayEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_device_day
	 * @mbg.generated
	 */
	int deleteByExample(Ph2DeviceDayEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_device_day
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_device_day
	 * @mbg.generated
	 */
	int insert(Ph2DeviceDayEntity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_device_day
	 * @mbg.generated
	 */
	int insertSelective(Ph2DeviceDayEntity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_device_day
	 * @mbg.generated
	 */
	List<Ph2DeviceDayEntity> selectByExample(Ph2DeviceDayEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_device_day
	 * @mbg.generated
	 */
	Ph2DeviceDayEntity selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_device_day
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("row") Ph2DeviceDayEntity row,
			@Param("example") Ph2DeviceDayEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_device_day
	 * @mbg.generated
	 */
	int updateByExample(@Param("row") Ph2DeviceDayEntity row, @Param("example") Ph2DeviceDayEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_device_day
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Ph2DeviceDayEntity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_device_day
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Ph2DeviceDayEntity row);

	Short getYear(@Param("deviceId") Long deviceId,  @Param("date") Date date);
	
	int multiRowInsert(@Param("targets") List<Ph2DeviceDayEntity> targets);
	
	Long selectMaxId();
	
	Date selectMaxTrueDate(@Param("deviceId") Long deviceId);
	
	MaxMinDateDTO selectMaxMinDate(@Param("deviceId") Long deviceId, @Param("year") Short year);
}