package com.logpose.ph2.api.dao.db.mappers;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.logpose.ph2.api.dao.db.entity.Ph2DashBoardSensorsEntity;
import com.logpose.ph2.api.dao.db.entity.Ph2DashBoardSensorsEntityExample;

@Mapper
public interface Ph2DashBoardSensorsMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_dashboard_sensors
	 * @mbg.generated
	 */
	long countByExample(Ph2DashBoardSensorsEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_dashboard_sensors
	 * @mbg.generated
	 */
	int deleteByExample(Ph2DashBoardSensorsEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_dashboard_sensors
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Long sensorId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_dashboard_sensors
	 * @mbg.generated
	 */
	int insert(Ph2DashBoardSensorsEntity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_dashboard_sensors
	 * @mbg.generated
	 */
	int insertSelective(Ph2DashBoardSensorsEntity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_dashboard_sensors
	 * @mbg.generated
	 */
	List<Ph2DashBoardSensorsEntity> selectByExample(Ph2DashBoardSensorsEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_dashboard_sensors
	 * @mbg.generated
	 */
	Ph2DashBoardSensorsEntity selectByPrimaryKey(Long sensorId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_dashboard_sensors
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("row") Ph2DashBoardSensorsEntity row,
			@Param("example") Ph2DashBoardSensorsEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_dashboard_sensors
	 * @mbg.generated
	 */
	int updateByExample(@Param("row") Ph2DashBoardSensorsEntity row,
			@Param("example") Ph2DashBoardSensorsEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_dashboard_sensors
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Ph2DashBoardSensorsEntity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_dashboard_sensors
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Ph2DashBoardSensorsEntity row);

	List<Ph2DashBoardSensorsEntity> selectSensorSettingsByDeviceId(@Param("deviceId") Long deviceId);

	int deleteByDeviceId(@Param("deviceId") Long deviceId);
}