package com.logpose.ph2.api.dao.db.mappers;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.logpose.ph2.api.dao.db.entity.Ph2DevicesEnyity;
import com.logpose.ph2.api.dao.db.entity.Ph2DevicesEnyityExample;
import com.logpose.ph2.api.dto.ModelRefDataDTO;
@Mapper
public interface Ph2DevicesMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_devices
	 * @mbg.generated
	 */
	long countByExample(Ph2DevicesEnyityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_devices
	 * @mbg.generated
	 */
	int deleteByExample(Ph2DevicesEnyityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_devices
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_devices
	 * @mbg.generated
	 */
	Long insert(Ph2DevicesEnyity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_devices
	 * @mbg.generated
	 */
	int insertSelective(Ph2DevicesEnyity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_devices
	 * @mbg.generated
	 */
	List<Ph2DevicesEnyity> selectByExample(Ph2DevicesEnyityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_devices
	 * @mbg.generated
	 */
	Ph2DevicesEnyity selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_devices
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("row") Ph2DevicesEnyity row, @Param("example") Ph2DevicesEnyityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_devices
	 * @mbg.generated
	 */
	int updateByExample(@Param("row") Ph2DevicesEnyity row, @Param("example") Ph2DevicesEnyityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_devices
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Ph2DevicesEnyity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_devices
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Ph2DevicesEnyity row);

	List<ModelRefDataDTO> selectDeviceList();

	List<Ph2DevicesEnyity> selectAll();
}