package com.logpose.ph2.api.dao.db.mappers;

import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.logpose.ph2.api.dao.db.entity.Ph2DeviceLogEntity;
import com.logpose.ph2.api.dao.db.entity.Ph2DeviceLogEntityExample;

@Mapper
public interface Ph2DeviceLogMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_device_log
	 * @mbg.generated
	 */
	long countByExample(Ph2DeviceLogEntityExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_device_log
	 * @mbg.generated
	 */
	int deleteByExample(Ph2DeviceLogEntityExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_device_log
	 * @mbg.generated
	 */
	int insert(Ph2DeviceLogEntity row);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_device_log
	 * @mbg.generated
	 */
	int insertSelective(Ph2DeviceLogEntity row);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_device_log
	 * @mbg.generated
	 */
	List<Ph2DeviceLogEntity> selectByExample(Ph2DeviceLogEntityExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_device_log
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("row") Ph2DeviceLogEntity row,
			@Param("example") Ph2DeviceLogEntityExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_device_log
	 * @mbg.generated
	 */
	int updateByExample(@Param("row") Ph2DeviceLogEntity row, @Param("example") Ph2DeviceLogEntityExample example);
	void deleteLoadLog(@Param("deviceId") Long deviceId);
	void deleteUpdateLog(@Param("deviceId") Long deviceId);
	List<Ph2DeviceLogEntity> selectOfBatchTerm(@Param("deviceId") Long deviceId, @Param("startTime") Date startTime, @Param("endTime") Date endTime);
	void deleteOfBatchTerm(@Param("deviceId") Long deviceId, @Param("startTime") Date startTime, @Param("endTime") Date endTime);

}