package com.logpose.ph2.api.dao.db.mappers;

import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.logpose.ph2.api.dao.db.entity.Ph2DevicesEntity;
import com.logpose.ph2.api.dao.db.entity.Ph2DevicesEntityExample;
import com.logpose.ph2.api.dto.ModelRefDataDTO;
import com.logpose.ph2.api.dto.element.ObjectStatus;
@Mapper
public interface Ph2DevicesMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_devices
	 * @mbg.generated
	 */
	long countByExample(Ph2DevicesEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_devices
	 * @mbg.generated
	 */
	int deleteByExample(Ph2DevicesEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_devices
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_devices
	 * @mbg.generated
	 */
	Long insert(Ph2DevicesEntity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_devices
	 * @mbg.generated
	 */
	int insertSelective(Ph2DevicesEntity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_devices
	 * @mbg.generated
	 */
	List<Ph2DevicesEntity> selectByExample(Ph2DevicesEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_devices
	 * @mbg.generated
	 */
	Ph2DevicesEntity selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_devices
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("row") Ph2DevicesEntity row, @Param("example") Ph2DevicesEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_devices
	 * @mbg.generated
	 */
	int updateByExample(@Param("row") Ph2DevicesEntity row, @Param("example") Ph2DevicesEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_devices
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Ph2DevicesEntity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_devices
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Ph2DevicesEntity row);

	List<ModelRefDataDTO> selectDeviceList();

	List<Ph2DevicesEntity> selectAll(@Param("status") Integer status);
	
	int updateAllStatus(@Param("status") int status, @Param("idList") List<Long> idList);
	int unsetAllStatus(@Param("status") int status, @Param("idList") List<Long> idList);
	List<ObjectStatus> selectDeviceStatus(@Param("idList") List<Long> idList);
	List<ObjectStatus> selectAllStatus(@Param("date") Date date);
	void setAllStatus(@Param("status") int status);
	
}