package com.logpose.ph2.api.dao.db.mappers;

import com.logpose.ph2.api.dao.db.entity.Ph2DailyBaseDataEntity;
import com.logpose.ph2.api.dao.db.entity.Ph2DailyBaseDataEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Ph2DailyBaseDataMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_daily_base_data
	 * @mbg.generated  Mon Jul 24 09:35:27 JST 2023
	 */
	long countByExample(Ph2DailyBaseDataEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_daily_base_data
	 * @mbg.generated  Mon Jul 24 09:35:27 JST 2023
	 */
	int deleteByExample(Ph2DailyBaseDataEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_daily_base_data
	 * @mbg.generated  Mon Jul 24 09:35:27 JST 2023
	 */
	int insert(Ph2DailyBaseDataEntity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_daily_base_data
	 * @mbg.generated  Mon Jul 24 09:35:27 JST 2023
	 */
	int insertSelective(Ph2DailyBaseDataEntity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_daily_base_data
	 * @mbg.generated  Mon Jul 24 09:35:27 JST 2023
	 */
	List<Ph2DailyBaseDataEntity> selectByExample(
			Ph2DailyBaseDataEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_daily_base_data
	 * @mbg.generated  Mon Jul 24 09:35:27 JST 2023
	 */
	int updateByExampleSelective(@Param("row") Ph2DailyBaseDataEntity row,
			@Param("example") Ph2DailyBaseDataEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_daily_base_data
	 * @mbg.generated  Mon Jul 24 09:35:27 JST 2023
	 */
	int updateByExample(@Param("row") Ph2DailyBaseDataEntity row,
			@Param("example") Ph2DailyBaseDataEntityExample example);
}