package com.logpose.ph2.api.dao.db.mappers;

import com.logpose.ph2.api.dao.db.entity.Ph2ElStageMasterEntity;
import com.logpose.ph2.api.dao.db.entity.Ph2ElStageMasterEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Ph2ElStageMasterMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_el_stage_master
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	long countByExample(Ph2ElStageMasterEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_el_stage_master
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	int deleteByExample(Ph2ElStageMasterEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_el_stage_master
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_el_stage_master
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	int insert(Ph2ElStageMasterEntity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_el_stage_master
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	int insertSelective(Ph2ElStageMasterEntity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_el_stage_master
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	List<Ph2ElStageMasterEntity> selectByExample(Ph2ElStageMasterEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_el_stage_master
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	Ph2ElStageMasterEntity selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_el_stage_master
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	int updateByExampleSelective(@Param("row") Ph2ElStageMasterEntity row,
			@Param("example") Ph2ElStageMasterEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_el_stage_master
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	int updateByExample(@Param("row") Ph2ElStageMasterEntity row,
			@Param("example") Ph2ElStageMasterEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_el_stage_master
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	int updateByPrimaryKeySelective(Ph2ElStageMasterEntity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_el_stage_master
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	int updateByPrimaryKey(Ph2ElStageMasterEntity row);
}