package com.logpose.ph2.api.dao.db.mappers;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.logpose.ph2.api.dao.db.entity.Ph2FDataEntity;
import com.logpose.ph2.api.dao.db.entity.Ph2FDataEntityExample;
@Mapper
public interface Ph2FDataMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_fdata
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	long countByExample(Ph2FDataEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_fdata
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	int deleteByExample(Ph2FDataEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_fdata
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	int insert(Ph2FDataEntity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_fdata
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	int insertSelective(Ph2FDataEntity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_fdata
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	List<Ph2FDataEntity> selectByExample(Ph2FDataEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_fdata
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	int updateByExampleSelective(@Param("row") Ph2FDataEntity row, @Param("example") Ph2FDataEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_fdata
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	int updateByExample(@Param("row") Ph2FDataEntity row, @Param("example") Ph2FDataEntityExample example);
}