package com.logpose.ph2.api.dao.db.mappers;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.logpose.ph2.api.dao.db.entity.Ph2FieldsEntity;
import com.logpose.ph2.api.dao.db.entity.Ph2FieldsEntityExample;
@Mapper
public interface Ph2FieldsMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_fields
	 * @mbg.generated  Wed Aug 02 13:44:57 JST 2023
	 */
	long countByExample(Ph2FieldsEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_fields
	 * @mbg.generated  Wed Aug 02 13:44:57 JST 2023
	 */
	int deleteByExample(Ph2FieldsEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_fields
	 * @mbg.generated  Wed Aug 02 13:44:57 JST 2023
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_fields
	 * @mbg.generated  Wed Aug 02 13:44:57 JST 2023
	 */
	long insert(Ph2FieldsEntity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_fields
	 * @mbg.generated  Wed Aug 02 13:44:57 JST 2023
	 */
	int insertSelective(Ph2FieldsEntity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_fields
	 * @mbg.generated  Wed Aug 02 13:44:57 JST 2023
	 */
	List<Ph2FieldsEntity> selectByExample(Ph2FieldsEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_fields
	 * @mbg.generated  Wed Aug 02 13:44:57 JST 2023
	 */
	Ph2FieldsEntity selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_fields
	 * @mbg.generated  Wed Aug 02 13:44:57 JST 2023
	 */
	int updateByExampleSelective(@Param("row") Ph2FieldsEntity row,
			@Param("example") Ph2FieldsEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_fields
	 * @mbg.generated  Wed Aug 02 13:44:57 JST 2023
	 */
	int updateByExample(@Param("row") Ph2FieldsEntity row,
			@Param("example") Ph2FieldsEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_fields
	 * @mbg.generated  Wed Aug 02 13:44:57 JST 2023
	 */
	int updateByPrimaryKeySelective(Ph2FieldsEntity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_fields
	 * @mbg.generated  Wed Aug 02 13:44:57 JST 2023
	 */
	int updateByPrimaryKey(Ph2FieldsEntity row);
}