package com.logpose.ph2.api.dao.db.mappers;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.logpose.ph2.api.dao.db.entity.Ph2HeadLinesEntity;
import com.logpose.ph2.api.dao.db.entity.Ph2HeadLinesEntityExample;
@Mapper
public interface Ph2HeadLinesMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_headlines
	 * @mbg.generated
	 */
	long countByExample(Ph2HeadLinesEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_headlines
	 * @mbg.generated
	 */
	int deleteByExample(Ph2HeadLinesEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_headlines
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Long rawDataId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_headlines
	 * @mbg.generated
	 */
	int insert(Ph2HeadLinesEntity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_headlines
	 * @mbg.generated
	 */
	int insertSelective(Ph2HeadLinesEntity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_headlines
	 * @mbg.generated
	 */
	List<Ph2HeadLinesEntity> selectByExample(Ph2HeadLinesEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_headlines
	 * @mbg.generated
	 */
	Ph2HeadLinesEntity selectByPrimaryKey(Long rawDataId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_headlines
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("row") Ph2HeadLinesEntity row,
			@Param("example") Ph2HeadLinesEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_headlines
	 * @mbg.generated
	 */
	int updateByExample(@Param("row") Ph2HeadLinesEntity row, @Param("example") Ph2HeadLinesEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_headlines
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Ph2HeadLinesEntity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_headlines
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Ph2HeadLinesEntity row);
}