package com.logpose.ph2.api.dao.db.mappers;

import com.logpose.ph2.api.dao.db.entity.Ph2InsolationDataEntity;
import com.logpose.ph2.api.dao.db.entity.Ph2InsolationDataEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Ph2InsolationDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph2_insolation_data
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    long countByExample(Ph2InsolationDataEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph2_insolation_data
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    int deleteByExample(Ph2InsolationDataEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph2_insolation_data
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    int insert(Ph2InsolationDataEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph2_insolation_data
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    int insertSelective(Ph2InsolationDataEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph2_insolation_data
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    List<Ph2InsolationDataEntity> selectByExample(Ph2InsolationDataEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph2_insolation_data
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    int updateByExampleSelective(@Param("row") Ph2InsolationDataEntity row, @Param("example") Ph2InsolationDataEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph2_insolation_data
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    int updateByExample(@Param("row") Ph2InsolationDataEntity row, @Param("example") Ph2InsolationDataEntityExample example);
}