package com.logpose.ph2.api.dao.db.mappers;

import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.cursor.Cursor;

import com.logpose.ph2.api.dao.db.entity.Ph2MessagesEntity;
import com.logpose.ph2.api.dao.db.entity.Ph2MessagesEntityExample;
@Mapper
public interface Ph2MessagesMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_messages
	 * @mbg.generated
	 */
	long countByExample(Ph2MessagesEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_messages
	 * @mbg.generated
	 */
	int deleteByExample(Ph2MessagesEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_messages
	 * @mbg.generated
	 */
	int insert(Ph2MessagesEntity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_messages
	 * @mbg.generated
	 */
	int insertSelective(Ph2MessagesEntity row);

	int multiRowInsert(@Param("targets") List<Ph2MessagesEntity> targets);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_messages
	 * @mbg.generated
	 */
	List<Ph2MessagesEntity> selectByExample(Ph2MessagesEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_messages
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("row") Ph2MessagesEntity row,
			@Param("example") Ph2MessagesEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_messages
	 * @mbg.generated
	 */
	int updateByExample(@Param("row") Ph2MessagesEntity row, @Param("example") Ph2MessagesEntityExample example);
	
	Date selectLastCastedTime(@Param("sigfoxId") String sigfoxId);
	
	Cursor<Ph2MessagesEntity> selectByCastedAt(
			@Param("sigfoxId") String sigfoxId, 
			@Param("tz") String tz, 
			@Param("opStart") Date opStart,
			@Param("opEnd") Date opEnd);

}