package com.logpose.ph2.api.dao.db.mappers;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.logpose.ph2.api.dao.db.entity.Ph2ModelMasterEntity;
import com.logpose.ph2.api.dao.db.entity.Ph2ModelMasterEntityExample;
@Mapper
public interface Ph2ModelMasterMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_model_master
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	long countByExample(Ph2ModelMasterEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_model_master
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	int deleteByExample(Ph2ModelMasterEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_model_master
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_model_master
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	int insert(Ph2ModelMasterEntity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_model_master
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	int insertSelective(Ph2ModelMasterEntity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_model_master
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	List<Ph2ModelMasterEntity> selectByExample(Ph2ModelMasterEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_model_master
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	Ph2ModelMasterEntity selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_model_master
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	int updateByExampleSelective(@Param("row") Ph2ModelMasterEntity row,
			@Param("example") Ph2ModelMasterEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_model_master
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	int updateByExample(@Param("row") Ph2ModelMasterEntity row, @Param("example") Ph2ModelMasterEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_model_master
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	int updateByPrimaryKeySelective(Ph2ModelMasterEntity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_model_master
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	int updateByPrimaryKey(Ph2ModelMasterEntity row);
}