package com.logpose.ph2.api.dao.db.mappers;

import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.logpose.ph2.api.dao.db.entity.Ph2ModelDataEntity;
import com.logpose.ph2.api.dao.db.entity.Ph2ModelDataEntityExample;
import com.logpose.ph2.api.dao.db.entity.joined.ModelDataEntity;
import com.logpose.ph2.api.dto.ValueDateDTO;
@Mapper
public interface Ph2ModelDataMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_model_data
	 * @mbg.generated  Sat Sep 16 17:32:32 JST 2023
	 */
	long countByExample(Ph2ModelDataEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_model_data
	 * @mbg.generated  Sat Sep 16 17:32:32 JST 2023
	 */
	int deleteByExample(Ph2ModelDataEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_model_data
	 * @mbg.generated  Sat Sep 16 17:32:32 JST 2023
	 */
	int deleteByPrimaryKey(Long dayId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_model_data
	 * @mbg.generated  Sat Sep 16 17:32:32 JST 2023
	 */
	int insert(Ph2ModelDataEntity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_model_data
	 * @mbg.generated  Sat Sep 16 17:32:32 JST 2023
	 */
	int insertSelective(Ph2ModelDataEntity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_model_data
	 * @mbg.generated  Sat Sep 16 17:32:32 JST 2023
	 */
	List<Ph2ModelDataEntity> selectByExample(Ph2ModelDataEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_model_data
	 * @mbg.generated  Sat Sep 16 17:32:32 JST 2023
	 */
	Ph2ModelDataEntity selectByPrimaryKey(Long dayId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_model_data
	 * @mbg.generated  Sat Sep 16 17:32:32 JST 2023
	 */
	int updateByExampleSelective(@Param("row") Ph2ModelDataEntity row,
			@Param("example") Ph2ModelDataEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_model_data
	 * @mbg.generated  Sat Sep 16 17:32:32 JST 2023
	 */
	int updateByExample(@Param("row") Ph2ModelDataEntity row,
			@Param("example") Ph2ModelDataEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_model_data
	 * @mbg.generated  Sat Sep 16 17:32:32 JST 2023
	 */
	int updateByPrimaryKeySelective(Ph2ModelDataEntity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_model_data
	 * @mbg.generated  Sat Sep 16 17:32:32 JST 2023
	 */
	int updateByPrimaryKey(Ph2ModelDataEntity row);

	List<ModelDataEntity> selectModelDataByType(@Param("deviceId") Long deviceId, @Param("year") Short year);

	ValueDateDTO selectRealFValueByDate(@Param("deviceId") Long deviceId, @Param("date") Date date, @Param("isReal") boolean isReal);
	
	ValueDateDTO selectFValueByDate(@Param("deviceId") Long deviceId, @Param("date") Date date);
	
	int multiRowInsert(@Param("targets") List<Ph2ModelDataEntity> targets);
}