package com.logpose.ph2.api.dao.db.mappers;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.logpose.ph2.api.dao.db.entity.Ph2OauthEntity;
import com.logpose.ph2.api.dao.db.entity.Ph2OauthEntityExample;

@Mapper
public interface Ph2OauthMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_oauth
	 * @mbg.generated
	 */
	long countByExample(Ph2OauthEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_oauth
	 * @mbg.generated
	 */
	int deleteByExample(Ph2OauthEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_oauth
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_oauth
	 * @mbg.generated
	 */
	int insert(Ph2OauthEntity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_oauth
	 * @mbg.generated
	 */
	int insertSelective(Ph2OauthEntity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_oauth
	 * @mbg.generated
	 */
	List<Ph2OauthEntity> selectByExample(Ph2OauthEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_oauth
	 * @mbg.generated
	 */
	Ph2OauthEntity selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_oauth
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("row") Ph2OauthEntity row, @Param("example") Ph2OauthEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_oauth
	 * @mbg.generated
	 */
	int updateByExample(@Param("row") Ph2OauthEntity row, @Param("example") Ph2OauthEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_oauth
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Ph2OauthEntity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_oauth
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Ph2OauthEntity row);

	List<Ph2OauthEntity> selectByAppId(@Param("appId") Long appId);
}