package com.logpose.ph2.api.dao.db.mappers;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.logpose.ph2.api.dao.db.entity.Ph2ParamsetLeafAreaEntity;
import com.logpose.ph2.api.dao.db.entity.Ph2ParamsetLeafAreaEntityExample;
@Mapper
public interface Ph2ParamsetLeafAreaMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_paramset_leaf_area
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	long countByExample(Ph2ParamsetLeafAreaEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_paramset_leaf_area
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	int deleteByExample(Ph2ParamsetLeafAreaEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_paramset_leaf_area
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	int deleteByPrimaryKey(Long paramsetId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_paramset_leaf_area
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	int insert(Ph2ParamsetLeafAreaEntity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_paramset_leaf_area
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	int insertSelective(Ph2ParamsetLeafAreaEntity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_paramset_leaf_area
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	List<Ph2ParamsetLeafAreaEntity> selectByExample(Ph2ParamsetLeafAreaEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_paramset_leaf_area
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	Ph2ParamsetLeafAreaEntity selectByPrimaryKey(Long paramsetId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_paramset_leaf_area
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	int updateByExampleSelective(@Param("row") Ph2ParamsetLeafAreaEntity row,
			@Param("example") Ph2ParamsetLeafAreaEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_paramset_leaf_area
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	int updateByExample(@Param("row") Ph2ParamsetLeafAreaEntity row,
			@Param("example") Ph2ParamsetLeafAreaEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_paramset_leaf_area
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	int updateByPrimaryKeySelective(Ph2ParamsetLeafAreaEntity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_paramset_leaf_area
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	int updateByPrimaryKey(Ph2ParamsetLeafAreaEntity row);
}