package com.logpose.ph2.api.dao.db.mappers;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.logpose.ph2.api.dao.db.entity.Ph2ParamsetLeafCountEntity;
import com.logpose.ph2.api.dao.db.entity.Ph2ParamsetLeafCountEntityExample;
@Mapper
public interface Ph2ParamsetLeafCountMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_paramset_leaf_count
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	long countByExample(Ph2ParamsetLeafCountEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_paramset_leaf_count
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	int deleteByExample(Ph2ParamsetLeafCountEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_paramset_leaf_count
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	int deleteByPrimaryKey(Long paramsetId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_paramset_leaf_count
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	int insert(Ph2ParamsetLeafCountEntity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_paramset_leaf_count
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	int insertSelective(Ph2ParamsetLeafCountEntity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_paramset_leaf_count
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	List<Ph2ParamsetLeafCountEntity> selectByExample(
			Ph2ParamsetLeafCountEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_paramset_leaf_count
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	Ph2ParamsetLeafCountEntity selectByPrimaryKey(Long paramsetId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_paramset_leaf_count
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	int updateByExampleSelective(@Param("row") Ph2ParamsetLeafCountEntity row,
			@Param("example") Ph2ParamsetLeafCountEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_paramset_leaf_count
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	int updateByExample(@Param("row") Ph2ParamsetLeafCountEntity row,
			@Param("example") Ph2ParamsetLeafCountEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_paramset_leaf_count
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	int updateByPrimaryKeySelective(Ph2ParamsetLeafCountEntity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_paramset_leaf_count
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	int updateByPrimaryKey(Ph2ParamsetLeafCountEntity row);

	List<Ph2ParamsetLeafCountEntity> selectByDefautFlag(@Param("deviceId") Long deviceId);
}