package com.logpose.ph2.api.dao.db.mappers;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.logpose.ph2.api.dao.db.entity.Ph2ParamsetHistoryEntity;
import com.logpose.ph2.api.dao.db.entity.Ph2ParamsetHistoryEntityExample;
@Mapper
public interface Ph2ParamsetHistoryMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_paramset_history
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	long countByExample(Ph2ParamsetHistoryEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_paramset_history
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	int deleteByExample(Ph2ParamsetHistoryEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_paramset_history
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	int insert(Ph2ParamsetHistoryEntity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_paramset_history
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	int insertSelective(Ph2ParamsetHistoryEntity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_paramset_history
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	List<Ph2ParamsetHistoryEntity> selectByExample(Ph2ParamsetHistoryEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_paramset_history
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	int updateByExampleSelective(@Param("row") Ph2ParamsetHistoryEntity row,
			@Param("example") Ph2ParamsetHistoryEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_paramset_history
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	int updateByExample(@Param("row") Ph2ParamsetHistoryEntity row,
			@Param("example") Ph2ParamsetHistoryEntityExample example);
}