package com.logpose.ph2.api.dao.db.mappers;

import com.logpose.ph2.api.dao.db.entity.Ph2RealFruitsBearingEntity;
import com.logpose.ph2.api.dao.db.entity.Ph2RealFruitsBearingEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Ph2RealFruitsBearingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph2_real_fruits_bearing
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    long countByExample(Ph2RealFruitsBearingEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph2_real_fruits_bearing
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    int deleteByExample(Ph2RealFruitsBearingEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph2_real_fruits_bearing
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    int deleteByPrimaryKey(Long deviceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph2_real_fruits_bearing
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    int insert(Ph2RealFruitsBearingEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph2_real_fruits_bearing
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    int insertSelective(Ph2RealFruitsBearingEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph2_real_fruits_bearing
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    List<Ph2RealFruitsBearingEntity> selectByExample(Ph2RealFruitsBearingEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph2_real_fruits_bearing
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    Ph2RealFruitsBearingEntity selectByPrimaryKey(Long deviceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph2_real_fruits_bearing
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    int updateByExampleSelective(@Param("row") Ph2RealFruitsBearingEntity row, @Param("example") Ph2RealFruitsBearingEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph2_real_fruits_bearing
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    int updateByExample(@Param("row") Ph2RealFruitsBearingEntity row, @Param("example") Ph2RealFruitsBearingEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph2_real_fruits_bearing
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    int updateByPrimaryKeySelective(Ph2RealFruitsBearingEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph2_real_fruits_bearing
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    int updateByPrimaryKey(Ph2RealFruitsBearingEntity row);
}