package com.logpose.ph2.api.dao.db.mappers;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.logpose.ph2.api.dao.db.entity.Ph2RealPsAmountEntity;
import com.logpose.ph2.api.dao.db.entity.Ph2RealPsAmountEntityExample;
@Mapper
public interface Ph2RealPsAmountMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_real_ps_amount
	 * @mbg.generated  Wed Aug 02 13:44:57 JST 2023
	 */
	long countByExample(Ph2RealPsAmountEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_real_ps_amount
	 * @mbg.generated  Wed Aug 02 13:44:57 JST 2023
	 */
	int deleteByExample(Ph2RealPsAmountEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_real_ps_amount
	 * @mbg.generated  Wed Aug 02 13:44:57 JST 2023
	 */
	int insert(Ph2RealPsAmountEntity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_real_ps_amount
	 * @mbg.generated  Wed Aug 02 13:44:57 JST 2023
	 */
	int insertSelective(Ph2RealPsAmountEntity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_real_ps_amount
	 * @mbg.generated  Wed Aug 02 13:44:57 JST 2023
	 */
	List<Ph2RealPsAmountEntity> selectByExample(
			Ph2RealPsAmountEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_real_ps_amount
	 * @mbg.generated  Wed Aug 02 13:44:57 JST 2023
	 */
	int updateByExampleSelective(@Param("row") Ph2RealPsAmountEntity row,
			@Param("example") Ph2RealPsAmountEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_real_ps_amount
	 * @mbg.generated  Wed Aug 02 13:44:57 JST 2023
	 */
	int updateByExample(@Param("row") Ph2RealPsAmountEntity row,
			@Param("example") Ph2RealPsAmountEntityExample example);
}