package com.logpose.ph2.api.dao.db.mappers;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.logpose.ph2.api.dao.db.entity.Ph2RelBaseDataEntity;
import com.logpose.ph2.api.dao.db.entity.Ph2RelBaseDataEntityExample;
@Mapper
public interface Ph2RelBaseDataMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_rel_base_data
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	long countByExample(Ph2RelBaseDataEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_rel_base_data
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	int deleteByExample(Ph2RelBaseDataEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_rel_base_data
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_rel_base_data
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	int insert(Ph2RelBaseDataEntity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_rel_base_data
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	int insertSelective(Ph2RelBaseDataEntity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_rel_base_data
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	List<Ph2RelBaseDataEntity> selectByExample(Ph2RelBaseDataEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_rel_base_data
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	Ph2RelBaseDataEntity selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_rel_base_data
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	int updateByExampleSelective(@Param("row") Ph2RelBaseDataEntity row,
			@Param("example") Ph2RelBaseDataEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_rel_base_data
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	int updateByExample(@Param("row") Ph2RelBaseDataEntity row, @Param("example") Ph2RelBaseDataEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_rel_base_data
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	int updateByPrimaryKeySelective(Ph2RelBaseDataEntity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_rel_base_data
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	int updateByPrimaryKey(Ph2RelBaseDataEntity row);
}