package com.logpose.ph2.api.dao.db.mappers;

import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.logpose.ph2.api.dao.db.entity.Ph2RawDataEntity;
import com.logpose.ph2.api.dao.db.entity.Ph2RawDataEntityExample;
@Mapper
public interface Ph2RawDataMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_raw_data
	 * @mbg.generated
	 */
	long countByExample(Ph2RawDataEntityExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_raw_data
	 * @mbg.generated
	 */
	int deleteByExample(Ph2RawDataEntityExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_raw_data
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Long id);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_raw_data
	 * @mbg.generated
	 */
	int insert(Ph2RawDataEntity row);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_raw_data
	 * @mbg.generated
	 */
	int insertSelective(Ph2RawDataEntity row);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_raw_data
	 * @mbg.generated
	 */
	List<Ph2RawDataEntity> selectByExample(Ph2RawDataEntityExample example);
	List<Ph2RawDataEntity> selectForDate(@Param("sensorId") Long sensorId,
			@Param("startDate") Date startDate, @Param("endDate") Date endDate,
			@Param("startTime") Date startTime, @Param("endTime") Date endTime);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_raw_data
	 * @mbg.generated
	 */
	Ph2RawDataEntity selectByPrimaryKey(Long id);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_raw_data
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("row") Ph2RawDataEntity row, @Param("example") Ph2RawDataEntityExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_raw_data
	 * @mbg.generated
	 */
	int updateByExample(@Param("row") Ph2RawDataEntity row, @Param("example") Ph2RawDataEntityExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_raw_data
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Ph2RawDataEntity row);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_raw_data
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Ph2RawDataEntity row);

	int multiRowInsert(@Param("targets") List<Ph2RawDataEntity> targets);
	
	int deleteByDevice(@Param("deviceId") Long deviceId);
	
	List<Ph2RawDataEntity> selectByDevice(@Param("deviceId") Long deviceId, @Param("castedAt") Date castedAt);
}