package com.logpose.ph2.api.dao.db.mappers;

import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.logpose.ph2.api.dao.db.entity.Ph2RealLeafShootsCountEntity;
import com.logpose.ph2.api.dao.db.entity.Ph2RealLeafShootsCountEntityExample;

@Mapper
public interface Ph2RealLeafShootsCountMapper
	{

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_real_leaf_shoots_count
	 * @mbg.generated
	 */
	long countByExample(Ph2RealLeafShootsCountEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_real_leaf_shoots_count
	 * @mbg.generated
	 */
	int deleteByExample(Ph2RealLeafShootsCountEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_real_leaf_shoots_count
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(@Param("deviceId") Long deviceId, @Param("year") Short year);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_real_leaf_shoots_count
	 * @mbg.generated
	 */
	int insert(Ph2RealLeafShootsCountEntity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_real_leaf_shoots_count
	 * @mbg.generated
	 */
	int insertSelective(Ph2RealLeafShootsCountEntity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_real_leaf_shoots_count
	 * @mbg.generated
	 */
	List<Ph2RealLeafShootsCountEntity> selectByExample(Ph2RealLeafShootsCountEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_real_leaf_shoots_count
	 * @mbg.generated
	 */
	Ph2RealLeafShootsCountEntity selectByPrimaryKey(@Param("deviceId") Long deviceId, @Param("year") Short year);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_real_leaf_shoots_count
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("row") Ph2RealLeafShootsCountEntity row,
			@Param("example") Ph2RealLeafShootsCountEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_real_leaf_shoots_count
	 * @mbg.generated
	 */
	int updateByExample(@Param("row") Ph2RealLeafShootsCountEntity row,
			@Param("example") Ph2RealLeafShootsCountEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_real_leaf_shoots_count
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Ph2RealLeafShootsCountEntity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_real_leaf_shoots_count
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Ph2RealLeafShootsCountEntity row);

	List<Ph2RealLeafShootsCountEntity> selectByDeviceId(@Param("deviceId") Long deviceId,
			@Param("year") Short year);

	List<Ph2RealLeafShootsCountEntity> selectByDate(@Param("deviceId") Long deviceId,
			@Param("year") Short year, @Param("date") Date date);

	}