package com.logpose.ph2.api.dao.db.mappers;

import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.logpose.ph2.api.dao.db.entity.Ph2RealLeafShootsAreaEntity;
import com.logpose.ph2.api.dao.db.entity.Ph2RealLeafShootsAreaEntityExample;
@Mapper
public interface Ph2RealLeafShootsAreaMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_real_leaf_shoots_area
	 * @mbg.generated
	 */
	long countByExample(Ph2RealLeafShootsAreaEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_real_leaf_shoots_area
	 * @mbg.generated
	 */
	int deleteByExample(Ph2RealLeafShootsAreaEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_real_leaf_shoots_area
	 * @mbg.generated
	 */
	int insert(Ph2RealLeafShootsAreaEntity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_real_leaf_shoots_area
	 * @mbg.generated
	 */
	int insertSelective(Ph2RealLeafShootsAreaEntity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_real_leaf_shoots_area
	 * @mbg.generated
	 */
	List<Ph2RealLeafShootsAreaEntity> selectByExample(Ph2RealLeafShootsAreaEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_real_leaf_shoots_area
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("row") Ph2RealLeafShootsAreaEntity row,
			@Param("example") Ph2RealLeafShootsAreaEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_real_leaf_shoots_area
	 * @mbg.generated
	 */
	int updateByExample(@Param("row") Ph2RealLeafShootsAreaEntity row,
			@Param("example") Ph2RealLeafShootsAreaEntityExample example);

	List<Ph2RealLeafShootsAreaEntity> selectByDeviceId(@Param("deviceId") Long deviceId,
			@Param("year") Short year);

	List<Ph2RealLeafShootsAreaEntity> selectByDate(@Param("deviceId") Long deviceId,
			@Param("year") Short year, @Param("date") Date date);
}