package com.logpose.ph2.api.dao.db.mappers;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.logpose.ph2.api.dao.db.entity.Ph2RealLeafShootsCountEntity;
import com.logpose.ph2.api.dao.db.entity.Ph2RealLeafShootsCountEntityExample;
@Mapper
public interface Ph2RealLeafShootsCountMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_real_leaf_shoots_count
	 * @mbg.generated  Mon Jul 31 06:36:03 JST 2023
	 */
	long countByExample(Ph2RealLeafShootsCountEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_real_leaf_shoots_count
	 * @mbg.generated  Mon Jul 31 06:36:03 JST 2023
	 */
	int deleteByExample(Ph2RealLeafShootsCountEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_real_leaf_shoots_count
	 * @mbg.generated  Mon Jul 31 06:36:03 JST 2023
	 */
	int insert(Ph2RealLeafShootsCountEntity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_real_leaf_shoots_count
	 * @mbg.generated  Mon Jul 31 06:36:03 JST 2023
	 */
	int insertSelective(Ph2RealLeafShootsCountEntity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_real_leaf_shoots_count
	 * @mbg.generated  Mon Jul 31 06:36:03 JST 2023
	 */
	List<Ph2RealLeafShootsCountEntity> selectByExample(
			Ph2RealLeafShootsCountEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_real_leaf_shoots_count
	 * @mbg.generated  Mon Jul 31 06:36:03 JST 2023
	 */
	int updateByExampleSelective(@Param("row") Ph2RealLeafShootsCountEntity row,
			@Param("example") Ph2RealLeafShootsCountEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_real_leaf_shoots_count
	 * @mbg.generated  Mon Jul 31 06:36:03 JST 2023
	 */
	int updateByExample(@Param("row") Ph2RealLeafShootsCountEntity row,
			@Param("example") Ph2RealLeafShootsCountEntityExample example);
}