package com.logpose.ph2.api.dao.db.mappers;

import com.logpose.ph2.api.dao.db.entity.Ph2RawDataEntity;
import com.logpose.ph2.api.dao.db.entity.Ph2RawDataEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Ph2RawDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph2_raw_data
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    long countByExample(Ph2RawDataEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph2_raw_data
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    int deleteByExample(Ph2RawDataEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph2_raw_data
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    int insert(Ph2RawDataEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph2_raw_data
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    int insertSelective(Ph2RawDataEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph2_raw_data
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    List<Ph2RawDataEntity> selectByExample(Ph2RawDataEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph2_raw_data
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    int updateByExampleSelective(@Param("row") Ph2RawDataEntity row, @Param("example") Ph2RawDataEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph2_raw_data
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    int updateByExample(@Param("row") Ph2RawDataEntity row, @Param("example") Ph2RawDataEntityExample example);
}