package com.logpose.ph2.api.dao.db.mappers;

import com.logpose.ph2.api.dao.db.entity.Ph2RealGrowthFDateEntity;
import com.logpose.ph2.api.dao.db.entity.Ph2RealGrowthFDateEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Ph2RealGrowthFDateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph2_real_growth_f_date
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    long countByExample(Ph2RealGrowthFDateEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph2_real_growth_f_date
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    int deleteByExample(Ph2RealGrowthFDateEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph2_real_growth_f_date
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    int insert(Ph2RealGrowthFDateEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph2_real_growth_f_date
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    int insertSelective(Ph2RealGrowthFDateEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph2_real_growth_f_date
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    List<Ph2RealGrowthFDateEntity> selectByExample(Ph2RealGrowthFDateEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph2_real_growth_f_date
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    int updateByExampleSelective(@Param("row") Ph2RealGrowthFDateEntity row, @Param("example") Ph2RealGrowthFDateEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph2_real_growth_f_date
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    int updateByExample(@Param("row") Ph2RealGrowthFDateEntity row, @Param("example") Ph2RealGrowthFDateEntityExample example);
}