package com.logpose.ph2.api.dao.db.mappers;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.logpose.ph2.api.dao.db.entity.Ph2RelFieldDeviceEntity;
import com.logpose.ph2.api.dao.db.entity.Ph2RelFieldDeviceEntityExample;
@Mapper
public interface Ph2RelFieldDeviceMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_rel_field_device
	 * @mbg.generated  Tue Aug 01 04:16:34 JST 2023
	 */
	long countByExample(Ph2RelFieldDeviceEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_rel_field_device
	 * @mbg.generated  Tue Aug 01 04:16:34 JST 2023
	 */
	int deleteByExample(Ph2RelFieldDeviceEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_rel_field_device
	 * @mbg.generated  Tue Aug 01 04:16:34 JST 2023
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_rel_field_device
	 * @mbg.generated  Tue Aug 01 04:16:34 JST 2023
	 */
	int insert(Ph2RelFieldDeviceEntity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_rel_field_device
	 * @mbg.generated  Tue Aug 01 04:16:34 JST 2023
	 */
	int insertSelective(Ph2RelFieldDeviceEntity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_rel_field_device
	 * @mbg.generated  Tue Aug 01 04:16:34 JST 2023
	 */
	List<Ph2RelFieldDeviceEntity> selectByExample(
			Ph2RelFieldDeviceEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_rel_field_device
	 * @mbg.generated  Tue Aug 01 04:16:34 JST 2023
	 */
	Ph2RelFieldDeviceEntity selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_rel_field_device
	 * @mbg.generated  Tue Aug 01 04:16:34 JST 2023
	 */
	int updateByExampleSelective(@Param("row") Ph2RelFieldDeviceEntity row,
			@Param("example") Ph2RelFieldDeviceEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_rel_field_device
	 * @mbg.generated  Tue Aug 01 04:16:34 JST 2023
	 */
	int updateByExample(@Param("row") Ph2RelFieldDeviceEntity row,
			@Param("example") Ph2RelFieldDeviceEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_rel_field_device
	 * @mbg.generated  Tue Aug 01 04:16:34 JST 2023
	 */
	int updateByPrimaryKeySelective(Ph2RelFieldDeviceEntity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_rel_field_device
	 * @mbg.generated  Tue Aug 01 04:16:34 JST 2023
	 */
	int updateByPrimaryKey(Ph2RelFieldDeviceEntity row);
}