package com.logpose.ph2.api.dao.db.mappers;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.logpose.ph2.api.dao.db.entity.Ph2SystemStatusEntity;
import com.logpose.ph2.api.dao.db.entity.Ph2SystemStatusEntityExample;
@Mapper
public interface Ph2SystemStatusMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_system_status
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	long countByExample(Ph2SystemStatusEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_system_status
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	int deleteByExample(Ph2SystemStatusEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_system_status
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	int deleteByPrimaryKey(String tableName);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_system_status
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	int insert(Ph2SystemStatusEntity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_system_status
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	int insertSelective(Ph2SystemStatusEntity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_system_status
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	List<Ph2SystemStatusEntity> selectByExample(
			Ph2SystemStatusEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_system_status
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	Ph2SystemStatusEntity selectByPrimaryKey(String tableName);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_system_status
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	int updateByExampleSelective(@Param("row") Ph2SystemStatusEntity row,
			@Param("example") Ph2SystemStatusEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_system_status
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	int updateByExample(@Param("row") Ph2SystemStatusEntity row,
			@Param("example") Ph2SystemStatusEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_system_status
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	int updateByPrimaryKeySelective(Ph2SystemStatusEntity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_system_status
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	int updateByPrimaryKey(Ph2SystemStatusEntity row);
}