package com.logpose.ph2.api.dao.db.mappers;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.logpose.ph2.api.dao.db.entity.Ph2SensorModelsEntity;
import com.logpose.ph2.api.dao.db.entity.Ph2SensorModelsEntityExample;
import com.logpose.ph2.api.dto.element.Label;
@Mapper
public interface Ph2SensorModelsMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_sensor_models
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	long countByExample(Ph2SensorModelsEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_sensor_models
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	int deleteByExample(Ph2SensorModelsEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_sensor_models
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_sensor_models
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	int insert(Ph2SensorModelsEntity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_sensor_models
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	int insertSelective(Ph2SensorModelsEntity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_sensor_models
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	List<Ph2SensorModelsEntity> selectByExample(Ph2SensorModelsEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_sensor_models
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	Ph2SensorModelsEntity selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_sensor_models
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	int updateByExampleSelective(@Param("row") Ph2SensorModelsEntity row,
			@Param("example") Ph2SensorModelsEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_sensor_models
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	int updateByExample(@Param("row") Ph2SensorModelsEntity row,
			@Param("example") Ph2SensorModelsEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_sensor_models
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	int updateByPrimaryKeySelective(Ph2SensorModelsEntity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_sensor_models
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	int updateByPrimaryKey(Ph2SensorModelsEntity row);
	
	List<Label> getAll();
}