package com.logpose.ph2.api.dao.db.mappers;

import com.logpose.ph2.api.dao.db.entity.Ph2TemperatureEntity;
import com.logpose.ph2.api.dao.db.entity.Ph2TemperatureEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Ph2TemperatureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph2_temperature
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    long countByExample(Ph2TemperatureEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph2_temperature
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    int deleteByExample(Ph2TemperatureEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph2_temperature
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    int insert(Ph2TemperatureEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph2_temperature
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    int insertSelective(Ph2TemperatureEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph2_temperature
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    List<Ph2TemperatureEntity> selectByExample(Ph2TemperatureEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph2_temperature
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    int updateByExampleSelective(@Param("row") Ph2TemperatureEntity row, @Param("example") Ph2TemperatureEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph2_temperature
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    int updateByExample(@Param("row") Ph2TemperatureEntity row, @Param("example") Ph2TemperatureEntityExample example);
}