package com.logpose.ph2.api.dao.db.mappers;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.logpose.ph2.api.dao.db.entity.Ph2UsersEntity;
import com.logpose.ph2.api.dao.db.entity.Ph2UsersEntityExample;
@Mapper
public interface Ph2UsersMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_users
	 * @mbg.generated
	 */
	long countByExample(Ph2UsersEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_users
	 * @mbg.generated
	 */
	int deleteByExample(Ph2UsersEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_users
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_users
	 * @mbg.generated
	 */
	Long insert(Ph2UsersEntity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_users
	 * @mbg.generated
	 */
	int insertSelective(Ph2UsersEntity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_users
	 * @mbg.generated
	 */
	List<Ph2UsersEntity> selectByExample(Ph2UsersEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_users
	 * @mbg.generated
	 */
	Ph2UsersEntity selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_users
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("row") Ph2UsersEntity row, @Param("example") Ph2UsersEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_users
	 * @mbg.generated
	 */
	int updateByExample(@Param("row") Ph2UsersEntity row, @Param("example") Ph2UsersEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_users
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Ph2UsersEntity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_users
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Ph2UsersEntity row);
}