package com.logpose.ph2.api.dao.db.mappers;

import com.logpose.ph2.api.dao.db.entity.Ph2VoltageDataEntity;
import com.logpose.ph2.api.dao.db.entity.Ph2VoltageDataEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Ph2VoltageDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph2_voltage_data
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    long countByExample(Ph2VoltageDataEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph2_voltage_data
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    int deleteByExample(Ph2VoltageDataEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph2_voltage_data
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    int insert(Ph2VoltageDataEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph2_voltage_data
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    int insertSelective(Ph2VoltageDataEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph2_voltage_data
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    List<Ph2VoltageDataEntity> selectByExample(Ph2VoltageDataEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph2_voltage_data
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    int updateByExampleSelective(@Param("row") Ph2VoltageDataEntity row, @Param("example") Ph2VoltageDataEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph2_voltage_data
     *
     * @mbg.generated Sat Jul 15 16:35:56 JST 2023
     */
    int updateByExample(@Param("row") Ph2VoltageDataEntity row, @Param("example") Ph2VoltageDataEntityExample example);
}