package com.logpose.ph2.api.dao.db.mappers;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.logpose.ph2.api.dao.db.entity.Ph2WibleMasterEntity;
import com.logpose.ph2.api.dao.db.entity.Ph2WibleMasterEntityExample;
@Mapper
public interface Ph2WibleMasterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph2_wible_master
     *
     * @mbg.generated
     */
    long countByExample(Ph2WibleMasterEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph2_wible_master
     *
     * @mbg.generated
     */
    int deleteByExample(Ph2WibleMasterEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph2_wible_master
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Short lapseDays);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph2_wible_master
     *
     * @mbg.generated
     */
    int insert(Ph2WibleMasterEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph2_wible_master
     *
     * @mbg.generated
     */
    int insertSelective(Ph2WibleMasterEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph2_wible_master
     *
     * @mbg.generated
     */
    List<Ph2WibleMasterEntity> selectByExample(Ph2WibleMasterEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph2_wible_master
     *
     * @mbg.generated
     */
    Ph2WibleMasterEntity selectByPrimaryKey(Short lapseDays);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph2_wible_master
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") Ph2WibleMasterEntity row, @Param("example") Ph2WibleMasterEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph2_wible_master
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") Ph2WibleMasterEntity row, @Param("example") Ph2WibleMasterEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph2_wible_master
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Ph2WibleMasterEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph2_wible_master
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Ph2WibleMasterEntity row);
}