package com.logpose.ph2.api.dao.db.mappers;

import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.logpose.ph2.api.dao.db.entity.Ph2WeatherDailyMasterEntity;
import com.logpose.ph2.api.dao.db.entity.Ph2WeatherDailyMasterEntityExample;

@Mapper
public interface Ph2WeatherDailyMasterMapper
	{

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_weather_daily_master
	 * @mbg.generated
	 */
	long countByExample(Ph2WeatherDailyMasterEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_weather_daily_master
	 * @mbg.generated
	 */
	int deleteByExample(Ph2WeatherDailyMasterEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_weather_daily_master
	 * @mbg.generated
	 */
	int insert(Ph2WeatherDailyMasterEntity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_weather_daily_master
	 * @mbg.generated
	 */
	int insertSelective(Ph2WeatherDailyMasterEntity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_weather_daily_master
	 * @mbg.generated
	 */
	List<Ph2WeatherDailyMasterEntity> selectByExample(Ph2WeatherDailyMasterEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_weather_daily_master
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("row") Ph2WeatherDailyMasterEntity row,
			@Param("example") Ph2WeatherDailyMasterEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_weather_daily_master
	 * @mbg.generated
	 */
	int updateByExample(@Param("row") Ph2WeatherDailyMasterEntity row,
			@Param("example") Ph2WeatherDailyMasterEntityExample example);

	void multiRowInsert(@Param("targets") List<Ph2WeatherDailyMasterEntity> entities);

	Ph2WeatherDailyMasterEntity selectByDate(@Param("deviceId") Long deviceId, @Param("castedAt") Date castedAt);
	}