package com.logpose.ph2.api.dao.db.mappers;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.logpose.ph2.api.dao.db.entity.Ph2WeatherForecastEntity;
import com.logpose.ph2.api.dao.db.entity.Ph2WeatherForecastEntityExample;
import com.logpose.ph2.api.dto.dashboard.DashboardForecast;

@Mapper
public interface Ph2WeatherForecastMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_wheather_forecast
	 * @mbg.generated
	 */
	long countByExample(Ph2WeatherForecastEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_wheather_forecast
	 * @mbg.generated
	 */
	int deleteByExample(Ph2WeatherForecastEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_wheather_forecast
	 * @mbg.generated
	 */
	int insert(Ph2WeatherForecastEntity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_wheather_forecast
	 * @mbg.generated
	 */
	int insertSelective(Ph2WeatherForecastEntity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_wheather_forecast
	 * @mbg.generated
	 */
	List<Ph2WeatherForecastEntity> selectByExample(Ph2WeatherForecastEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_wheather_forecast
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("row") Ph2WeatherForecastEntity row,
			@Param("example") Ph2WeatherForecastEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_wheather_forecast
	 * @mbg.generated
	 */
	int updateByExample(@Param("row") Ph2WeatherForecastEntity row,
			@Param("example") Ph2WeatherForecastEntityExample example);
	
	List<DashboardForecast> selectWithText(@Param("deviceId") Long deviceId);
}