package com.logpose.ph2.api.dao.db.mappers;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.logpose.ph2.api.dao.db.entity.SensorSizesEntity;
import com.logpose.ph2.api.dao.db.entity.SensorSizesEntityExample;
import com.logpose.ph2.api.dto.element.Label;
@Mapper
public interface SensorSizesMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_sensor_sizes
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	long countByExample(SensorSizesEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_sensor_sizes
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	int deleteByExample(SensorSizesEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_sensor_sizes
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_sensor_sizes
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	int insert(SensorSizesEntity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_sensor_sizes
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	int insertSelective(SensorSizesEntity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_sensor_sizes
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	List<SensorSizesEntity> selectByExample(SensorSizesEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_sensor_sizes
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	SensorSizesEntity selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_sensor_sizes
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	int updateByExampleSelective(@Param("row") SensorSizesEntity row,
			@Param("example") SensorSizesEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_sensor_sizes
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	int updateByExample(@Param("row") SensorSizesEntity row, @Param("example") SensorSizesEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_sensor_sizes
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	int updateByPrimaryKeySelective(SensorSizesEntity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_sensor_sizes
	 * @mbg.generated  Sat Jul 15 16:35:56 JST 2023
	 */
	int updateByPrimaryKey(SensorSizesEntity row);
	
	List<Label> getAll();
}