package com.logpose.ph2.batch.dao.db.entity;

import java.util.Date;

public class Ph2DashBoardEntity {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_dashboard.device_id
	 * @mbg.generated  Sat Sep 16 17:32:32 JST 2023
	 */
	private Long deviceId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_dashboard.casted_at
	 * @mbg.generated  Sat Sep 16 17:32:32 JST 2023
	 */
	private Date castedAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_dashboard.content_id
	 * @mbg.generated  Sat Sep 16 17:32:32 JST 2023
	 */
	private Long contentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_dashboard.value
	 * @mbg.generated  Sat Sep 16 17:32:32 JST 2023
	 */
	private String value;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_dashboard.sensor_id
	 * @mbg.generated  Sat Sep 16 17:32:32 JST 2023
	 */
	private Long sensorId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_dashboard.device_id
	 * @return  the value of ph2_dashboard.device_id
	 * @mbg.generated  Sat Sep 16 17:32:32 JST 2023
	 */
	public Long getDeviceId()
		{
		return deviceId;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_dashboard.device_id
	 * @param deviceId  the value for ph2_dashboard.device_id
	 * @mbg.generated  Sat Sep 16 17:32:32 JST 2023
	 */
	public void setDeviceId(Long deviceId)
		{
		this.deviceId = deviceId;
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_dashboard.casted_at
	 * @return  the value of ph2_dashboard.casted_at
	 * @mbg.generated  Sat Sep 16 17:32:32 JST 2023
	 */
	public Date getCastedAt()
		{
		return castedAt;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_dashboard.casted_at
	 * @param castedAt  the value for ph2_dashboard.casted_at
	 * @mbg.generated  Sat Sep 16 17:32:32 JST 2023
	 */
	public void setCastedAt(Date castedAt)
		{
		this.castedAt = castedAt;
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_dashboard.content_id
	 * @return  the value of ph2_dashboard.content_id
	 * @mbg.generated  Sat Sep 16 17:32:32 JST 2023
	 */
	public Long getContentId()
		{
		return contentId;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_dashboard.content_id
	 * @param contentId  the value for ph2_dashboard.content_id
	 * @mbg.generated  Sat Sep 16 17:32:32 JST 2023
	 */
	public void setContentId(Long contentId)
		{
		this.contentId = contentId;
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_dashboard.value
	 * @return  the value of ph2_dashboard.value
	 * @mbg.generated  Sat Sep 16 17:32:32 JST 2023
	 */
	public String getValue()
		{
		return value;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_dashboard.value
	 * @param value  the value for ph2_dashboard.value
	 * @mbg.generated  Sat Sep 16 17:32:32 JST 2023
	 */
	public void setValue(String value)
		{
		this.value = value == null ? null : value.trim();
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_dashboard.sensor_id
	 * @return  the value of ph2_dashboard.sensor_id
	 * @mbg.generated  Sat Sep 16 17:32:32 JST 2023
	 */
	public Long getSensorId()
		{
		return sensorId;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_dashboard.sensor_id
	 * @param sensorId  the value for ph2_dashboard.sensor_id
	 * @mbg.generated  Sat Sep 16 17:32:32 JST 2023
	 */
	public void setSensorId(Long sensorId)
		{
		this.sensorId = sensorId;
		}
}