package com.logpose.ph2.batch.dao.db.entity;

import java.util.Date;

public class Ph2FDataEntity {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_fdata.fstage_id
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	private Long fstageId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_fdata.date
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	private Date date;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_fdata.fvalue
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	private Double fvalue;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_fdata.is_effective
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	private Boolean isEffective;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_fdata.f_sig_value
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	private Double fSigValue;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_fdata.fstage_id
	 * @return  the value of ph2_fdata.fstage_id
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	public Long getFstageId()
		{
		return fstageId;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_fdata.fstage_id
	 * @param fstageId  the value for ph2_fdata.fstage_id
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	public void setFstageId(Long fstageId)
		{
		this.fstageId = fstageId;
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_fdata.date
	 * @return  the value of ph2_fdata.date
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	public Date getDate()
		{
		return date;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_fdata.date
	 * @param date  the value for ph2_fdata.date
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	public void setDate(Date date)
		{
		this.date = date;
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_fdata.fvalue
	 * @return  the value of ph2_fdata.fvalue
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	public Double getFvalue()
		{
		return fvalue;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_fdata.fvalue
	 * @param fvalue  the value for ph2_fdata.fvalue
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	public void setFvalue(Double fvalue)
		{
		this.fvalue = fvalue;
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_fdata.is_effective
	 * @return  the value of ph2_fdata.is_effective
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	public Boolean getIsEffective()
		{
		return isEffective;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_fdata.is_effective
	 * @param isEffective  the value for ph2_fdata.is_effective
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	public void setIsEffective(Boolean isEffective)
		{
		this.isEffective = isEffective;
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_fdata.f_sig_value
	 * @return  the value of ph2_fdata.f_sig_value
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	public Double getfSigValue()
		{
		return fSigValue;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_fdata.f_sig_value
	 * @param fSigValue  the value for ph2_fdata.f_sig_value
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	public void setfSigValue(Double fSigValue)
		{
		this.fSigValue = fSigValue;
		}
}