package com.logpose.ph2.batch.dao.db.entity;

public class Ph2InsolationDataEntity {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_insolation_data.relation_id
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	private Long relationId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_insolation_data.sensor_id
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	private Long sensorId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_insolation_data.insolation_intensity
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	private Double insolationIntensity;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_insolation_data.relation_id
	 * @return  the value of ph2_insolation_data.relation_id
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	public Long getRelationId()
		{
		return relationId;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_insolation_data.relation_id
	 * @param relationId  the value for ph2_insolation_data.relation_id
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	public void setRelationId(Long relationId)
		{
		this.relationId = relationId;
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_insolation_data.sensor_id
	 * @return  the value of ph2_insolation_data.sensor_id
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	public Long getSensorId()
		{
		return sensorId;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_insolation_data.sensor_id
	 * @param sensorId  the value for ph2_insolation_data.sensor_id
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	public void setSensorId(Long sensorId)
		{
		this.sensorId = sensorId;
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_insolation_data.insolation_intensity
	 * @return  the value of ph2_insolation_data.insolation_intensity
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	public Double getInsolationIntensity()
		{
		return insolationIntensity;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_insolation_data.insolation_intensity
	 * @param insolationIntensity  the value for ph2_insolation_data.insolation_intensity
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	public void setInsolationIntensity(Double insolationIntensity)
		{
		this.insolationIntensity = insolationIntensity;
		}
}