package com.logpose.ph2.batch.dao.db.entity;

import java.util.Date;

public class Ph2ModelDataEntity {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_model_data.day_id
	 * @mbg.generated  Sat Sep 16 17:32:32 JST 2023
	 */
	private Long dayId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_model_data.f_value
	 * @mbg.generated  Sat Sep 16 17:32:32 JST 2023
	 */
	private Double fValue;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_model_data.culmitive_cnopy_ps
	 * @mbg.generated  Sat Sep 16 17:32:32 JST 2023
	 */
	private Double culmitiveCnopyPs;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_model_data.crown_leaf_area
	 * @mbg.generated  Sat Sep 16 17:32:32 JST 2023
	 */
	private Double crownLeafArea;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_model_data.leaf_count
	 * @mbg.generated  Sat Sep 16 17:32:32 JST 2023
	 */
	private Double leafCount;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_model_data.day_id
	 * @return  the value of ph2_model_data.day_id
	 * @mbg.generated  Sat Sep 16 17:32:32 JST 2023
	 */
	public Long getDayId()
		{
		return dayId;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_model_data.day_id
	 * @param dayId  the value for ph2_model_data.day_id
	 * @mbg.generated  Sat Sep 16 17:32:32 JST 2023
	 */
	public void setDayId(Long dayId)
		{
		this.dayId = dayId;
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_model_data.f_value
	 * @return  the value of ph2_model_data.f_value
	 * @mbg.generated  Sat Sep 16 17:32:32 JST 2023
	 */
	public Double getfValue()
		{
		return fValue;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_model_data.f_value
	 * @param fValue  the value for ph2_model_data.f_value
	 * @mbg.generated  Sat Sep 16 17:32:32 JST 2023
	 */
	public void setfValue(Double fValue)
		{
		this.fValue = fValue;
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_model_data.culmitive_cnopy_ps
	 * @return  the value of ph2_model_data.culmitive_cnopy_ps
	 * @mbg.generated  Sat Sep 16 17:32:32 JST 2023
	 */
	public Double getCulmitiveCnopyPs()
		{
		return culmitiveCnopyPs;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_model_data.culmitive_cnopy_ps
	 * @param culmitiveCnopyPs  the value for ph2_model_data.culmitive_cnopy_ps
	 * @mbg.generated  Sat Sep 16 17:32:32 JST 2023
	 */
	public void setCulmitiveCnopyPs(Double culmitiveCnopyPs)
		{
		this.culmitiveCnopyPs = culmitiveCnopyPs;
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_model_data.crown_leaf_area
	 * @return  the value of ph2_model_data.crown_leaf_area
	 * @mbg.generated  Sat Sep 16 17:32:32 JST 2023
	 */
	public Double getCrownLeafArea()
		{
		return crownLeafArea;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_model_data.crown_leaf_area
	 * @param crownLeafArea  the value for ph2_model_data.crown_leaf_area
	 * @mbg.generated  Sat Sep 16 17:32:32 JST 2023
	 */
	public void setCrownLeafArea(Double crownLeafArea)
		{
		this.crownLeafArea = crownLeafArea;
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_model_data.leaf_count
	 * @return  the value of ph2_model_data.leaf_count
	 * @mbg.generated  Sat Sep 16 17:32:32 JST 2023
	 */
	public Double getLeafCount()
		{
		return leafCount;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_model_data.leaf_count
	 * @param leafCount  the value for ph2_model_data.leaf_count
	 * @mbg.generated  Sat Sep 16 17:32:32 JST 2023
	 */
	public void setLeafCount(Double leafCount)
		{
		this.leafCount = leafCount;
		}
}