package com.logpose.ph2.batch.dao.db.entity;

import java.util.Date;

public class Ph2ParamsetCatalogEntity {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_paramset_catalog.id
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_paramset_catalog.name
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_paramset_catalog.default_flag
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	private Boolean defaultFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_paramset_catalog.model_id
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	private Integer modelId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_paramset_catalog.created_at
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	private Date createdAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_paramset_catalog.updated_at
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	private Date updatedAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_paramset_catalog.device_id
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	private Long deviceId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_paramset_catalog.year
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	private Short year;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_paramset_catalog.id
	 * @return  the value of ph2_paramset_catalog.id
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	public Long getId()
		{
		return id;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_paramset_catalog.id
	 * @param id  the value for ph2_paramset_catalog.id
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	public void setId(Long id)
		{
		this.id = id;
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_paramset_catalog.name
	 * @return  the value of ph2_paramset_catalog.name
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	public String getName()
		{
		return name;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_paramset_catalog.name
	 * @param name  the value for ph2_paramset_catalog.name
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	public void setName(String name)
		{
		this.name = name == null ? null : name.trim();
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_paramset_catalog.default_flag
	 * @return  the value of ph2_paramset_catalog.default_flag
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	public Boolean getDefaultFlag()
		{
		return defaultFlag;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_paramset_catalog.default_flag
	 * @param defaultFlag  the value for ph2_paramset_catalog.default_flag
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	public void setDefaultFlag(Boolean defaultFlag)
		{
		this.defaultFlag = defaultFlag;
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_paramset_catalog.model_id
	 * @return  the value of ph2_paramset_catalog.model_id
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	public Integer getModelId()
		{
		return modelId;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_paramset_catalog.model_id
	 * @param modelId  the value for ph2_paramset_catalog.model_id
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	public void setModelId(Integer modelId)
		{
		this.modelId = modelId;
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_paramset_catalog.created_at
	 * @return  the value of ph2_paramset_catalog.created_at
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	public Date getCreatedAt()
		{
		return createdAt;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_paramset_catalog.created_at
	 * @param createdAt  the value for ph2_paramset_catalog.created_at
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	public void setCreatedAt(Date createdAt)
		{
		this.createdAt = createdAt;
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_paramset_catalog.updated_at
	 * @return  the value of ph2_paramset_catalog.updated_at
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	public Date getUpdatedAt()
		{
		return updatedAt;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_paramset_catalog.updated_at
	 * @param updatedAt  the value for ph2_paramset_catalog.updated_at
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	public void setUpdatedAt(Date updatedAt)
		{
		this.updatedAt = updatedAt;
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_paramset_catalog.device_id
	 * @return  the value of ph2_paramset_catalog.device_id
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	public Long getDeviceId()
		{
		return deviceId;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_paramset_catalog.device_id
	 * @param deviceId  the value for ph2_paramset_catalog.device_id
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	public void setDeviceId(Long deviceId)
		{
		this.deviceId = deviceId;
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_paramset_catalog.year
	 * @return  the value of ph2_paramset_catalog.year
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	public Short getYear()
		{
		return year;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_paramset_catalog.year
	 * @param year  the value for ph2_paramset_catalog.year
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	public void setYear(Short year)
		{
		this.year = year;
		}
}