package com.logpose.ph2.batch.dao.db.entity;

import java.util.Date;

public class Ph2ParamsetLeafCountEntity {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_paramset_leaf_count.paramset_id
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	private Long paramsetId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_paramset_leaf_count.value_c
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	private Double valueC;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_paramset_leaf_count.value_d
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	private Double valueD;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_paramset_leaf_count.created_at
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	private Date createdAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_paramset_leaf_count.updated_at
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	private Date updatedAt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_paramset_leaf_count.paramset_id
	 * @return  the value of ph2_paramset_leaf_count.paramset_id
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	public Long getParamsetId()
		{
		return paramsetId;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_paramset_leaf_count.paramset_id
	 * @param paramsetId  the value for ph2_paramset_leaf_count.paramset_id
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	public void setParamsetId(Long paramsetId)
		{
		this.paramsetId = paramsetId;
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_paramset_leaf_count.value_c
	 * @return  the value of ph2_paramset_leaf_count.value_c
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	public Double getValueC()
		{
		return valueC;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_paramset_leaf_count.value_c
	 * @param valueC  the value for ph2_paramset_leaf_count.value_c
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	public void setValueC(Double valueC)
		{
		this.valueC = valueC;
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_paramset_leaf_count.value_d
	 * @return  the value of ph2_paramset_leaf_count.value_d
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	public Double getValueD()
		{
		return valueD;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_paramset_leaf_count.value_d
	 * @param valueD  the value for ph2_paramset_leaf_count.value_d
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	public void setValueD(Double valueD)
		{
		this.valueD = valueD;
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_paramset_leaf_count.created_at
	 * @return  the value of ph2_paramset_leaf_count.created_at
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	public Date getCreatedAt()
		{
		return createdAt;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_paramset_leaf_count.created_at
	 * @param createdAt  the value for ph2_paramset_leaf_count.created_at
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	public void setCreatedAt(Date createdAt)
		{
		this.createdAt = createdAt;
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_paramset_leaf_count.updated_at
	 * @return  the value of ph2_paramset_leaf_count.updated_at
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	public Date getUpdatedAt()
		{
		return updatedAt;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_paramset_leaf_count.updated_at
	 * @param updatedAt  the value for ph2_paramset_leaf_count.updated_at
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	public void setUpdatedAt(Date updatedAt)
		{
		this.updatedAt = updatedAt;
		}
}