package com.logpose.ph2.batch.dao.db.entity;

import java.util.Date;

public class Ph2RealLeafShootsCountEntity {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_real_leaf_shoots_count.device_id
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	private Long deviceId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_real_leaf_shoots_count.target_date
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	private Date targetDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_real_leaf_shoots_count.count
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	private Integer count;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_real_leaf_shoots_count.created_at
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	private Date createdAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_real_leaf_shoots_count.updated_at
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	private Date updatedAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_real_leaf_shoots_count.year
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	private Short year;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_real_leaf_shoots_count.device_id
	 * @return  the value of ph2_real_leaf_shoots_count.device_id
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	public Long getDeviceId()
		{
		return deviceId;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_real_leaf_shoots_count.device_id
	 * @param deviceId  the value for ph2_real_leaf_shoots_count.device_id
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	public void setDeviceId(Long deviceId)
		{
		this.deviceId = deviceId;
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_real_leaf_shoots_count.target_date
	 * @return  the value of ph2_real_leaf_shoots_count.target_date
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	public Date getTargetDate()
		{
		return targetDate;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_real_leaf_shoots_count.target_date
	 * @param targetDate  the value for ph2_real_leaf_shoots_count.target_date
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	public void setTargetDate(Date targetDate)
		{
		this.targetDate = targetDate;
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_real_leaf_shoots_count.count
	 * @return  the value of ph2_real_leaf_shoots_count.count
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	public Integer getCount()
		{
		return count;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_real_leaf_shoots_count.count
	 * @param count  the value for ph2_real_leaf_shoots_count.count
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	public void setCount(Integer count)
		{
		this.count = count;
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_real_leaf_shoots_count.created_at
	 * @return  the value of ph2_real_leaf_shoots_count.created_at
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	public Date getCreatedAt()
		{
		return createdAt;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_real_leaf_shoots_count.created_at
	 * @param createdAt  the value for ph2_real_leaf_shoots_count.created_at
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	public void setCreatedAt(Date createdAt)
		{
		this.createdAt = createdAt;
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_real_leaf_shoots_count.updated_at
	 * @return  the value of ph2_real_leaf_shoots_count.updated_at
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	public Date getUpdatedAt()
		{
		return updatedAt;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_real_leaf_shoots_count.updated_at
	 * @param updatedAt  the value for ph2_real_leaf_shoots_count.updated_at
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	public void setUpdatedAt(Date updatedAt)
		{
		this.updatedAt = updatedAt;
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_real_leaf_shoots_count.year
	 * @return  the value of ph2_real_leaf_shoots_count.year
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	public Short getYear()
		{
		return year;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_real_leaf_shoots_count.year
	 * @param year  the value for ph2_real_leaf_shoots_count.year
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	public void setYear(Short year)
		{
		this.year = year;
		}
}