package com.logpose.ph2.batch.dao.db.entity;

import java.util.Date;

public class Ph2SensorModelsEntity {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_sensor_models.id
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_sensor_models.code
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_sensor_models.created_at
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	private Date createdAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ph2_sensor_models.updated_at
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	private Date updatedAt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_sensor_models.id
	 * @return  the value of ph2_sensor_models.id
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	public Long getId()
		{
		return id;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_sensor_models.id
	 * @param id  the value for ph2_sensor_models.id
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	public void setId(Long id)
		{
		this.id = id;
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_sensor_models.code
	 * @return  the value of ph2_sensor_models.code
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	public String getCode()
		{
		return code;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_sensor_models.code
	 * @param code  the value for ph2_sensor_models.code
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	public void setCode(String code)
		{
		this.code = code == null ? null : code.trim();
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_sensor_models.created_at
	 * @return  the value of ph2_sensor_models.created_at
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	public Date getCreatedAt()
		{
		return createdAt;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_sensor_models.created_at
	 * @param createdAt  the value for ph2_sensor_models.created_at
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	public void setCreatedAt(Date createdAt)
		{
		this.createdAt = createdAt;
		}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ph2_sensor_models.updated_at
	 * @return  the value of ph2_sensor_models.updated_at
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	public Date getUpdatedAt()
		{
		return updatedAt;
		}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ph2_sensor_models.updated_at
	 * @param updatedAt  the value for ph2_sensor_models.updated_at
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	public void setUpdatedAt(Date updatedAt)
		{
		this.updatedAt = updatedAt;
		}
}