package com.logpose.ph2.batch.dao.db.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SensorsEntityExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ph2_sensors
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ph2_sensors
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ph2_sensors
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_sensors
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	public SensorsEntityExample()
		{
		oredCriteria = new ArrayList<>();
		}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_sensors
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	public void setOrderByClause(String orderByClause)
		{
		this.orderByClause = orderByClause;
		}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_sensors
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	public String getOrderByClause()
		{
		return orderByClause;
		}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_sensors
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	public void setDistinct(boolean distinct)
		{
		this.distinct = distinct;
		}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_sensors
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	public boolean isDistinct()
		{
		return distinct;
		}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_sensors
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	public List<Criteria> getOredCriteria()
		{
		return oredCriteria;
		}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_sensors
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	public void or(Criteria criteria)
		{
		oredCriteria.add(criteria);
		}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_sensors
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	public Criteria or()
		{
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
		}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_sensors
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	public Criteria createCriteria()
		{
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0)
			{
			oredCriteria.add(criteria);
			}
		return criteria;
		}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_sensors
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	protected Criteria createCriteriaInternal()
		{
		Criteria criteria = new Criteria();
		return criteria;
		}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_sensors
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	public void clear()
		{
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
		}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table ph2_sensors
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	protected abstract static class GeneratedCriteria
		{
		protected List<Criterion> criteria;

		protected GeneratedCriteria()
			{
			super();
			criteria = new ArrayList<>();
			}

		public boolean isValid()
			{
			return criteria.size() > 0;
			}

		public List<Criterion> getAllCriteria()
			{
			return criteria;
			}

		public List<Criterion> getCriteria()
			{
			return criteria;
			}

		protected void addCriterion(String condition)
			{
			if (condition == null)
				{
				throw new RuntimeException(
						"Value for condition cannot be null");
				}
			criteria.add(new Criterion(condition));
			}

		protected void addCriterion(String condition, Object value,
				String property)
			{
			if (value == null)
				{
				throw new RuntimeException(
						"Value for " + property + " cannot be null");
				}
			criteria.add(new Criterion(condition, value));
			}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property)
			{
			if (value1 == null || value2 == null)
				{
				throw new RuntimeException(
						"Between values for " + property + " cannot be null");
				}
			criteria.add(new Criterion(condition, value1, value2));
			}

		public Criteria andIdIsNull()
			{
			addCriterion("id is null");
			return (Criteria) this;
			}

		public Criteria andIdIsNotNull()
			{
			addCriterion("id is not null");
			return (Criteria) this;
			}

		public Criteria andIdEqualTo(Long value)
			{
			addCriterion("id =", value, "id");
			return (Criteria) this;
			}

		public Criteria andIdNotEqualTo(Long value)
			{
			addCriterion("id <>", value, "id");
			return (Criteria) this;
			}

		public Criteria andIdGreaterThan(Long value)
			{
			addCriterion("id >", value, "id");
			return (Criteria) this;
			}

		public Criteria andIdGreaterThanOrEqualTo(Long value)
			{
			addCriterion("id >=", value, "id");
			return (Criteria) this;
			}

		public Criteria andIdLessThan(Long value)
			{
			addCriterion("id <", value, "id");
			return (Criteria) this;
			}

		public Criteria andIdLessThanOrEqualTo(Long value)
			{
			addCriterion("id <=", value, "id");
			return (Criteria) this;
			}

		public Criteria andIdIn(List<Long> values)
			{
			addCriterion("id in", values, "id");
			return (Criteria) this;
			}

		public Criteria andIdNotIn(List<Long> values)
			{
			addCriterion("id not in", values, "id");
			return (Criteria) this;
			}

		public Criteria andIdBetween(Long value1, Long value2)
			{
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
			}

		public Criteria andIdNotBetween(Long value1, Long value2)
			{
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
			}

		public Criteria andDeviceIdIsNull()
			{
			addCriterion("device_id is null");
			return (Criteria) this;
			}

		public Criteria andDeviceIdIsNotNull()
			{
			addCriterion("device_id is not null");
			return (Criteria) this;
			}

		public Criteria andDeviceIdEqualTo(Long value)
			{
			addCriterion("device_id =", value, "deviceId");
			return (Criteria) this;
			}

		public Criteria andDeviceIdNotEqualTo(Long value)
			{
			addCriterion("device_id <>", value, "deviceId");
			return (Criteria) this;
			}

		public Criteria andDeviceIdGreaterThan(Long value)
			{
			addCriterion("device_id >", value, "deviceId");
			return (Criteria) this;
			}

		public Criteria andDeviceIdGreaterThanOrEqualTo(Long value)
			{
			addCriterion("device_id >=", value, "deviceId");
			return (Criteria) this;
			}

		public Criteria andDeviceIdLessThan(Long value)
			{
			addCriterion("device_id <", value, "deviceId");
			return (Criteria) this;
			}

		public Criteria andDeviceIdLessThanOrEqualTo(Long value)
			{
			addCriterion("device_id <=", value, "deviceId");
			return (Criteria) this;
			}

		public Criteria andDeviceIdIn(List<Long> values)
			{
			addCriterion("device_id in", values, "deviceId");
			return (Criteria) this;
			}

		public Criteria andDeviceIdNotIn(List<Long> values)
			{
			addCriterion("device_id not in", values, "deviceId");
			return (Criteria) this;
			}

		public Criteria andDeviceIdBetween(Long value1, Long value2)
			{
			addCriterion("device_id between", value1, value2, "deviceId");
			return (Criteria) this;
			}

		public Criteria andDeviceIdNotBetween(Long value1, Long value2)
			{
			addCriterion("device_id not between", value1, value2, "deviceId");
			return (Criteria) this;
			}

		public Criteria andChannelIsNull()
			{
			addCriterion("channel is null");
			return (Criteria) this;
			}

		public Criteria andChannelIsNotNull()
			{
			addCriterion("channel is not null");
			return (Criteria) this;
			}

		public Criteria andChannelEqualTo(Integer value)
			{
			addCriterion("channel =", value, "channel");
			return (Criteria) this;
			}

		public Criteria andChannelNotEqualTo(Integer value)
			{
			addCriterion("channel <>", value, "channel");
			return (Criteria) this;
			}

		public Criteria andChannelGreaterThan(Integer value)
			{
			addCriterion("channel >", value, "channel");
			return (Criteria) this;
			}

		public Criteria andChannelGreaterThanOrEqualTo(Integer value)
			{
			addCriterion("channel >=", value, "channel");
			return (Criteria) this;
			}

		public Criteria andChannelLessThan(Integer value)
			{
			addCriterion("channel <", value, "channel");
			return (Criteria) this;
			}

		public Criteria andChannelLessThanOrEqualTo(Integer value)
			{
			addCriterion("channel <=", value, "channel");
			return (Criteria) this;
			}

		public Criteria andChannelIn(List<Integer> values)
			{
			addCriterion("channel in", values, "channel");
			return (Criteria) this;
			}

		public Criteria andChannelNotIn(List<Integer> values)
			{
			addCriterion("channel not in", values, "channel");
			return (Criteria) this;
			}

		public Criteria andChannelBetween(Integer value1, Integer value2)
			{
			addCriterion("channel between", value1, value2, "channel");
			return (Criteria) this;
			}

		public Criteria andChannelNotBetween(Integer value1, Integer value2)
			{
			addCriterion("channel not between", value1, value2, "channel");
			return (Criteria) this;
			}

		public Criteria andSensorSizeIdIsNull()
			{
			addCriterion("sensor_size_id is null");
			return (Criteria) this;
			}

		public Criteria andSensorSizeIdIsNotNull()
			{
			addCriterion("sensor_size_id is not null");
			return (Criteria) this;
			}

		public Criteria andSensorSizeIdEqualTo(Long value)
			{
			addCriterion("sensor_size_id =", value, "sensorSizeId");
			return (Criteria) this;
			}

		public Criteria andSensorSizeIdNotEqualTo(Long value)
			{
			addCriterion("sensor_size_id <>", value, "sensorSizeId");
			return (Criteria) this;
			}

		public Criteria andSensorSizeIdGreaterThan(Long value)
			{
			addCriterion("sensor_size_id >", value, "sensorSizeId");
			return (Criteria) this;
			}

		public Criteria andSensorSizeIdGreaterThanOrEqualTo(Long value)
			{
			addCriterion("sensor_size_id >=", value, "sensorSizeId");
			return (Criteria) this;
			}

		public Criteria andSensorSizeIdLessThan(Long value)
			{
			addCriterion("sensor_size_id <", value, "sensorSizeId");
			return (Criteria) this;
			}

		public Criteria andSensorSizeIdLessThanOrEqualTo(Long value)
			{
			addCriterion("sensor_size_id <=", value, "sensorSizeId");
			return (Criteria) this;
			}

		public Criteria andSensorSizeIdIn(List<Long> values)
			{
			addCriterion("sensor_size_id in", values, "sensorSizeId");
			return (Criteria) this;
			}

		public Criteria andSensorSizeIdNotIn(List<Long> values)
			{
			addCriterion("sensor_size_id not in", values, "sensorSizeId");
			return (Criteria) this;
			}

		public Criteria andSensorSizeIdBetween(Long value1, Long value2)
			{
			addCriterion("sensor_size_id between", value1, value2,
					"sensorSizeId");
			return (Criteria) this;
			}

		public Criteria andSensorSizeIdNotBetween(Long value1, Long value2)
			{
			addCriterion("sensor_size_id not between", value1, value2,
					"sensorSizeId");
			return (Criteria) this;
			}

		public Criteria andSensorContentIdIsNull()
			{
			addCriterion("sensor_content_id is null");
			return (Criteria) this;
			}

		public Criteria andSensorContentIdIsNotNull()
			{
			addCriterion("sensor_content_id is not null");
			return (Criteria) this;
			}

		public Criteria andSensorContentIdEqualTo(Long value)
			{
			addCriterion("sensor_content_id =", value, "sensorContentId");
			return (Criteria) this;
			}

		public Criteria andSensorContentIdNotEqualTo(Long value)
			{
			addCriterion("sensor_content_id <>", value, "sensorContentId");
			return (Criteria) this;
			}

		public Criteria andSensorContentIdGreaterThan(Long value)
			{
			addCriterion("sensor_content_id >", value, "sensorContentId");
			return (Criteria) this;
			}

		public Criteria andSensorContentIdGreaterThanOrEqualTo(Long value)
			{
			addCriterion("sensor_content_id >=", value, "sensorContentId");
			return (Criteria) this;
			}

		public Criteria andSensorContentIdLessThan(Long value)
			{
			addCriterion("sensor_content_id <", value, "sensorContentId");
			return (Criteria) this;
			}

		public Criteria andSensorContentIdLessThanOrEqualTo(Long value)
			{
			addCriterion("sensor_content_id <=", value, "sensorContentId");
			return (Criteria) this;
			}

		public Criteria andSensorContentIdIn(List<Long> values)
			{
			addCriterion("sensor_content_id in", values, "sensorContentId");
			return (Criteria) this;
			}

		public Criteria andSensorContentIdNotIn(List<Long> values)
			{
			addCriterion("sensor_content_id not in", values, "sensorContentId");
			return (Criteria) this;
			}

		public Criteria andSensorContentIdBetween(Long value1, Long value2)
			{
			addCriterion("sensor_content_id between", value1, value2,
					"sensorContentId");
			return (Criteria) this;
			}

		public Criteria andSensorContentIdNotBetween(Long value1, Long value2)
			{
			addCriterion("sensor_content_id not between", value1, value2,
					"sensorContentId");
			return (Criteria) this;
			}

		public Criteria andPlantIsNull()
			{
			addCriterion("plant is null");
			return (Criteria) this;
			}

		public Criteria andPlantIsNotNull()
			{
			addCriterion("plant is not null");
			return (Criteria) this;
			}

		public Criteria andPlantEqualTo(String value)
			{
			addCriterion("plant =", value, "plant");
			return (Criteria) this;
			}

		public Criteria andPlantNotEqualTo(String value)
			{
			addCriterion("plant <>", value, "plant");
			return (Criteria) this;
			}

		public Criteria andPlantGreaterThan(String value)
			{
			addCriterion("plant >", value, "plant");
			return (Criteria) this;
			}

		public Criteria andPlantGreaterThanOrEqualTo(String value)
			{
			addCriterion("plant >=", value, "plant");
			return (Criteria) this;
			}

		public Criteria andPlantLessThan(String value)
			{
			addCriterion("plant <", value, "plant");
			return (Criteria) this;
			}

		public Criteria andPlantLessThanOrEqualTo(String value)
			{
			addCriterion("plant <=", value, "plant");
			return (Criteria) this;
			}

		public Criteria andPlantLike(String value)
			{
			addCriterion("plant like", value, "plant");
			return (Criteria) this;
			}

		public Criteria andPlantNotLike(String value)
			{
			addCriterion("plant not like", value, "plant");
			return (Criteria) this;
			}

		public Criteria andPlantIn(List<String> values)
			{
			addCriterion("plant in", values, "plant");
			return (Criteria) this;
			}

		public Criteria andPlantNotIn(List<String> values)
			{
			addCriterion("plant not in", values, "plant");
			return (Criteria) this;
			}

		public Criteria andPlantBetween(String value1, String value2)
			{
			addCriterion("plant between", value1, value2, "plant");
			return (Criteria) this;
			}

		public Criteria andPlantNotBetween(String value1, String value2)
			{
			addCriterion("plant not between", value1, value2, "plant");
			return (Criteria) this;
			}

		public Criteria andKstIsNull()
			{
			addCriterion("kst is null");
			return (Criteria) this;
			}

		public Criteria andKstIsNotNull()
			{
			addCriterion("kst is not null");
			return (Criteria) this;
			}

		public Criteria andKstEqualTo(Double value)
			{
			addCriterion("kst =", value, "kst");
			return (Criteria) this;
			}

		public Criteria andKstNotEqualTo(Double value)
			{
			addCriterion("kst <>", value, "kst");
			return (Criteria) this;
			}

		public Criteria andKstGreaterThan(Double value)
			{
			addCriterion("kst >", value, "kst");
			return (Criteria) this;
			}

		public Criteria andKstGreaterThanOrEqualTo(Double value)
			{
			addCriterion("kst >=", value, "kst");
			return (Criteria) this;
			}

		public Criteria andKstLessThan(Double value)
			{
			addCriterion("kst <", value, "kst");
			return (Criteria) this;
			}

		public Criteria andKstLessThanOrEqualTo(Double value)
			{
			addCriterion("kst <=", value, "kst");
			return (Criteria) this;
			}

		public Criteria andKstIn(List<Double> values)
			{
			addCriterion("kst in", values, "kst");
			return (Criteria) this;
			}

		public Criteria andKstNotIn(List<Double> values)
			{
			addCriterion("kst not in", values, "kst");
			return (Criteria) this;
			}

		public Criteria andKstBetween(Double value1, Double value2)
			{
			addCriterion("kst between", value1, value2, "kst");
			return (Criteria) this;
			}

		public Criteria andKstNotBetween(Double value1, Double value2)
			{
			addCriterion("kst not between", value1, value2, "kst");
			return (Criteria) this;
			}

		public Criteria andSmIsNull()
			{
			addCriterion("sm is null");
			return (Criteria) this;
			}

		public Criteria andSmIsNotNull()
			{
			addCriterion("sm is not null");
			return (Criteria) this;
			}

		public Criteria andSmEqualTo(Double value)
			{
			addCriterion("sm =", value, "sm");
			return (Criteria) this;
			}

		public Criteria andSmNotEqualTo(Double value)
			{
			addCriterion("sm <>", value, "sm");
			return (Criteria) this;
			}

		public Criteria andSmGreaterThan(Double value)
			{
			addCriterion("sm >", value, "sm");
			return (Criteria) this;
			}

		public Criteria andSmGreaterThanOrEqualTo(Double value)
			{
			addCriterion("sm >=", value, "sm");
			return (Criteria) this;
			}

		public Criteria andSmLessThan(Double value)
			{
			addCriterion("sm <", value, "sm");
			return (Criteria) this;
			}

		public Criteria andSmLessThanOrEqualTo(Double value)
			{
			addCriterion("sm <=", value, "sm");
			return (Criteria) this;
			}

		public Criteria andSmIn(List<Double> values)
			{
			addCriterion("sm in", values, "sm");
			return (Criteria) this;
			}

		public Criteria andSmNotIn(List<Double> values)
			{
			addCriterion("sm not in", values, "sm");
			return (Criteria) this;
			}

		public Criteria andSmBetween(Double value1, Double value2)
			{
			addCriterion("sm between", value1, value2, "sm");
			return (Criteria) this;
			}

		public Criteria andSmNotBetween(Double value1, Double value2)
			{
			addCriterion("sm not between", value1, value2, "sm");
			return (Criteria) this;
			}

		public Criteria andLfIsNull()
			{
			addCriterion("lf is null");
			return (Criteria) this;
			}

		public Criteria andLfIsNotNull()
			{
			addCriterion("lf is not null");
			return (Criteria) this;
			}

		public Criteria andLfEqualTo(Double value)
			{
			addCriterion("lf =", value, "lf");
			return (Criteria) this;
			}

		public Criteria andLfNotEqualTo(Double value)
			{
			addCriterion("lf <>", value, "lf");
			return (Criteria) this;
			}

		public Criteria andLfGreaterThan(Double value)
			{
			addCriterion("lf >", value, "lf");
			return (Criteria) this;
			}

		public Criteria andLfGreaterThanOrEqualTo(Double value)
			{
			addCriterion("lf >=", value, "lf");
			return (Criteria) this;
			}

		public Criteria andLfLessThan(Double value)
			{
			addCriterion("lf <", value, "lf");
			return (Criteria) this;
			}

		public Criteria andLfLessThanOrEqualTo(Double value)
			{
			addCriterion("lf <=", value, "lf");
			return (Criteria) this;
			}

		public Criteria andLfIn(List<Double> values)
			{
			addCriterion("lf in", values, "lf");
			return (Criteria) this;
			}

		public Criteria andLfNotIn(List<Double> values)
			{
			addCriterion("lf not in", values, "lf");
			return (Criteria) this;
			}

		public Criteria andLfBetween(Double value1, Double value2)
			{
			addCriterion("lf between", value1, value2, "lf");
			return (Criteria) this;
			}

		public Criteria andLfNotBetween(Double value1, Double value2)
			{
			addCriterion("lf not between", value1, value2, "lf");
			return (Criteria) this;
			}

		public Criteria andCbIsNull()
			{
			addCriterion("cb is null");
			return (Criteria) this;
			}

		public Criteria andCbIsNotNull()
			{
			addCriterion("cb is not null");
			return (Criteria) this;
			}

		public Criteria andCbEqualTo(Double value)
			{
			addCriterion("cb =", value, "cb");
			return (Criteria) this;
			}

		public Criteria andCbNotEqualTo(Double value)
			{
			addCriterion("cb <>", value, "cb");
			return (Criteria) this;
			}

		public Criteria andCbGreaterThan(Double value)
			{
			addCriterion("cb >", value, "cb");
			return (Criteria) this;
			}

		public Criteria andCbGreaterThanOrEqualTo(Double value)
			{
			addCriterion("cb >=", value, "cb");
			return (Criteria) this;
			}

		public Criteria andCbLessThan(Double value)
			{
			addCriterion("cb <", value, "cb");
			return (Criteria) this;
			}

		public Criteria andCbLessThanOrEqualTo(Double value)
			{
			addCriterion("cb <=", value, "cb");
			return (Criteria) this;
			}

		public Criteria andCbIn(List<Double> values)
			{
			addCriterion("cb in", values, "cb");
			return (Criteria) this;
			}

		public Criteria andCbNotIn(List<Double> values)
			{
			addCriterion("cb not in", values, "cb");
			return (Criteria) this;
			}

		public Criteria andCbBetween(Double value1, Double value2)
			{
			addCriterion("cb between", value1, value2, "cb");
			return (Criteria) this;
			}

		public Criteria andCbNotBetween(Double value1, Double value2)
			{
			addCriterion("cb not between", value1, value2, "cb");
			return (Criteria) this;
			}

		public Criteria andSensorModelIdIsNull()
			{
			addCriterion("sensor_model_id is null");
			return (Criteria) this;
			}

		public Criteria andSensorModelIdIsNotNull()
			{
			addCriterion("sensor_model_id is not null");
			return (Criteria) this;
			}

		public Criteria andSensorModelIdEqualTo(Long value)
			{
			addCriterion("sensor_model_id =", value, "sensorModelId");
			return (Criteria) this;
			}

		public Criteria andSensorModelIdNotEqualTo(Long value)
			{
			addCriterion("sensor_model_id <>", value, "sensorModelId");
			return (Criteria) this;
			}

		public Criteria andSensorModelIdGreaterThan(Long value)
			{
			addCriterion("sensor_model_id >", value, "sensorModelId");
			return (Criteria) this;
			}

		public Criteria andSensorModelIdGreaterThanOrEqualTo(Long value)
			{
			addCriterion("sensor_model_id >=", value, "sensorModelId");
			return (Criteria) this;
			}

		public Criteria andSensorModelIdLessThan(Long value)
			{
			addCriterion("sensor_model_id <", value, "sensorModelId");
			return (Criteria) this;
			}

		public Criteria andSensorModelIdLessThanOrEqualTo(Long value)
			{
			addCriterion("sensor_model_id <=", value, "sensorModelId");
			return (Criteria) this;
			}

		public Criteria andSensorModelIdIn(List<Long> values)
			{
			addCriterion("sensor_model_id in", values, "sensorModelId");
			return (Criteria) this;
			}

		public Criteria andSensorModelIdNotIn(List<Long> values)
			{
			addCriterion("sensor_model_id not in", values, "sensorModelId");
			return (Criteria) this;
			}

		public Criteria andSensorModelIdBetween(Long value1, Long value2)
			{
			addCriterion("sensor_model_id between", value1, value2,
					"sensorModelId");
			return (Criteria) this;
			}

		public Criteria andSensorModelIdNotBetween(Long value1, Long value2)
			{
			addCriterion("sensor_model_id not between", value1, value2,
					"sensorModelId");
			return (Criteria) this;
			}

		public Criteria andNameIsNull()
			{
			addCriterion("name is null");
			return (Criteria) this;
			}

		public Criteria andNameIsNotNull()
			{
			addCriterion("name is not null");
			return (Criteria) this;
			}

		public Criteria andNameEqualTo(String value)
			{
			addCriterion("name =", value, "name");
			return (Criteria) this;
			}

		public Criteria andNameNotEqualTo(String value)
			{
			addCriterion("name <>", value, "name");
			return (Criteria) this;
			}

		public Criteria andNameGreaterThan(String value)
			{
			addCriterion("name >", value, "name");
			return (Criteria) this;
			}

		public Criteria andNameGreaterThanOrEqualTo(String value)
			{
			addCriterion("name >=", value, "name");
			return (Criteria) this;
			}

		public Criteria andNameLessThan(String value)
			{
			addCriterion("name <", value, "name");
			return (Criteria) this;
			}

		public Criteria andNameLessThanOrEqualTo(String value)
			{
			addCriterion("name <=", value, "name");
			return (Criteria) this;
			}

		public Criteria andNameLike(String value)
			{
			addCriterion("name like", value, "name");
			return (Criteria) this;
			}

		public Criteria andNameNotLike(String value)
			{
			addCriterion("name not like", value, "name");
			return (Criteria) this;
			}

		public Criteria andNameIn(List<String> values)
			{
			addCriterion("name in", values, "name");
			return (Criteria) this;
			}

		public Criteria andNameNotIn(List<String> values)
			{
			addCriterion("name not in", values, "name");
			return (Criteria) this;
			}

		public Criteria andNameBetween(String value1, String value2)
			{
			addCriterion("name between", value1, value2, "name");
			return (Criteria) this;
			}

		public Criteria andNameNotBetween(String value1, String value2)
			{
			addCriterion("name not between", value1, value2, "name");
			return (Criteria) this;
			}

		public Criteria andCreatedAtIsNull()
			{
			addCriterion("created_at is null");
			return (Criteria) this;
			}

		public Criteria andCreatedAtIsNotNull()
			{
			addCriterion("created_at is not null");
			return (Criteria) this;
			}

		public Criteria andCreatedAtEqualTo(Date value)
			{
			addCriterion("created_at =", value, "createdAt");
			return (Criteria) this;
			}

		public Criteria andCreatedAtNotEqualTo(Date value)
			{
			addCriterion("created_at <>", value, "createdAt");
			return (Criteria) this;
			}

		public Criteria andCreatedAtGreaterThan(Date value)
			{
			addCriterion("created_at >", value, "createdAt");
			return (Criteria) this;
			}

		public Criteria andCreatedAtGreaterThanOrEqualTo(Date value)
			{
			addCriterion("created_at >=", value, "createdAt");
			return (Criteria) this;
			}

		public Criteria andCreatedAtLessThan(Date value)
			{
			addCriterion("created_at <", value, "createdAt");
			return (Criteria) this;
			}

		public Criteria andCreatedAtLessThanOrEqualTo(Date value)
			{
			addCriterion("created_at <=", value, "createdAt");
			return (Criteria) this;
			}

		public Criteria andCreatedAtIn(List<Date> values)
			{
			addCriterion("created_at in", values, "createdAt");
			return (Criteria) this;
			}

		public Criteria andCreatedAtNotIn(List<Date> values)
			{
			addCriterion("created_at not in", values, "createdAt");
			return (Criteria) this;
			}

		public Criteria andCreatedAtBetween(Date value1, Date value2)
			{
			addCriterion("created_at between", value1, value2, "createdAt");
			return (Criteria) this;
			}

		public Criteria andCreatedAtNotBetween(Date value1, Date value2)
			{
			addCriterion("created_at not between", value1, value2, "createdAt");
			return (Criteria) this;
			}

		public Criteria andUpdatedAtIsNull()
			{
			addCriterion("updated_at is null");
			return (Criteria) this;
			}

		public Criteria andUpdatedAtIsNotNull()
			{
			addCriterion("updated_at is not null");
			return (Criteria) this;
			}

		public Criteria andUpdatedAtEqualTo(Date value)
			{
			addCriterion("updated_at =", value, "updatedAt");
			return (Criteria) this;
			}

		public Criteria andUpdatedAtNotEqualTo(Date value)
			{
			addCriterion("updated_at <>", value, "updatedAt");
			return (Criteria) this;
			}

		public Criteria andUpdatedAtGreaterThan(Date value)
			{
			addCriterion("updated_at >", value, "updatedAt");
			return (Criteria) this;
			}

		public Criteria andUpdatedAtGreaterThanOrEqualTo(Date value)
			{
			addCriterion("updated_at >=", value, "updatedAt");
			return (Criteria) this;
			}

		public Criteria andUpdatedAtLessThan(Date value)
			{
			addCriterion("updated_at <", value, "updatedAt");
			return (Criteria) this;
			}

		public Criteria andUpdatedAtLessThanOrEqualTo(Date value)
			{
			addCriterion("updated_at <=", value, "updatedAt");
			return (Criteria) this;
			}

		public Criteria andUpdatedAtIn(List<Date> values)
			{
			addCriterion("updated_at in", values, "updatedAt");
			return (Criteria) this;
			}

		public Criteria andUpdatedAtNotIn(List<Date> values)
			{
			addCriterion("updated_at not in", values, "updatedAt");
			return (Criteria) this;
			}

		public Criteria andUpdatedAtBetween(Date value1, Date value2)
			{
			addCriterion("updated_at between", value1, value2, "updatedAt");
			return (Criteria) this;
			}

		public Criteria andUpdatedAtNotBetween(Date value1, Date value2)
			{
			addCriterion("updated_at not between", value1, value2, "updatedAt");
			return (Criteria) this;
			}
		}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table ph2_sensors
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	public static class Criterion
		{
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition()
			{
			return condition;
			}

		public Object getValue()
			{
			return value;
			}

		public Object getSecondValue()
			{
			return secondValue;
			}

		public boolean isNoValue()
			{
			return noValue;
			}

		public boolean isSingleValue()
			{
			return singleValue;
			}

		public boolean isBetweenValue()
			{
			return betweenValue;
			}

		public boolean isListValue()
			{
			return listValue;
			}

		public String getTypeHandler()
			{
			return typeHandler;
			}

		protected Criterion(String condition)
			{
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
			}

		protected Criterion(String condition, Object value, String typeHandler)
			{
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>)
				{
				this.listValue = true;
				}
			else
				{
				this.singleValue = true;
				}
			}

		protected Criterion(String condition, Object value)
			{
			this(condition, value, null);
			}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler)
			{
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
			}

		protected Criterion(String condition, Object value, Object secondValue)
			{
			this(condition, value, secondValue, null);
			}
		}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ph2_sensors
     *
     * @mbg.generated do_not_delete_during_merge Thu Jul 06 19:21:57 JST 2023
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }
}