package com.logpose.ph1.api.dao.db.mappers;

import com.logpose.ph1.api.dao.db.entity.MessagesEnyity;
import com.logpose.ph1.api.dao.db.entity.MessagesEnyityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MessagesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messages
     *
     * @mbg.generated
     */
    long countByExample(MessagesEnyityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messages
     *
     * @mbg.generated
     */
    int deleteByExample(MessagesEnyityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messages
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messages
     *
     * @mbg.generated
     */
    int insert(MessagesEnyity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messages
     *
     * @mbg.generated
     */
    int insertSelective(MessagesEnyity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messages
     *
     * @mbg.generated
     */
    List<MessagesEnyity> selectByExample(MessagesEnyityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messages
     *
     * @mbg.generated
     */
    MessagesEnyity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messages
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") MessagesEnyity row, @Param("example") MessagesEnyityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messages
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") MessagesEnyity row, @Param("example") MessagesEnyityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messages
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MessagesEnyity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messages
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MessagesEnyity row);
}