package com.logpose.ph2.batch.dao.db.mappers;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.logpose.ph2.batch.dao.db.entity.Ph2ParamsetPsWeibullEntity;
import com.logpose.ph2.batch.dao.db.entity.Ph2ParamsetPsWeibullEntityExample;
@Mapper
public interface Ph2ParamsetPsWeibullMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_paramset_ps_weibull
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	long countByExample(Ph2ParamsetPsWeibullEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_paramset_ps_weibull
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	int deleteByExample(Ph2ParamsetPsWeibullEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_paramset_ps_weibull
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	int deleteByPrimaryKey(Long paramsetId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_paramset_ps_weibull
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	int insert(Ph2ParamsetPsWeibullEntity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_paramset_ps_weibull
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	int insertSelective(Ph2ParamsetPsWeibullEntity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_paramset_ps_weibull
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	List<Ph2ParamsetPsWeibullEntity> selectByExample(
			Ph2ParamsetPsWeibullEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_paramset_ps_weibull
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	Ph2ParamsetPsWeibullEntity selectByPrimaryKey(Long paramsetId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_paramset_ps_weibull
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	int updateByExampleSelective(@Param("row") Ph2ParamsetPsWeibullEntity row,
			@Param("example") Ph2ParamsetPsWeibullEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_paramset_ps_weibull
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	int updateByExample(@Param("row") Ph2ParamsetPsWeibullEntity row,
			@Param("example") Ph2ParamsetPsWeibullEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_paramset_ps_weibull
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	int updateByPrimaryKeySelective(Ph2ParamsetPsWeibullEntity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_paramset_ps_weibull
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	int updateByPrimaryKey(Ph2ParamsetPsWeibullEntity row);
}