package com.logpose.ph2.batch.dao.db.mappers;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.logpose.ph2.batch.dao.db.entity.Ph2SensorContentsEntity;
import com.logpose.ph2.batch.dao.db.entity.Ph2SensorContentsEntityExample;
@Mapper
public interface Ph2SensorContentsMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_sensor_contents
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	long countByExample(Ph2SensorContentsEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_sensor_contents
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	int deleteByExample(Ph2SensorContentsEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_sensor_contents
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_sensor_contents
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	int insert(Ph2SensorContentsEntity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_sensor_contents
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	int insertSelective(Ph2SensorContentsEntity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_sensor_contents
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	List<Ph2SensorContentsEntity> selectByExample(
			Ph2SensorContentsEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_sensor_contents
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	Ph2SensorContentsEntity selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_sensor_contents
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	int updateByExampleSelective(@Param("row") Ph2SensorContentsEntity row,
			@Param("example") Ph2SensorContentsEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_sensor_contents
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	int updateByExample(@Param("row") Ph2SensorContentsEntity row,
			@Param("example") Ph2SensorContentsEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_sensor_contents
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	int updateByPrimaryKeySelective(Ph2SensorContentsEntity row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ph2_sensor_contents
	 * @mbg.generated  Thu Aug 03 01:50:05 JST 2023
	 */
	int updateByPrimaryKey(Ph2SensorContentsEntity row);
}